### ISSUE TITLE
Feature: Check out as *.ipynb (e.g., .py.ipynb), check in as * (e.g., .py)

### ISSUE THREAD

**Issue by JERisBRISK** [paiqo/Databricks-VSCode#10]
_I'm hoping to use your awesome extension as the backbone of a multi-developer CI/CD experience. Thanks so much for all the heavy lifting here -- this extension is **seriously** a **huge** time saver already!_

**tl;dr - A feature that (if enabled) let's us _edit_ in .ipynb format but _save_ in .py format!**

**Background**
In experimenting using this for CI / CD and Pull Requests against the ADO Git repositories that reflect our Databricks environments, we already had most of our Notebooks saved in .py format. (Since it's the only sane choice for Code Review). The extension honors this, seeing that the local .py file exists when downloading new versions and not downloading the .py.ipynb version. That's good, but it's not quite what we're after...

The complications we experienced trying to use this for a proper code-reviewed, CI/CD workflow:
- VS Code editing of **.py** format is tedious and error-prone and doesn't mimic the Databricks experience. This increases drag.
- If you have a **.py** file locally that represents a notebook, Databricks VSCode is smart enough to download updates in that format. However, if you have a *new* notebook, it uses the **...exportFormat**. This is fine for edits and uploads directly to Databricks (yay), but if you're trying to also do CI / CD with a human code-reviewed Pull Request in the middle... **.ipynb** format is not your friend, as it renders as a single line of JSON with islands of HTML embedded therein.

Thus, our request is simple - let us _edit_ in .ipynb format and _save_ in .py format (similar to how Git lets you auto-convert line endings between Windows and Unix).

**Ideas for Implementation**
Here's some rough guesses at how this could work:
- Have a **...localWorkingFolder** config value and all "downloads" go under that directory in the ***.ipynb** format.
- Introduce a new "Sync" button (perhaps use a Git branch style icon ![PR icon](https://img.icons8.com/ios/0.5x/pull-request.png)?) that flushes the working notebook (or a directory, or the whole localWorkingFolder) over to one or more **.py** files in the **localSyncFolder** (where the user's git repo likely is).
- Since offline conversion to and from the formats (e.g., .py <-> .ipynb) may not be available or desirable to implement, consider leveraging whatever facility Databricks provides for this -- perhaps upload the notebook(s) into a temporary version (in **.ipynb** format), and then download the notebook as the (e.g.) **.py** format for saving to the local git repo?

**Related Requests / Ideas**
- Add an option that always performs this convert-and-flush to local git repo whenever a notebook is saved

**Comment by gbrueckl** [comment]
Hi Jeremy,
thats actually very common feedback that we get. Notebooks are the preferred way to edit/work with Databricks but they cannot be used efficiently in combination with GIT and/or CI/CD. 

In general, there are multiple tools involved in the whole process (Databricks, VS Code, this extension, your GIT provider, ...) and there could be multiple viable solutions. For example, some tools do support proper comparison also for notebooks so that may also be an option. Speaking for this extension, we try to keep the interfaces and functionality to what the extension is designed for - leveraging the Databricks REST API in VS Code. 

However, as this is a very common requirement that totally makes sense, we will and already are actively looking into solving this and your proposed solution is also something we already considered. 

I will keep you updated here!

**Comment by JERisBRISK** [comment]
Thanks, @gbrueckl !  Looking forward to whatever solution y'all come up with. Thanks again for the amazing extension.  Questions that emerge:

- Do you have any idea what your ETA for such a feature is? 😸 
- In the meanwhile, what tools are you referencing that supports proper comparison?  (Our organization has standardized on ADO, so hopefully whatever is out there for diffing notebooks could be plugged in or integrated there...)

**Comment by gbrueckl** [comment]
no ETA yet, need to evaluate it first 

in the meantime, here are some tools for DIFF on notebooks:
https://nbdime.readthedocs.io/en/latest/
https://towardsdatascience.com/introducing-reviewnb-visual-diff-for-jupyter-notebooks-6797e6dfa20c
but you will find much more on Google

another workaround would be to do what you already suggested (letting Databricks do the conversion) by simply having two connections/environments to the same Databricks workspace but each configured with a different exportFormat - e.g. one with ".py" and one with ".py.ipynb"
Then you can develop locally in your ".py.ipynb" environment, upload your notebook to databricks and use the second environment to download it again as ".py" and check it in to GIT

**Comment by gbrueckl** [comment]
@JERisBRISK 
how about this workflow:
you edit a notebook (.ipynb) locally in VS Code. Once you upload it - presumably to your DEV Databricks workspace - it gets downloaded directly after automatically again as .py into a separate folder to be checked in to GIT?

**Comment by chelnak** [comment]
Hello! Did anything move forward with this issue? 

Having to do the manual conversion potentially introduces risk if your notebook state contains IDD or data that you do not wish to commit.

**Comment by gbrueckl** [comment]
Hi Craig,
I thought about it and the root issue is not really related to this extension. You want to work with notebooks but check in .py files which is nothing this extension was initially designed for.
There are converters out there that do exactly this for you. So you should one of those, convert all notebooks to .py files before checking them in, ideally also excluding notebooks via gitignore.
This adds one additional step to your work flow before checking your files in which should be doable. Maybe there is even a tool that does this for you automatically but it will not be covered by this extension any time soon.
The workaround provided above is also still an option.

-gerhard

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by chelnak** [comment]
Hey @gbrueckl thanks for the quick (and understandable) response. Maybe a pre-commit hook could work here too.

KR,
Craig

**Comment by gbrueckl** [comment]
closing this with the explanations above
