### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'data') when trying to read parquet file

### ISSUE THREAD

**Issue by minhhieutran2112** [paiqo/Databricks-VSCode#100]
Hi,

When trying to run pd.read_parquet to import a parquet file from my database, it raised a type error: TypeError: Cannot read properties of undefined (reading 'data').

Every other functionality of the extension works fine (i.e. I can sync repo, connections, workspaces, clusters etc.).

Can you please advise?

Thanks!
![image](https://user-images.githubusercontent.com/46810422/194871452-debad543-5104-4fda-a6ec-c96f021abd0c.png)

**Comment by gbrueckl** [comment]
can you please check the output of the extension via the dedicated output-channel in VSCode:
![image](https://user-images.githubusercontent.com/11884402/194872151-541f1d09-c7b4-4304-82ab-0db7706651d5.png)

**Comment by minhhieutran2112** [comment]
Here's when the request finished
![image](https://user-images.githubusercontent.com/46810422/194878988-d9e58f50-78bd-47c9-a094-f5256d345f6f.png)

**Comment by minhhieutran2112** [comment]
Running it again raised this. Most of the time it raised this error
![image](https://user-images.githubusercontent.com/46810422/194880763-bda1c90f-9ec7-4ede-b56c-eaf28d3d95d0.png)

**Comment by gbrueckl** [comment]
hmm, could it be that the result is quite big and takes more than 15 seconds to transfer to your client?

**Comment by gbrueckl** [comment]
we are not actively setting a timeout on any of our calls. Could also be that there is a timeout on Databricks side but I could not find any documentation about this 
However, I will see what I can find out - but this will take some time

In general I would recommend filtering the dataframe before displaying it

**Comment by gbrueckl** [comment]
if the error were from the command itself, the message would be different - it is definitely a connectivity issue

do you actually display the dataframe in the end?
Or is it really only that simple assignment you posted in the beginning?

**Comment by gbrueckl** [comment]
thats weird, as it should not produce any output that is returned from Databricks 
the only thing I can think of is that the cluster was changed (restarted, stopped, edited, not yet started) etc. while the code was running
on a cluster that you are using on your own the command should not run very long nor cause issues when returning the "result" (which is empty)

**Comment by minhhieutran2112** [comment]
I'll try restarting the cluster and rerun the command a couple of times to see if the problem is still there. Will keep you updated.

Thanks!

**Comment by gbrueckl** [comment]
any update on this?

**Comment by gbrueckl** [comment]
I ran some more tests and it is actually fine if a command runs 60+ seconds
When we run your command on the cluster, this is asynchronous, so we just start it and let it run
then, every second we check whether it has finished yet 
in your particular case that check whether the command has already finished timed out, which is a super simple API call, especially if there is no result to display. 

This concludes to me that it has nothing to do with your code nor with the VSCode extension but is more like a network issue on either your side or on Databricks
