### ISSUE TITLE
Can we create a branch and commit it from Databricks-VsCode?

### ISSUE THREAD

**Issue by guilhermeparreira** [paiqo/Databricks-VSCode#103]
I found fantastic this extension for VsCode.

I want to know whether I can create a branch and commit it from VsCode extension?

Or do I need to do theses processes on Web? (Ex.: Once I created the branch online, I can download the notebook work on VsCode, upload back and then commit via Web?)

Also, what does the `check-out` button in `Repos` mean?
![image](https://user-images.githubusercontent.com/13880005/198129409-1b190a41-4b17-4e81-a0da-5ed5d45476cb.png)

Thanks in advance!

**Comment by gbrueckl** [comment]
unfortunately, the [Databricks Repos API ](https://docs.databricks.com/dev-tools/api/latest/repos.html) is quite limited here and only allows a very small subset of the Git Operations which are basically all already implemented

The `Check-Out` button allows you to change your current repository to another branch or tag whereas `Pull` just pulls the latest version of your currently selected branch/tag

**Comment by drorcohengithub** [comment]
@gbrueckl I'm confused as to how the version control should be working. I had expected that working on vscode any changes I make would be "commitable" in some way. Instead I see that my changes are synced with the corresponding branch on databricks. But as far as I can tell those syncs are not version controlled anywhere. 

Did I miss something?

**Comment by gbrueckl** [comment]
no, you did not miss anything. As I said in the previous command, there is currently no way to commit changes to a branch via the [Databricks Repos API](https://docs.databricks.com/dev-tools/api/latest/repos.html) hence this extension also cannot provide this functionality (yet).
I hope that this will be added in the near future so we can also provide you with that functionality from within VSCode

**Comment by drorcohengithub** [comment]
Got it. I see that the databricks repos api is limited, but isn't it possible to do everything thru github and forget about databricks repo aip? 

As part of my current workflow I have the repo I work on in databricks cloned locally. When I make changes locally I push them to github and then pull from databricks. So it seems to me that if could somehow "point" the extension to my already cloned repo everything should work. Anyhow, I'm sure you've thought of this 😆 

Thanks for the extension 🙏

**Comment by gbrueckl** [comment]
technically you can store your files anywhere on your disk and still execute them against a Databricks Cluster using the notebook kernels provided by this extension.
However, some specific commands may not work as expected - mainly `%run`, `dbutils.notebook.run(...)` and potentially Files in Repos

To make this work you could use the [Workspace Manager](https://github.com/paiqo/Databricks-VSCode#workspace-manager) and configure your `localSyncFolder` so it is aligned with your git repo:
assuming your `localSyncFolder` is `C:\databricks` you would need to move your local github repo into `C:\databricks\Workspace\Repos\<folderOfYourRepoOnDatabricks>\<NameOfYourRepoOnDatabricks>\`

with this setup the above mentioned limitations should work again and you can commit your code using your local git tools. On Databricks you can then pull the latest changes (or use the [Repo Manager](https://github.com/paiqo/Databricks-VSCode#repo-manager) from this extension to do so)

**Comment by gbrueckl** [comment]
just leaving this open in case the [Databricks Repos API](https://docs.databricks.com/dev-tools/api/latest/repos.html) ever supports commits

**Comment by abitbetter** [comment]
hi, I wonder if there exists any possibility of using a git client in some way.

Let me explain:
- I can use your extension and work with databricks Repos folder both on workspace manager or file manager.  By working this way I have no .git folder in my local Repos path, so I need to rely on databricks web ui to commit, push, etc.
- I have tried to use a folder on my own, under de localSyncFolder so I could have a .git folder and commit, push, etc without relying on databricks web ui and relying on vscode (for example).  I managed to do this, but I loose the feature given by databricks of converting .ipynb to .py and viceversa when working with git, being a complete mess when looking for changes within a file.

Is there a way of having the best of both worlds or sadly I need to choose between:
- having .ipynb to .py conversion relying on databricks repos ui
- not having .ipynb to .py conversion without the need of relying on databricks repos ui and being able to use a git clilent of my own

Thank you in advance!

**Comment by gbrueckl** [comment]
well, if you download the notebooks as `.ipynb`, they are stored locally a JSON and this will also show up in diff views like this. I agree that this might not be the best way to compare differences, especially if the JSON/ipynb also contains the outputs of the cells
However, there should be git clients or diff tools that handle this for you?

**Comment by next-guillermofernandez** [comment]
Hi Gerhard, thank you for you answer.

Although I am searching for the full pack.  This is:
- I want to work with ipynb on my local
- I want them to be transformed to .py automatically when pushing changes to git
- I want the .py to be transformed to .ipynb automatically when I clone or pull changes from git
- I want to be able to look for diff of my ipynb against git, as we can easily do with .py when working with git
- I want to be able to run notebooks remotely on databricks as your extension enables.

I think your suggestion is great, but it implies the manual work of downloading the notebooks as notebooks.  Added the fact of being messy to store JSON in git so a user that checks git with the web ui wouldn't be able to see a readable format.

Maybe all of this is possible and the only issue here is my own ignorance :)

**Comment by abitbetter** [comment]
Hi Gerhard, thank you for you answer.

Although I am searching for the full pack. This is:

I want to work with ipynb on my local
I want them to be transformed to .py automatically when pushing changes to git
I want the .py to be transformed to .ipynb automatically when I clone or pull changes from git
I want to be able to look for diff of my ipynb against git, as we can easily do with .py when working with git
I want to be able to run notebooks remotely on databricks as your extension enables.
I think your suggestion is great, but it implies the manual work of downloading the notebooks as notebooks. Added the fact of being messy to store JSON in git so a user that checks git with the web ui wouldn't be able to see a readable format.

Maybe all of this is possible and the only issue here is my own ignorance :)

**Comment by gbrueckl** [comment]
while I definitely understand your point, I am afraid thats nothing that can be solved by this extension.
it is more like a git problem or with your workflow

I have an idea how I could open regular `.py` files downloaded from Databricks as a notebook but this will take some time to be implemented

**Comment by abitbetter** [comment]
Thank you again Gerhard!

Motivated by your previous suggestion I am doing some research and just found Jupytext.  It might make the hack in some way by maintaining a sync between a .ipynb and a .py locally so it might be possible to work with .ipynb locally but only do commit, push, etc of the .py automatically synchronized with the .ipynb.

I will give it a try, although what doesn't convince me a priori is that it can add a new possible point of failure.
