### ISSUE TITLE
Can we have a default cluster after open a notebook file?

### ISSUE THREAD

**Issue by guilhermeparreira** [paiqo/Databricks-VSCode#104]
Hi there!

When I open or download a notebook file from my workspace, the server is always local (and then I change to the databricks cluster I want):
 
![image](https://user-images.githubusercontent.com/13880005/198128781-3e62443a-d64d-40c2-87c8-cafe7df65b11.png)

As I always work with the same cluster, I was wondering if I could set a cluster to attach by default to all my notebook files from databricks.

Tks in advance.

**Comment by gbrueckl** [comment]
actually VSCode should remember the cluster that was used for a given notebook and pick it automatically the next time you open the notebook

regarding a default cluster: this is probably not something we will add as it is a very specific requirement. What we are thinking of though is to make the Databricks clusters more present in the list and eventually select the first one available automatically once you open a notebook

**Comment by gbrueckl** [comment]
Databricks clusters should now appear on top when opening a notebook from `dbws:/` for from the `localSyncFolder`
