### ISSUE TITLE
Linting and Local Development

### ISSUE THREAD

**Issue by parsatorb** [paiqo/Databricks-VSCode#105]
Hey, I'm new to this project, but I wanted to drop this issue here as a feature request (that I may or may not have time to help implement). 

Given that you can mount workspaces and repos as a live filesystem, I was wondering if there was a way to have an entire repo actually downloaded and cached (while synced) so that you could run linting operations and other quick development changes.

**Comment by gbrueckl** [comment]
did you have a look at the [Workspace Manager](https://github.com/paiqo/Databricks-VSCode#workspace-manager) yet?
it basically allows you to do exactly that (well, except for the automated sync) - what do you think?

**Comment by slowder-bpcs** [comment]
In running the linting operations against all your notebooks and repositories, are you looking to improve the quality of your code? Are you open to coupling the linter with a human to work out changes?

In your scenario, are the notebooks you're looking for lint on analysis or data engineering notebooks?

**Comment by gbrueckl** [comment]
closing due to missing update
