### ISSUE TITLE
Running a notebook from VSCode has different cwd than on the Databricks website

### ISSUE THREAD

**Issue by halkony** [paiqo/Databricks-VSCode#107]
My team has written some modules that this extension fails to import.

When I run the notebook through the databricks site, my cwd is:
/Workspace/Repos/(my username)/(My repo)/...

Running from this extension its:
/databricks/driver

Any way to change this?

**Comment by gbrueckl** [comment]
Hi @halkony, this is something that should work the very same way as it does in the Databricks Web UI
Whenever a notebook from the Repos folder is opened, we set the working directory accordingly and also append the root of your repo to the `sys.path`
https://github.com/paiqo/Databricks-VSCode/blob/master/src/vscode/notebook/DatabricksKernel.ts#L180

parts of this only works if you are using a Databricks Cluster Runtime 11.0+
during my tests with 11.3 LTS it worked just fine
on 10.4 LTS it fails as you cannot change the directory to `/Workspace` there due to some permissions issues

for more details on whats actually happening when you execute your code you can also have a look at the Output tab selecting `paiqo.databricks-vscode` output

**Comment by halkony** [comment]
My runtime is older than 10.4 -- it's 9.1 :(

On my setup, I can manually change to the workspace folder with os.chdir so it isn't a permissions problem.
Didnt notice anything notable in the extension output.

**Comment by gbrueckl** [comment]
just ran some tests with different runtimes on Databricks Web UI using Azure Databricks:
- 9.1 LTS -> `/databricks/driver`
- 10.4 LTS -> `/databricks/driver`
- 11.3 LTS -> `/Workspace/Repos/<myUser>/<myRepo>/<MyFolder>`

also, only on 11.3 LTS I can run `os.chdir("/Workspace/Repos/<myUser>/<myRepo>/<MyFolder>")`, on all older runtimes I get a permission issue so I am a bit surprise why it would work on your side 

thats the error I see in the extension output when running the code on 9.1 LTS:
```
NotebookKernel: Setting up FilesInRepo support for dbws:/Repos/Main/DatabricksTEST/MyNotebook.ipynb
POST 1.2/commands/execute --> {"clusterId":"1115-194844-n1f6bt5s","language":"python","contextId":"8808294538429471693","command":"import sys\nimport os\nsys.path.append('/Workspace/Repos/Main/DatabricksTEST')\nos.chdir('/Workspace/Repos/Main/DatabricksTEST')"}
Response: {"id":"6d1a7909-42db-424e-8d9e-b8a5b968ed8b"}
GET 1.2/commands/status --> {"clusterId":"1115-194844-n1f6bt5s","contextId":"8808294538429471693","commandId":"6d1a7909-42db-424e-8d9e-b8a5b968ed8b"}
Response: {"id":"6d1a7909-42db-424e-8d9e-b8a5b968ed8b","status":"Queued","results":null}
GET 1.2/commands/status --> {"clusterId":"1115-194844-n1f6bt5s","contextId":"8808294538429471693","commandId":"6d1a7909-42db-424e-8d9e-b8a5b968ed8b"}
Response: {"id":"6d1a7909-42db-424e-8d9e-b8a5b968ed8b","status":"Finished","results":{"resultType":"error","summary":"<span class=\"ansi-red-fg\">BlockingIOError</span>: [Errno 11] Resource temporarily unavailable: &#39;/Workspace/Repos/Main/DatabricksTEST&#39;","cause":"---------------------------------------------------------------------------\nBlockingIOError                           Traceback (most recent call last)\n<command--1> in <module>\n      2 import os\n      3 sys.path.append('/Workspace/Repos/Main/DatabricksTEST')\n----> 4 os.chdir('/Workspace/Repos/Main/DatabricksTEST')\n\nBlockingIOError: [Errno 11] Resource temporarily unavailable: '/Workspace/Repos/Main/DatabricksTEST'"}}
<span class="ansi-red-fg">BlockingIOError</span>: [Errno 11] Resource temporarily unavailable: &#39;/Workspace/Repos/Main/DatabricksTEST&#39;
---------------------------------------------------------------------------
BlockingIOError                           Traceback (most recent call last)
<command--1> in <module>
      2 import os
      3 sys.path.append('/Workspace/Repos/Main/DatabricksTEST')
----> 4 os.chdir('/Workspace/Repos/Main/DatabricksTEST')

BlockingIOError: [Errno 11] Resource temporarily unavailable: '/Workspace/Repos/Main/DatabricksTEST'
```
`
as this is very much related to an older runtime which does not support all features I will close this issue.
If you want to use the latest features of Databricks and also this VSCode extension, please use a newer runtime

**Comment by halkony** [comment]
Hi Gerhard,

I started a cluster with the 11.3 runtime and have re-encountered this issue.

![image](https://user-images.githubusercontent.com/15790371/204614452-14f0e6e2-91b9-4baa-ac0b-67b50d83665c.png)

**Comment by halkony** [comment]
I have strangely confirmed that I do not encounter this issue on 10.4 LTS

**Comment by gbrueckl** [comment]
Please use `%pip install` instead of `%python pip install`
There is some special logic that runs when, you use the `%pip` magic that resets the working directory

**Comment by marvinbernhardt** [comment]
I think I have the same problem. On Databricks Web UI:
```python
>>> os.path.abspath('')
/Workspace/Repos/<username>/<repo>/<folder>/
```
In VS Code using the Databricks kernel
```python
>>> os.path.abspath('')
/databricks/driver
```

I don't think I use `%python pip install` anywhere, I only have `pip install -r req.txt` in the clusters init script, and my runtime is 12.2 LTS.

Can this be reopened or should I make a new issue?

**Comment by gbrueckl** [comment]
please create a new issue
you used the same for both executions, right?

**Comment by marvinbernhardt** [comment]
I did. If I can provide any more info, let me know.

**Comment by gbrueckl** [comment]
please check the log for `paiqo.databricks-vscode`
there should be some API calls where we run `sys.path.append` and `os.chdir` to mimic the behavior of DAtabricks
I assume they fail for some reason hence it is not working

are you maybe using "Files in Workspaces" ?

it should definitely work for "Files in Repos" 

users also reported issues with different Cluster DBR versions where some did work and some did not
