### ISSUE TITLE
_sqldf usage 

### ISSUE THREAD

**Issue by atakanokan** [paiqo/Databricks-VSCode#109]
Is there a way to use the output of SQL cells like in the UI? The UI outputs `_sqldf` to be usable in the other cells with `python`.

**Comment by gbrueckl** [comment]
guess you are talking about this feature: https://learn.microsoft.com/en-us/azure/databricks/notebooks/notebooks-use#--explore-sql-cell-results-in-python-notebooks-natively-using-python

I already have some code to make this work - will be released in the next version then

**Comment by atakanokan** [comment]
yep exactly. great extension by the way, thanks for the dev work! Will keep the issue open for now, to be closed with the feature merge.

**Comment by gbrueckl** [comment]
`v1.3.0` was just released and `_sqldf` should work now!

**Comment by gbrueckl** [comment]
Closing as fixed

**Comment by atakanokan** [comment]
Thank you @gbrueckl !
