### ISSUE TITLE
Icons for Online Only (etc) should propogate up the tree

### ISSUE THREAD

**Issue by JERisBRISK** [paiqo/Databricks-VSCode#11]
Consider these folders:
![image](https://user-images.githubusercontent.com/14815901/78924981-832d2380-7a4f-11ea-9a68-d26813fb56f8.png)

Which of these have notebooks that are **Online Only**? 

If you said 'Users' you'd be right, but only partly so.

Now re-consider the same folders:
![image](https://user-images.githubusercontent.com/14815901/78925055-a48e0f80-7a4f-11ea-8fca-e3de0a0cef9b.png)

Suggestion
Have a version of the "red diamond" icon (perhaps a 50% alpha / transparent red diamond?) used for every parent folder that has children which have **Online Only** contents.  E.g.:

![image](https://user-images.githubusercontent.com/14815901/78925828-e8354900-7a50-11ea-9667-dd25373a7a5a.png)

**Comment by gbrueckl** [comment]
thanks for the good feedback - again
at the moment the online/offline status is calculated on an item level (file or folder) but not recursively as this could get quite complex. 
Consider a folder that exists online and also offline and you have a file that only exists online and another one that only exists offline.
what should we display then?

**Comment by gbrueckl** [comment]
after some investigation - to enable this feature would mean that we need to recursively browse/download and compare the whole workspace which is not feasible
so this feature will not be implemented
