### ISSUE TITLE
Cannot work with .py file

### ISSUE THREAD

**Issue by totocto** [paiqo/Databricks-VSCode#110]
Hello,
I got a problem for working with .py file:

![arborescence](https://user-images.githubusercontent.com/48205056/203281371-78bdd233-b9e4-43b3-8958-8515370d9719.PNG)

Here I am trying to import lib_low_frequency from main notebook. 

I got the following error:

![image](https://user-images.githubusercontent.com/48205056/203281671-6c669180-2e80-400b-bf7c-054de4641565.png)

When i run it from databricks directly, I have no error.

Any suggestion about this behaviour?

**Comment by shannonlowder** [comment]
I've noticed databricks is sensitive to paths and references to your modules.  I've taken to making sure the **full** path to my code is included in sys.path at the beginning of my scripts to be sure I can include my modules.

```
if "Workspace/Repos/<username>/<repositoryName>/<full>/<module>/<path>" not in sys.path:
    sys.path.append("Workspace/Repos/<username>/<repositoryName>/<full>/<module>/<path>") 
```

That seems to make databricks happy, and I can reference my modules when running in databricks UI or VSC.

**Comment by gbrueckl** [comment]
A very similar code runs automatically in the background when you run a notebook that resides in a Repository.
This is also shown in the logs.

Can you check sys.path in your notebook please?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rkortekaas** [comment]
For me same trouble.

When I do sys.path I get this:
<img width="1967" alt="image" src="https://user-images.githubusercontent.com/3194362/209431398-6ec8ba84-15b4-4c75-a629-a19fa14790a4.png">

I'm connected to a databricks cluster. The last path you see is the correct path in databricks. However, I was under the impression that %run executes local files. So even when connected to a databricks cluster it would use my local file and execute it against the cluster. I cannot see my local path anywhere in sys.path.. Also when i add it manually as suggested above this has no result for finding the module. Only when i reference it explicitly (Repos/<username>/datameer-solution/src/SmartDataPlatform/databricks/workspace/libs/classes) it works. Notice that the above path is without the /Workspace/.

**Comment by gbrueckl** [comment]
the code ultimately runs on the Databricks cluster and of course you cannot *reference* your local code. However, what happens in [Offline-Execution](https://github.com/paiqo/Databricks-VSCode#execution-modes) is that it simply loads the code from the referenced local file and runs it in your current Databricks session. 

This works only if:
- you are using a notebook from your locally synced  workspace using [Workspace Manager](https://github.com/paiqo/Databricks-VSCode#workspace-manager)
- your notebook is part of a repo (one of its parent must be the `Repos` folder)
- the file referenced by `%run` also exists locally/has been synced 
- a cluster runtime DBR 11 or later

**Comment by gbrueckl** [comment]
closing as no further complaints were reported and a fix/workaround/explanation was provided
