### ISSUE TITLE
How to use %run and move up in folder structure

### ISSUE THREAD

**Issue by michaelmiscanuk** [paiqo/Databricks-VSCode#112]
Hi,

I want to use %run with ../ to include file in the outer folder, but have problem running it in VScode.

Here is my example structure:
![image](https://user-images.githubusercontent.com/37830487/203718490-b42be334-74c6-455e-8ca3-f93443ca58fb.png)

Here is what is inside:
my_main_file.ipynb:
![image](https://user-images.githubusercontent.com/37830487/203718734-7f8c64cc-45a8-4aa9-bdec-44fdc55fc0e5.png)
--- as you can see it works for file directly in the folder

my_included_in.ipynb:
![image](https://user-images.githubusercontent.com/37830487/203718866-da142138-f398-440c-950c-64bee6d5ab7e.png)

my_included_out.ipynb:
![image](https://user-images.githubusercontent.com/37830487/203718923-2931d006-1bb9-4e7b-b2d9-dd1b0b3fd156.png)

Can you please suggest how to use it with ../

Thank you! :)

**Comment by gbrueckl** [comment]
Try `./../my_included_out`, this should work

Does your `../my_included_out` work in the Databricks Web UI?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Michael Miscanuk ***@***.***>
Sent: Thursday, November 24, 2022 8:23:27 AM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] How to use %run and move up in folder structure (Issue #112)


Hi,

I want to use %run with ../ to include file in the outer folder, but have problem running it in VScode.

Here is my example structure:
[image]<https://user-images.githubusercontent.com/37830487/203718490-b42be334-74c6-455e-8ca3-f93443ca58fb.png>

Here is what is inside:
my_main_file.ipynb:
[image]<https://user-images.githubusercontent.com/37830487/203718734-7f8c64cc-45a8-4aa9-bdec-44fdc55fc0e5.png>
--- as you can see it works for file directly in the folder

my_included_in.ipynb:
[image]<https://user-images.githubusercontent.com/37830487/203718866-da142138-f398-440c-950c-64bee6d5ab7e.png>

my_included_out.ipynb:
[image]<https://user-images.githubusercontent.com/37830487/203718923-2931d006-1bb9-4e7b-b2d9-dd1b0b3fd156.png>

Can you please suggest how to use it with ../

Thank you! :)

**Comment by michaelmiscanuk** [comment]
Yes, this work in VSCode and in Web UI: `./../my_included_out` . Thanks
