### ISSUE TITLE
VScode Notebook Is not refreshing when did some changes in web UI (same notebook)

### ISSUE THREAD

**Issue by michaelmiscanuk** [paiqo/Databricks-VSCode#114]
Hi,

I have opened both same notebooks -  once in VScode and once in Web UI. When I do some changes to web UI, they are not immediately reflected in VSCode, so now when I do some changes in VSCode - and save - those previous changes from WEB UI are overwritten.

I found some workarounds, but those are easy to forget (for example to switch to other tab in VSCode and back, will get me changes from Web UI)

Is here some better way? Some setup, to refresh my page on changes from Web UI?

Thank you :)

**Comment by gbrueckl** [comment]
I am afraid there is no real solution to this problem as the underlying Databricks APIs only support full overwrites in both directions so there will never be a real co-editing/co-authoring capabilities between vscode and web ui as of now. The last save always overwrites intermediate changes.

The web ui is better here as it immediately reflects changes that got uploaded from VSCode, in VSCode this is a bit more tricky as we would need to constantly check for changes which is neither feasible, nor does it solve the next problem of syncing/merging changes, which is another completely different topic.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Michael Miscanuk ***@***.***>
Sent: Saturday, November 26, 2022 1:33:24 PM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] VScode Notebook Is not refreshing when did some changes in web UI (same notebook) (Issue #114)


Hi,

I have opened both same notebooks - once in VScode and once in Web UI. When I do some changes to web UI, they are not immediately reflected in VSCode, so now when I do some changes in VSCode - and save - those previous changes from WEB UI are overwritten.

I found some workarounds, but those are easy to forget (for example to switch to other tab in VSCode and back, will get me changes from Web UI)

Is here some better way? Some setup, to refresh my page on changes from Web UI?

Thank you :)
