### ISSUE TITLE
Can't download folders from workspace

### ISSUE THREAD

**Issue by jayrar** [paiqo/Databricks-VSCode#115]
Hello, This tool is really helpful thanks !

I've got an issue when I try to download folders from a workspace I get an error : 

Error running command databricksWorkspaceItem.download: Cannot read properties of null (reading 'path'). This is likely caused by the extension that contributes databricksWorkspaceItem.download.

I can download files individually without any issue.
I currently use the databircks CLI connection but I had the same issue with the Vs Code Settings options.
Not sure if it is related to your modules or to vs code in general but I did not find any kind of support.

Thanks in advance !

**Comment by gbrueckl** [comment]
just tried it myself and there seems to be indeed an issue - will have a look and try to provide a fix with the next release

PS: it is not related to the connection manager you use

**Comment by gbrueckl** [comment]
a fix for this was released some days ago - can you please try again?

**Comment by jamjambles** [comment]
I also have this issue with v1.3.0. How can I try the fix which appears to be in v1.3.1?

**Comment by jayrar** [comment]
I only have access to version 1.3.0 also.

**Comment by gbrueckl** [comment]
oh sorry, seems like I forgot to publish it 🙈

just published it now to the gallery and also created a release in the repo

**Comment by jayrar** [comment]
Works fine for me with the new version ! 
Thank you !

**Comment by gbrueckl** [comment]
closing as fixed
