### ISSUE TITLE
Issue using ipywidgets through VSC notebook

### ISSUE THREAD

**Issue by shannonlowder** [paiqo/Databricks-VSCode#116]
Starting with Databricks runtime 11, it supports ipywidgets. I figured this was so that you could write local code with widgets, test there, and then promote to databricks runtime.  What I find when I try to run that code through the VSC extension is an error.
```
Error: class com.databricks.backend.common.rpc.CommandResultMessages$MIMEBundleResult not supported
    at c._doExecution (/Users/slowder/.vscode/extensions/paiqo.databricks-vscode-1.3.0/dist/node/extension.js:2:428689)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at c.executeHandler (/Users/slowder/.vscode/extensions/paiqo.databricks-vscode-1.3.0/dist/node/extension.js:2:424042)
    at m.$executeCells (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:107639)
```

If I open the same code through databricks UI, the ipywidgets render and interact as I would expect.

### test code
```
# COMMAND ----------
import ipywidgets as widgets

# COMMAND ----------
scope = widgets.Text(
    value='',
    placeholder='your email address',
    description='Scope:',
    disabled=False
)

# COMMAND ----------
display(scope)
```

If there's anything I can do to help troubleshoot and fix this bug, please let me know!

**Comment by gbrueckl** [comment]
I am afraid this will never work within the VSCode extension as we are not really using an IPython Kernel in the background but instead simply send the code from the cells to the Databricks Execution REST API

we are looking into enabling widgets somehow also from within VSCode but we will first start with `dbutils.widgets` and if we find a proper solution for that we may further look into Ipywidgets
