### ISSUE TITLE
.ipynb not allowing '%sql' language

### ISSUE THREAD

**Issue by NeilGraham** [paiqo/Databricks-VSCode#117]
Hello, me and my colleagues are trying to execute a SQL query in a Jupyter Notebook (.ipynb) but are not able to with the %sql magic at the top of a Notebook part.

```
%sql
show databases
```
- Does not work when using the VS Code extensions Databricks + Jupyter Notebook.
- Does not stop executing.

![image](https://user-images.githubusercontent.com/9090965/206590462-4d1893ac-71a7-40d9-a1eb-0e9e75904a34.png)
- After finally stopping execution.

**Comment by gbrueckl** [comment]
the first executed statement on a new Kernel/Cluster might take some time (usually <10 seconds) as the session has to be initialized. If the cluster is under load, it might take longer.

besides that, please make sure that:
- you are using a Databricks Cluster Kernel
- you use the `%sql` magic (as its not being used in your screenshot)
- give it some more time, at least for testing this out

are regular PySpark/Python commands working?

**Comment by gbrueckl** [comment]
I had another look and the execution of `%sql` cells really took unnecessarily long which is related to the recent implementation of adding the `_sqldf` for Python cells. However, this did not cause the execution to be cancelled.
This will be fixed in the next release

**Comment by gbrueckl** [comment]
closing as no further complaints were reported and a fix/workaround/explanation was provided
