### ISSUE TITLE
Error with pulling repo

### ISSUE THREAD

**Issue by pwin** [paiqo/Databricks-VSCode#118]
I have the extension listing the repos that my databricks account has cloned, but when clicking the 'pull' icon in the extension REPOS window I get

Error running command databricksRepo.checkOut: Cannot read properties of undefined (reading 'checkOut'). This is likely caused by the extension that contributes databricksRepo.checkOut.

**Comment by gbrueckl** [comment]
so are you running "Pull" or "Check-Out" ? 
Pull would pull the latest changes whereas Check-out would allow you to switch to a different branch/tag

I just tested both on my side and they seem to work as expected.

can you please also provide the output from the logs:
![image](https://user-images.githubusercontent.com/11884402/207000536-870d16b1-923b-49a4-880a-f0b0a481e016.png)

**Comment by gbrueckl** [comment]
closing as no further complaints were reported and a fix/workaround/explanation was provided
