### ISSUE TITLE
NameError: name 'spark' is not defined

### ISSUE THREAD

**Issue by sebcruz** [paiqo/Databricks-VSCode#12]
I cannot run cells of an existing python notebook successfully downloaded from my Databricks instance through your (very cool) extension.  I receive the error below.  I am able to run pyspark commands against databricks through VSCode, outside of your extension.  All indications are that I have successfully connected to my Databricks instance.

spark.range(100).count()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
 in 
----> 1 spark.range(105).count()

NameError: name 'spark' is not defined

**Comment by gbrueckl** [comment]
That's actually related to Databricks-connect and has nothing to do with this extension

When a notebook is executed within the Databricks web service UI, the variable 'spark' is automatically created for you. When you want to run the code from your local IDE you need to initialize it by yourself first:

from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by gbrueckl** [comment]
closed as not related to this extension but to Databricks-Connect
