### ISSUE TITLE
How do I reference files in the mounted workspace?

### ISSUE THREAD

**Issue by wregter** [paiqo/Databricks-VSCode#120]
Hi, 

Amazing work on this extension! 

Could you give me an example of how I can reference the files in the mounted workspace in python code? Is there a certain sys.path I need to append? I am trying to reference modules and csv files that are stored in the sub directories of my repo.

Thank you in advance!

**Comment by gbrueckl** [comment]
well, how would you do it on Databricks directly?
the same way should also work in the extension

if you are working with repos, you can check `/Workspace/...` on your driver as all the code should be there

**Comment by wregter** [comment]
Thanks for the quick reply!

Hmmm, that is not working for me unfortunately. I forgot to mention that I am using a local jupyter kernel instead of a databricks cluster to run it. If I choose the databricks cluster I am indeed able to load the files without issues. However, when choosing the jupyter kernel it cannot find the files, and the working directory is pointing to my C drive. Any tips?

**Comment by gbrueckl** [comment]
if you are using your local jupyter kernel you of course cannot access files on Databricks - how should that work?
the idea of this extension is that you can run your local code against a Databricks cluster using the notebook kernels that are created for you

**Comment by wregter** [comment]
I understand that that is the main aim of the extension, I was just wondering whether the opposite is also possible, where you use your local kernel to run databricks code. I thought you might be able to reference the files that are synced in some way, but I see that this extension was not meant to do this, so I have closed the issue. Thanks for the replies.
