### ISSUE TITLE
Create Cluster link malformed

### ISSUE THREAD

**Issue by shannonlowder** [paiqo/Databricks-VSCode#121]
The URL generated is malformed when you click the add button in the clusters section. The base URL is correct, but the rest needs to be corrected. The extension adds "/%2523create/cluster". I've found that it needs to include "/?o=<workspace ID before the first dot>#create/cluster".

**Comment by gbrueckl** [comment]
this is indeed broken but will be fixed with the next release
the `?o=...` is not necessary and also should not be provided as part of the API root URL

**Comment by gbrueckl** [comment]
fixed and released some time ago
