### ISSUE TITLE
Question: how to know which branch I'm on for the repo

### ISSUE THREAD

**Issue by rhelpacc** [paiqo/Databricks-VSCode#122]
Hi,

I'd like to be able to do git operation of the files on local machine where I use this plugin. But it doesn't seem that the sync folders have information about git branch or it has all the files from the repo. It only has the ones I'm working on. Hence, I cannot do git interaction with it locally. Or is there a way to do this but I am not aware of?

**Comment by gbrueckl** [comment]
there is two ways how you can work with git
- use the Databricks Git Integration
- use your local git client
- (technically you could also use a combination of both)

it seems what you want to do is the local git client where you download the notebooks using the [Workspace Manager](https://github.com/paiqo/Databricks-VSCode#workspace-manager)
To check those files into your git repo, you simply need to sync those files into one of your locally existing git repos. Once you have the files locally you can use them as if they were any other regular source files
