### ISSUE TITLE
Missing Documentation on how to Enable spark Code Completion

### ISSUE THREAD

**Issue by bicaluv** [paiqo/Databricks-VSCode#125]
Installed the extension and connected to my Databricks workspace.
I‘m able to download, edit, and run my notebooks.
But what I do miss (or am lacking knowledge) is, how to configure VSCode (pylance) to support code completion for spark and dbutils types/instances.
Would be great to see this in the documentation.

**Comment by gbrueckl** [comment]
to be honest I am also not quite sure how this is working in VSCode internally. We are basically not doing anything to enable code completion
However, from my experience it sometimes picks up your local Python environment to do the completion so installing PySpark or dbconnect might work - we are also still testing this

**Comment by bicaluv** [comment]
Hm, installed pyspark, dbconnect and dbutils but still get no code completion on my Mac.
I'm really not sure on how this should work, because to run my code I have to select the up and running cluster on Databricks. But when I do this, VSCode has not completion support for my code which makes the extension useless to me.

If you have any clue what I can check to get code completion support, please let me know and I will give it a try.

BTW: having no support for the python code cells is not good, but also having no support for the %sql cells makes it more useless.

**Comment by gbrueckl** [comment]
as long as we are not using a real jupyter kernel but only the API I think it will be hard to get proper code completion. Feel free to talk to Databricks about exposing their kernel that they are using in the background - I would be more than happy to use it.

`%sql` cells should work when executed against a Databricks cluster - please open another issue with the details

**Comment by gbrueckl** [comment]
it partially helps to set `python.defaultInterpreterPath` to a python environment that has things like e.g. PySpark package installed - it will at least know those then
if there is a package for dbutils, this will probably work the same way

**Comment by bicaluv** [comment]
I'll give setting the defaultInterpreterPath a try. What came into my mind was that it might help installing the package in the global python env (knowing that this is no good practice for python)

**Comment by bicaluv** [comment]
But even when defaultInterpreterPath will work, I would have to import spark or dbutils which are implicitly imported when writing native Databricks code cells.

**Comment by gbrueckl** [comment]
Hi @bicaluv,
Databricks recently published its own [VSCode extension](https://marketplace.visualstudio.com/items?itemName=databricks.databricks) which also contains a script that adds auto-completion to all Databricks-specific classes/variables like `spark`, `sqlContext`, `dbutils.XXX`, etc.
if you place [this file](https://github.com/databricks/databricks-vscode/blob/main/packages/databricks-vscode/resources/python/stubs/databricks/sdk/runtime.pyi) in your project, Python should pick it up automatically

or you simply open your existing project in VSCode then open the new official Databricks Extension and it will prompt you to add this file to your project

**Comment by bicaluv** [comment]
Thanks for the hint, I‘ll give it a try.

**Comment by gbrueckl** [comment]
If you install the official Databricks extension it will also prompt you to add the typings to your project. If you do so, the autocomplete for Spark variables should work as expected

**Comment by basso1995** [comment]
Hello, sorry for reopening this, but I'm also struggling finding a way to enable autocompletion for notebooks

![image](https://github.com/paiqo/Databricks-VSCode/assets/101126055/22980fdc-acd2-4bd9-a67a-6fa8fbd34b94)

Your extension is truly amazing and this is the only missing piece we need, to enable syntax highlight and autocompletion while editing and running notebook on the cluster kernel

**Comment by basso1995** [comment]
Actually it's still not working as expected. By doing this workaround I can't import modules I defined in my repo. Do you have any recommended way of working to:
- work within a repository
- have syntax highlight and autocompletion for installed packages (even locally) and defined modules
- run commands on the databricks cluster

**Comment by gbrueckl** [comment]
I fully understand your point but thats outside of the responsibility of this extension.
We dont do anything specific about autocompletion but rely on the languages autocompletion capabilities. For this to work, you need to configure your VSCode and Python (or your language of choice) environment accordingly

also, as the code itself is stateless (the state of the variables only exist on the cluster), autocomplete will always be limited.
You might want to check out Databricks/Spark Connect v2 which I think covers this but you would loose other capabilities like integration within the repo etc.
