### ISSUE TITLE
displayHTML does not work with any HTML element

### ISSUE THREAD

**Issue by fabianprx** [paiqo/Databricks-VSCode#126]
I am currently trying to display images in my notebook located in the DBFS.
The files are located here: dbfs:/FileStore/tables/myFolder/<imgName>.png
**Remark**: my DBFS workspace is connected to my VSC workspace. 

When working in the Databricks web UI I can do this using a markdown cell:

`%md
![myImageDescription](files/tables/myFolder/myImage1.png)
![myImageDescription](files/tables/myFolder/myImage2.png)
`

Unfortunately, when working in VSC using the extension, all I see is this:
![image](https://user-images.githubusercontent.com/65440931/212864044-26fcf551-4730-4d7b-874c-47681d46b24a.png)

Due to that I tried to embed one of the images using HTML, e.g. using displayHTML:
`%python
displayHTML("<img src='dbfs:/FileStore/tables/myFolder/myImage1.png' width='600' height='600'>")
`
Doing so, I only received text as an output:
![image](https://user-images.githubusercontent.com/65440931/212864527-6473125e-1b15-457b-a18c-b19988395f61.png)

I also tried this with a HTML link and the behavior was the same. I was not able to observe an HTML link element, but rather just text.

Please also see #90 as I guess this issue was also occuring in the past. Unfortunately, for me the behavior seems to be the same and I cannot get it to work.
Maybe it is also my fault so I would be glad to receive help. Is there any solution that works both on Databricks UI and in VSC using the plugin? Thanks a lot!

**Comment by gbrueckl** [comment]
Markdown cells (`%md`) are an exception - they are rendered on the client/in VSCode directly without sending them to the Databricsk cluster hence you cannot reference files from DBFS. 
so I think you definitly need to use a Python cell for this - however, you probably cannot simply reference a file from DBFS 
you would probably need to read the file from DBFS first, convert it to base64 and inject the result into the <img> tag
as described here https://stackoverflow.com/questions/8499633/how-to-display-base64-images-in-html

**Comment by fabianprx** [comment]
Thanks for replying, go it. Nevertheless, when my workspace is connected to DBFS, would it mean there's another way to "locally" access the images to enable the rendering? If not, am I correct that probably what you suggested (convert to base64) might be the only option? If so, then I guess its not really "possible" (in terms of being convenient/easy-to-do) to have images embedded.

**Comment by gbrueckl** [comment]
if you have `dbfs:/` mounted in your VSCode workspace, you can easily access DBFS
however, this new dbfs URI scheme only exists within VSCode and I am quite sure that it will not work when used inside I Markdown text. It might though work if your markdown file is also on DBFS - dont know if thats an option

I usually recommend that code that runs from VSCode should also run the very same way in Databricks directly hence the approach using Python + base64 would be the only option

However, there are a lot of things that work differently in Databricks and in VSCode and we will probably never be able to replicate all of them into VSCode.

**Comment by gbrueckl** [comment]
the Databricks Execution API does not support running `%md` cells on the cluster hence we also cannot reference items that only exists in the Databricks Workspace (e.g. on DBFS)

closing as cannot be fixed
