### ISSUE TITLE
JSON cell result download not working 

### ISSUE THREAD

**Issue by richiesgr** [paiqo/Databricks-VSCode#127]
Hi
when I use the flat-data-view I get two button right down the area CSV and JSON 
The CSV button download the cell content but the JSON don't work at all any idea why ?
Thanks

**Comment by gbrueckl** [comment]
notebook renderers are not part of this extension - please ask your question here
https://github.com/RandomFractals/vscode-data-table 

flat-data-view renderer comes from that extension (which is installed as a dependency of Databricks-VSCode extension)

**Comment by richiesgr** [comment]
Sorry my mistake
