### ISSUE TITLE
No support for cells using dbutils.widgets

### ISSUE THREAD

**Issue by bicaluv** [paiqo/Databricks-VSCode#128]
As far as I can see, there is no support when using dbutils.widgets in my code.  
E.g.
`survey = dbutils.widgets.get('Umfrage')`

**Comment by gbrueckl** [comment]
thats right, this is currently not supported 
I am still looking for a way to properly implement this but to be honest, this is super difficult.
we might add a button to populate all widgets at once using the VSCode input box at the top - would that work for you?

However, this will probably only work for text inputs or simple dropdown

**Comment by bicaluv** [comment]
Populating all the widget at once and using the VSCode inout box would be fine. Because right now, I have no chance at all to use notebook using widgets.

**Comment by patchatarch** [comment]
Any suggestion for a workaround on this issue?

**Comment by gbrueckl** [comment]
not yet - except replacing the calls to `dbutils.widgets.get` with static values instead
but its on our roadmap

**Comment by gbrueckl** [comment]
can you please test the pre-release form here
https://github.com/paiqo/Databricks-VSCode/releases/tag/v1.5.0

it adds support for widgets and should cover the most common scenarios

**Comment by patchatarch** [comment]
@gbrueckl Great! This works for my use case.
I've only tried it for dbutils.widgets.text which is probably the only thing I need for 99% of my projects.

Although when I'm trying to edit value of the widgets, I don't have option to explicitly select the specific widget that I want to change value. It loops through each widget and wait for the specific one that I wanted to change to show up, then change it.

But overall, this is awesome! Thank you for the hardwork

**Comment by gbrueckl** [comment]
great, thanks for testing - I will probably add another multiselect to let the user choose which widgets to update 👍

**Comment by gbrueckl** [comment]
just released v1.5.0 to the VSCode gallery with some further improvements for widgets

**Comment by montanarograziano** [comment]
Hi @gbrueckl. i was testing a notebook with widgets inside and I found out that widgets are recognized in the Widget button only if they are defined using positional arguments, and not using keyword arguments.
I tried this line of code here, and i cannot see end edit them:
`dbutils.widgets.text(name='customer', defaultValue='John', label='Customer')`
Instead, it works fine when using:
`dbutils.widgets.text('Customer', 'John')`
Is this behaviour intended or am I doing something wrong? Thank you in advance.

**Comment by gbrueckl** [comment]
No, probably a parsing issue on our side.
I will check and update you here

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gbrueckl** [comment]
this will be fixed with the next release

**Comment by grazianom-tuidi** [comment]
Thank you @gbrueckl , working like a charm now!

**Comment by montanarograziano** [comment]
Thank you @gbrueckl , working like a charm now!

**Comment by gbrueckl** [comment]
closing as fixed
