### ISSUE TITLE
Authentication Prompt missing?

### ISSUE THREAD

**Issue by Charliux** [paiqo/Databricks-VSCode#129]
First of all, thanks for working on this extension, it is awesome.

Now my problem, whenever I try to run a simple python code (5 lines) against one of the databricks clusters, it just stays there running forever.

When I run this on Databricks, I get the following authentication prompt:
![image](https://user-images.githubusercontent.com/79228825/213886962-2173a6e2-71e6-4ed0-8065-d707228a82d4.png)

Once I go to that link and enter the code, my code continues running.

I believe my code hangs on VSCode is because it is waiting for this prompt, but can't find it anywhere.  Any idea?

**Comment by gbrueckl** [comment]
could you please share some more information on your environment?
which OS are you using? (Win, Linux, Mac)
where is your Databricks workspace hosted? (Azure, GCP, AWS)

Since you get a prompt for a login, I guess you are on Azure using the Azure Connection Manager?

**Comment by Charliux** [comment]
My environment is Windows10,   Databricks is hosted in Azure.

I only get the prompt for a login whenever I am in the databricks environment but not in VS Code.        

When I try to use the Connection Manager with Azure selected, it never connects to Databricks.
![image](https://user-images.githubusercontent.com/79228825/214323607-5cd02dcf-6fc1-455c-846b-601fecd992f2.png)

When I use VS Code Settings it does connect.
![image](https://user-images.githubusercontent.com/79228825/214323834-dc639bea-4436-4896-bc3c-3d018db14405.png)

and can run python code on the cluster.  The problem I am having is happening when I try to connect to an internal database and don't get that login prompt (which i do get whenever I run the same code in the Databricks environment)

**Comment by gbrueckl** [comment]
so the only time you should get prompted in the Databricks Web UI is at the very beginning when opening the site the first time but definitely not when executing a notebook

can you share some of the code that you use to "connect to an internal database"?

**Comment by Charliux** [comment]
This is the code, we use an internal library to facilitate the connection to that database.  

![image](https://user-images.githubusercontent.com/79228825/214637476-b52d4a76-7447-41e3-8941-2ab02149f4de.png)

in the screenshot here (running on DB) you can see I get the prompt.  Once I go the URL and enter the code the code runs.

When I try this in VSCode, it keeps running until it times out.  My thinking is that it is waiting for that prompt which I never get.

**Comment by gbrueckl** [comment]
not sure but it seems like this code then only shows the message/popup where it actually runs.
In our extensions we are just sending the plain python code to the Databricks cluster to execute it there so the message/popup might not be displayed properly (or at all) in VSCode

not sure if we can do anything about this

**Comment by gbrueckl** [comment]
closing as this cannot be fixed by the extension and the way it works (running Databricks Execution APIs which cannot create a pop up)
