### ISSUE TITLE
Cannot read property 'Python' of undefined

### ISSUE THREAD

**Issue by michaelschufi** [paiqo/Databricks-VSCode#13]
I'm getting the `Cannot read property 'Python' of undefined` whenever I want to open a workspace folder with files in it.

OS: Windows 10
VSCode:  1.44.2
Extension Version: 0.4.0

I tried reloading the window and resetting settings like:
- `python.pythonPath`
- `python.venvPath`
- `python.linting.enabled`
- `python.pythonPath`

My databricks settings:
```json
"databricks.connection.default.apiRootUrl": "https://westeurope.azuredatabricks.net",
"databricks.connection.default.personalAccessToken": "dapifffffff",
"databricks.connections": {
      "displayName": "A Name",
      "cloudProvider": "Azure",
      "apiRootUrl": "https://westeurope.azuredatabricks.net",
      "personalAccessToken": "dapifffffff",
      "localSyncFolder": "C:\\an_absolute_path\\bla",
    },
```

**Comment by gbrueckl** [comment]
This is probably a bug and related to the file extensions of the files in your localSyncFolder

Could you post your file/folder structure including file extensions so I can debug this?

The supported file extensions should be:
.py, .r, .scala and .sql optionally followed by .ipynb for notebooks

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by michaelschufi** [comment]
My localSyncFolder is empty except for an empty directory called "Workspace".

**Comment by gbrueckl** [comment]
ok, this is actually an issue with your settings/configuration

there are basically two ways to add/configure new connections:
1) using databricks.connection.default.* which are settings that can be set by the VSCode Settings UI
2) using databricks.connections: [ ... ] which can only be set in JSON directly

for both options, you need to specify the mandatory properties "displayName", "personalAccessToken", "apiRootUrl" and "localSyncfolder"

can you remove all settings from your JSON configuration manually and add them again via the UI?

**Comment by michaelschufi** [comment]
I did that and it turns out that the array configurations aren't working:

```json
{
  "databricks.connection.default.apiRootUrl": "https://westeurope.azuredatabricks.net",
  "databricks.connection.default.displayName": "Test",
  "databricks.connection.default.localSyncFolder": "C:\\temp\\databricks\\test",
  "databricks.connection.default.personalAccessToken": "dapikey",
  "databricks.connections": [
    {
      "apiRootUrl": "https://westeurope.azuredatabricks.net",
      "displayName": "Test2",
      "localSyncFolder": "C:\\temp\\databricks\\test2",
      "personalAccessToken": "dapikey",
    }
  ],
  "databricks.userWorkspaceConfigurations": [
    {
      "workspaceConfig": {
        "workspaceGuid": "92a978dc-86f0-2120-056c-721799cf4396",
        "lastActiveConnection": "Test"
      },
      "connections": [
        {
          "apiRootUrl": "https://westeurope.azuredatabricks.net",
          "displayName": "Test2",
          "localSyncFolder": "C:\\temp\\databricks\\test2",
          "personalAccessToken": "dapikey"
        },
        {
          "displayName": "Test",
          "cloudProvider": "",
          "apiRootUrl": "https://westeurope.azuredatabricks.net",
          "personalAccessToken": "dapikey",
          "localSyncFolder": "C:\\temp\\databricks\\test",
          "databricksConnectJars": "",
          "pythonInterpreter": "",
          "port": 0,
          "organizationId": "",
          "exportFormats": {
            "Scala": ".scala",
            "Python": ".py.ipynb",
            "SQL": ".sql",
            "R": ".r"
          }
        }
      ]
    }
  ],
}
```

The connection called "Test2" (from the array) is not working.  The connection "Test" works.

**Comment by gbrueckl** [comment]
can you add the property "exportFormats" also to the connection "Test2"?
this should solve the issue

I also just worked on v0.4.1 where this is fixed - you can download it manually form here
https://github.com/paiqo/Databricks-VSCode/releases/tag/v0.4.1

**Comment by michaelschufi** [comment]
Cool. It's working by adding the property "exportFormats".

I also tested it with the new version and can confirm it's working without explicitly adding the property.

Thanks :D

**Comment by gbrueckl** [comment]
Ok, great! 
I will close this issue then
