### ISSUE TITLE
Never prompts me for Authentication when using Azure Connection Manager

### ISSUE THREAD

**Issue by Saugat168** [paiqo/Databricks-VSCode#130]
VS Code Version: 1.74.3
Databricks VScode version: V1.4.0
Using windows and Azure Databricks

So, I was quite excited to try this extension out as we use Databricks Clusters with Credential passthrough to Azure Data Lake Gen2 a lot, and setting up an IDE to work with AAD and not PAT tokens, was proving very cumbersome.

This extension, according to the docs, can work with AAD. So, I have the following properties set

```
 "databricks.connectionManager": "Azure",
  "databricks.connection.default.apiRootUrl": "https://adb-<idofmyworkspace>.11.azuredatabricks.net",
  "databricks.connection.default.displayName": "ProdWorkspace",
  "databricks.connection.default.localSyncFolder": "C:\\RootFolder\\SubFolder\\testdatabricks",
  "databricks.azure.tenantId": "OurTenantID"
```

I understand that some of the settings could be optional, like the tenant id, but I added some of them after repeated failures to connect from VS Code.

I understand that I do not need to provide PAT token (listed as mandatory in the settings UI) if using the "Azure" connectionManager, 

However, refreshing the connections , does not list any connections, neither do I ever get a prompt to connect to Azure (as the docs suggest). Do I need to install any other extension, in order to sign in ? I would assume, VS Code, should be able to open up a browser window prompting me to sign in and then capturing the AAD token.

Looking at Output window , for "paiqo.databricks-vscode, I see the following errors

```

If you experience issues please open a ticket at https://github.com/paiqo/Databricks-VSCode
Trying to get config from Workspace settings ...
No Workspace settings found! Trying to get User-Settings instead ...
Initializing ConnectionManager Azure ...
TypeError: Cannot read properties of undefined (reading 'accessToken')
No Databricks Workspaces have been found! Please make sure you are connected to the right tenant and have the appropriate permissions!
API has not yet been initialized! Please connect first!
```

What am I missing? I have also tried connecting to Azure from VS code and I was able to successfully sign in and also choose the subscription. Please note that I have read permission to the subscription as well. But whatever I do, it still gives me the same error. The problem lies with it not getting the AAD token somehow.

**Comment by Saugat168** [comment]
I think lines 101-104 in `DatabricksConnectionManagerAzure.ts` is where the problem lies

```
if(this._connections && this._connections.length > 0)
		{
			return;
		}
```

it therefore never prompts me. I also see that in one of last check ins, the comment says `remove forced prompt for Azure connection Manager`

**Comment by gbrueckl** [comment]
thats weird, it should actually look like this:
![image](https://user-images.githubusercontent.com/11884402/216273150-17bec0e4-c412-4788-b105-b3ace6d00eff.png)

in order to authenticate, you need to sign into VSCode using your Work-account (the one from your Azure tenant) at the left bottom of VSCode.
![image](https://user-images.githubusercontent.com/11884402/216273452-2d18196f-bcf5-46cb-a004-dfe84cde0baa.png)

the code you in `DatabricksConnectionManagerAzure.ts` was originally an optimization, but it actually does nothing as it will never evaluate to true as the connection manager is always initialized from scratch

**Comment by Saugat168** [comment]
Thanks. That helped. I was signing through the command pallet earlier, but then I used what you suggested

![image](https://user-images.githubusercontent.com/30119939/216360378-45d7fad6-5b3e-4344-8f14-1b5bdde6cbe3.png)

**Comment by gbrueckl** [comment]
So is everything working now as expected?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gbrueckl** [comment]
btw, the command you used (`Azure: Sign in to Azure Cloud`) comes from the Azure Account extension and has nothing to do with this one :)

**Comment by gbrueckl** [comment]
closing as the last feedback was its fixed
