### ISSUE TITLE
Sql execution in vscode is executed twice by default

### ISSUE THREAD

**Issue by hahahahuang** [paiqo/Databricks-VSCode#131]
Connect to databricks in vscode to execute sql code, click Run, the command will be executed twice by default, which is very confusing to us, can you solve this problem as soon as possible, thank you very much

![image](https://user-images.githubusercontent.com/124541421/216865571-bdaea5b6-2714-4b69-aace-e35606117fe4.png)
![image](https://user-images.githubusercontent.com/124541421/216865598-efc37fbd-fc8b-4c20-8c2a-ee799be46ae4.png)

**Comment by gbrueckl** [comment]
thanks for reporting this
it is definitely a bug and a fix is on its way!

**Comment by gbrueckl** [comment]
just published `v1.4.1` which should fix this issue!

**Comment by hahahahuang** [comment]
Bugs have been fixed!  Thank you so much!

**Comment by gbrueckl** [comment]
closing as fixed
