### ISSUE TITLE
Unable to setup connection - SSL errors

### ISSUE THREAD

**Issue by abhijitpjoshi** [paiqo/Databricks-VSCode#136]
Hi There

I have installed the extension and getting the following errors in the extension output

**Method 1: Connection details from VS code settings**

"databricks.connectionManager": "VSCode Settings",
    "databricks.connections": [

        {
            "apiRootUrl": "https://oportun-integrated-dev.cloud.databricks.com",
            "displayName": "DEV",
            "localSyncFolder": "Users/abhijit.joshi/shellscripts/databricks/vscode-databricks/dev",
            "personalAccessToken": "<My working Dev token>"
        },
        {
            "apiRootUrl": "https://oportun-qa.cloud.databricks.com",
            "displayName": "QA",
            "localSyncFolder": "Users/abhijit.joshi/shellscripts/databricks/vscode-databricks/qa",
            "personalAccessToken": "<My working Dev token>"
        }
    ],
    "databricks.lastActiveConnection": "DEV",
    "databricks.sensitiveValueStore": "VSCodeSettings",
    
    
    Error:

Testing new Databricks API (https://oportun-integrated-dev.cloud.databricks.com/) settings ...
GET 2.0/workspace/list --> {"path":"/"}
ERROR: h
ERROR: request to https://oportun-integrated-dev.cloud.databricks.com/api/2.0/workspace/list?path=/ failed, reason: certificate signature failure
ERROR: h: request to https://oportun-integrated-dev.cloud.databricks.com/api/2.0/workspace/list?path=/ failed, reason: certificate signature failure
	at ClientRequest.<anonymous> (/Users/abhijit.joshi/.vscode/extensions/paiqo.databricks-vscode-1.5.0/dist/node/extension.js:2:239191)
	at ClientRequest.emit (node:events:538:35)
	at ClientRequest.emit (node:domain:475:12)
	at TLSSocket.socketErrorListener (node:_http_client:442:9)
	at TLSSocket.emit (node:events:526:28)
	at TLSSocket.emit (node:domain:475:12)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
undefined
ERROR: Error: Invalid Configuration for Databricks REST API: Cannot access 'https://oportun-integrated-dev.cloud.databricks.com/' with headers '{"Authorization":"Bearer <REDACTED it for safely>"}'!
API has not yet been initialized! Please connect first!

**Method 2: Databricks CLI profiles**

I get same errors

My databricks cli works fine from ~/.databrickscfg where I have mentioned the URL, token, localSyncFolder etc.

-  databricks workspace ls --profile dev                                                                                                                                                                            

bin
Users
Shared
Repos
app
databricks-support

**Please note** my databricks CLI works only after I set export REQUESTS_CA_BUNDLE='/Users/abhijit.joshi/shellscripts/Zscaler Root CA.cer' which I had to download reference here https://stackoverflow.com/questions/63888000/databricks-cli-sslerror-cant-find-local-issuer-certificate

Please assist

**Comment by gbrueckl** [comment]
pretty hard to say - you might try some VSCode settings but there is currently nothing specific about this extension that would help you with this

**Comment by gbrueckl** [comment]
closing as there is nothing we can do about this
