### ISSUE TITLE
Cannot "%run ../../notebook" relative path in workspace subfolder

### ISSUE THREAD

**Issue by mikecrowe-8451** [paiqo/Databricks-VSCode#138]
Background:

- I downloaded one of my repos to a local folder
- In my vscode workspace, I added the local folder like this (LMK if there was a better way to do this):

```
> Databricks - Workspace
    > Repos
        > my_db_user
            > MyRepo
> MyRepo (<-- folder added via Add Folder to Workspace pointing to ~/Databricks-VSCode/DEFAULT/Workspace/Repos/my_db_user/MyRepo)
```

* From this local folder, I open `MyRepo/task1/subtask1/folder1/folder2/notebook_to_run.ipynb`

Our repos are laid out with in nested folders as such:

```
task1/subtask1/config/setup.ipynb
task1/subtask1/folder1/folder2/notebook_to_run.ipynb
...
```

This might be a stupid problem on my side, but I'm having problems running a cell that simply does this:

**task1/subtask1/folder1/folder2/notebook_to_run.ipynb:**

```
%run ../../config/setup
```

> EntryNotFound (FileSystemError): Unable to resolve nonexistent file `/Users/me/Databricks-VSCode/config`

The full path to this notebook is:

```
/Users/me/Databricks-VSCode/DEFAULT/Workspace/Repos/my_db_user/MyRepo/task1/subtask1/folder1/folder2/notebook_to_run.ipynb
```

So, when running, it thinks the current folder is: 

> `/Users/me/Databricks-VSCode/DEFAULT/Workspace` 

However, it should be (I think):

> `/Users/me/Databricks-VSCode/DEFAULT/Workspace/Repos/my_db_user/MyRepo/task1/subtask1/folder1/folder2`

Is this an operator error on my part?  A setup issue?

**NOTE**: 

I also tried running this directly from the repo, and that error is:

```
EntryNotFound (FileSystemError): wsfs:/../../config/setup
```

**Comment by gbrueckl** [comment]
please try `%run ./../../config/setup` with a trailing `./`
this should be the same behavior as in the Databricks web UI where I think it also does not work if you start with `..`

**Comment by mikecrowe-8451** [comment]
Yeah, I saw that comment about the leading `./` -- problem is, we have a ton of notebooks that lack that, so I was hesitant to make so many changes to the notebook.

I was hoping there was a workaround for running from a local notebook somehow.

**Comment by gbrueckl** [comment]
are you sure those leading `..` do work in Databricks directly?

**Comment by mikecrowe-8451** [comment]
Yes

**Comment by gbrueckl** [comment]
this will be fixed in the next release - probably published today

**Comment by gbrueckl** [comment]
just released it - please update to 2.0.2 and give it another try :)

**Comment by mikecrowe-8451** [comment]
I'm now getting:

```
2023-03-29 10:18:11.448 [error] TypeError: t is not iterable
    at Function.refresh (/Users/myuser/.vscode/extensions/paiqo.databricks-vscode-2.0.2/dist/node/extension.js:2:71012)
```

**Comment by gbrueckl** [comment]
`wsfs` or local file?
any other important messages in the log?

the error you provided does not look related to `%run` or notebook execution in general, hmm

**Comment by mikecrowe-8451** [comment]
As an FYI, this seems to be another issue related to the Buffer changes.  I downgraded to 2.0.1 and it seems to be back to almost normal

**Comment by gbrueckl** [comment]
this should have been fixed now with v2.0.3 - sorry for the inconvenience!
can you please try your `%run` test again

**Comment by gbrueckl** [comment]
@mikecrowe-8451  did you have time yet to test this?

**Comment by gbrueckl** [comment]
closing as fixed and no further feedback
if the issue still persists, please open another, new ticket
