### ISSUE TITLE
Selected cell's language is ignored

### ISSUE THREAD

**Issue by SontungAnakin** [paiqo/Databricks-VSCode#139]
**Problem**
In a `.ipynb`, even when active cell's language is selected it is ignored, python is chosen, POSTed to the Databricks server and executed.
See the error & the POST request in the screenshot.

I suspect this line is the culprit
https://github.com/paiqo/Databricks-VSCode/blob/master/src/vscode/notebook/DatabricksKernel.ts#L301

**Expected behaviour**
Cell's selected language is respected. 
And/or there's a setting for default language of the whole notebook, and new notebooks default language.

**Attachment**
![Screenshot 2023-03-30 at 18 54 36](https://user-images.githubusercontent.com/23339071/228933367-bcf11f6b-7535-4922-a241-0ce60fcab997.png)

**Comment by SontungAnakin** [comment]
Thanks Gerhard for the quick response! I see your point of having Databricks and Powertools behave same for the same `.ipynb` notebook. 
On this point do you think if it's possible to automatically change/add to the first line the language switch (`%scala`, `%sql`,...) when I press the cell's Language button? This is just like the way how Databricks handle it for `.ipynb`.

I am looking forward to the feature of rendering `.scala `notebooks, would be awesome and just like how Databricks handle scala properly.

**Comment by gbrueckl** [comment]
I think automatically adding the magics whenever you change the language of a cell would also work - though, rendering original `.scala` files as a notebook would be the better approach and we will invest our time there :)

**Comment by SontungAnakin** [comment]
Rendering .scala files from Databricks as notebooks is defo an awesome upgrade :)
But even with that, adding language magics is needed because it is possible to write python, sql, etc in scala notebooks with the switch as well. Databricks does it so. 
In any case, thank you very much for the continuous work on the plugin! It is very neat!

**Comment by gbrueckl** [comment]
can you please try this pre-release:
https://github.com/paiqo/Databricks-VSCode/releases/tag/v2.1.0-pre

it now renders source files (scala, R, SQL) as notebooks and should give you the same experience as for Python

please be aware that now all `.scala`, `.r` and `.sql` files will be opened as notebooks and this will fail if the notebook was not originally downloaded from Databricks!
this is something we are still working on

**Comment by SontungAnakin** [comment]
what a speed! Thank you, let me try.

**Comment by SontungAnakin** [comment]
Alright, here are some observations:

a) there's no option to create a new .scala notebook using the menu: File -> New file

b) opening an existing .scala file with empty lines before the magic line `"// Databricks notebook source"` is not treated as a scala notebook

c) opening an existing .scala file with magic line `"// Databricks notebook source"` followed immediately by a text line is not treated as a scala notebook. 

(b) and (c) are treated as a scala notebook in databricks normally

**Comment by gbrueckl** [comment]
closing this ticket as the root issue was explained and/or fixed
if the other suggestions like New File from Workspace browser are still needed, please open another ticket
