### ISSUE TITLE
How can I execute notebooks against a Cluster?

### ISSUE THREAD

**Issue by michaelschufi** [paiqo/Databricks-VSCode#14]
I have followed the steps in the [guide](https://docs.databricks.com/dev-tools/databricks-connect.html) linked in the readme:

- I'm using a local virtual environment inside my VS Code folder (`.venv`) for databricks-connect. 
- I've configured databricks and `databricks-connect test` runs successfully. (Using the builtin-java classes).
- I've set the Python interpreter and configured it like the guide mentioned. 
   ```
   "python.venvPath": "c:\\path_to_workspace\\.venv\\lib\\site-packages\\pyspark\\jars",
   "python.linting.enabled": false,
   "python.pythonPath": "C:\\path_to_workspace\\.venv\\Scripts\\python.exe",
   ```
- Additionally, I've set up
   ```
  "databricks.connection.default.databricksConnectJars": "c:\\path_to_workspace\\.venv\\lib\\site-packages\\pyspark\\jars",
  "databricks.connection.default.organizationId": "4636970212345678",
  "databricks.connection.default.port": 15001,
  "databricks.connection.default.pythonInterpreter": "C:\\path_to_workspace\\.venv\\Scripts\\python.exe",
   ```
  (I'm currently using the default connection)

However, after opening a notebook using the Workspace section, VS Code spawns a local server and connects to it locally. What am I doing wrong?

**Comment by gbrueckl** [comment]
Please check the docs for Databricks-Connect
The responsibility of this extension ends once the file/notebook is downloaded

(the specific and optional Databricks.* settings in VS Code are reserved for future use but are currently not obeyed)
