### ISSUE TITLE
Working directory is different in VS Code from Databricks web UI

### ISSUE THREAD

**Issue by marvinbernhardt** [paiqo/Databricks-VSCode#140]
I think I have the same problem as described in #107: I am trying to run a notebook that resides in a repo in Databricks from VS code and import from a python file that is in the same folder. That does not work because I the working directory is not right.

On Databricks Web UI:
```python
> os.path.abspath('')
/Workspace/Repos/<username>/<repo>/<folder>/
```

In VS Code using the Databricks kernel
```python
> os.path.abspath('')
/databricks/driver
```
I don't think I use %python pip install anywhere (this was the issue in #107), I only have pip install -r req.txt in the clusters init script. My runtime is 12.2 LTS.

I used the same cluster for both executions. I tried in Offline-execution and Live-execution ("Add Databricks Workspace to VS Code Workspace" Button).

I noticed, that also `sys.path` does not contain the expected directory in VS Code, only in Databricks UI.

**Comment by gbrueckl** [comment]
just ran another test on my side and it works fine for me, even on 12.2 LTS
can you please check the logs:
![image](https://user-images.githubusercontent.com/11884402/229757623-24e14584-4448-4b10-8cae-f7375e3142f3.png)
it should look similar as above
if it is successful, you should also see a line like this which also tells you which commands were executed in the background
![image](https://user-images.githubusercontent.com/11884402/229757915-e76b0b39-6c96-41e2-a34b-6425544b7414.png)

**Comment by marvinbernhardt** [comment]
I checked my logs

```
NotebookKernel: Successfully set up FilesInRepo by running 'sys.path.append('/Workspace/Repos/<username>/<repo>')' and 'os.chdir('/Workspace/Repos/<username>/<repo>/<folder>')' on driver!
```

and now it suddenly works?! I deactivated and activated the extension in between, not sure what else is different today. I will just close for now.
