### ISSUE TITLE
Suddenly unable to establish connection

### ISSUE THREAD

**Issue by ibarshai** [paiqo/Databricks-VSCode#142]
I've been using this extension for a while now and it's been working very well. Last week, I was suddenly unable to connect. I reset all of the connection settings, added a new working PAT (just in case) and connection was reestablished. This morning, everything was working fine. Then, it suddenly stopped and I've been unable to establish a connection since.

The message I get in VSCode when I try to connect is:
"No Databricks Workspaces have been found! Please make sure you are connected to the right tenant and have the appropriate permissions!"

When I first configured the settings, I provided the mandatory fields inside VSCode settings and it connected. Now, I've tried configuring the settings under User, under Workspace, and neither does the trick. My PAT is definitely functional. I've set up the databricks CLI using the same PAT and Root URL (host), and I can connect without any issues.

I would really appreciate any help, including guidance about how where to look for the issue!

My user settings are:
```{
    "editor.inlineSuggest.enabled": true,
    "[python]": {
        "editor.formatOnType": true
    },
    "databricks.connection.default.displayName": "Databricks A3KCore Nonprod for Autograder",
    "databricks.connection.default.apiRootUrl": "https://mhe-a3kcore-nonprod.cloud.databricks.com",
    "databricks.connection.default.localSyncFolder": "C:/Users/ilybar/OneDrive - Personal/AutoGrader/databricks_sync",
    "databricks.connection.default.personalAccessToken": WORKING PAT

}```

The workspace settings are:
```{
	"folders": [
		{
			"path": ".."
		}
	],
	"settings": {
		"databricks.connection.default.localSyncFolder": "C:/Users/ilybar/OneDrive - Personal/AutoGrader/databricks_sync",
		"databricks.connection.default.personalAccessToken": WORKING PAT,
		"databricks.connection.default.apiRootUrl": "https://mhe-a3kcore-nonprod.cloud.databricks.com",
		"databricks.connection.default.displayName": "Databricks A3KCore Nonprod for Autograder",
		"databricks.connection.default.useCodeCells": false,
		"databricks.connectionManager": "Default",
		"databricks.connections": [],
		"databricks.sensitiveValueStore": "SystemKeyChain",
		"databricks.connection.default.exportFormats": {
			"Scala": ".scala",
			"Python": ".ipynb",
			"SQL": ".sql",
			"R": ".r"
		},
		"databricks.azure.workspaces": [
		]
	}
}```

**Comment by gbrueckl** [comment]
have you recently installed the official Databricks Extension?
if it is installed and you have set `"databricks.connectionManager": "Default"` it will try to derive the settings from the official Databricks Extension and if this has not yet been configured, it will fail with the error message you posted

to make it work as before you would need to change `"databricks.connectionManager": "VSCode Settings"` to force it to use the settings from your VSCode workspace

**Comment by ibarshai** [comment]
Thank you so much! I uninstalled the official extension and everything went back to working. Weirdly, putting everything in my workspace settings and setting `"databricks.connectionManager": "VSCode Settings"` didn't seem to do it.

**Comment by gbrueckl** [comment]
did you restart VSCode after you changed the connection manager to `VSCode Settings`? could be that it was not picked up properly otherwise
technically, using `VSCode Settings` is the same as `Default` if you do not have the Databricks Extension installed
