### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by dilzeem** [paiqo/Databricks-VSCode#143]
Hi, 

This extension looks very promising, though I am getting trouble with trying to get it to work. 

I am getting an error of not being able to find apiClient?
Is there some dependency that needs to be installed to retrieve this apiClient?
This is running on WSL2 Ubuntu.

```
Initializing ConnectionManager Databricks Extension ...
Databricks extension is installed!
TypeError: Cannot read properties of undefined (reading 'apiClient')
No Databricks Workspaces have been found! Please make sure you are connected to the right tenant and have the appropriate permissions!
API has not yet been initialized! Please connect first!
```

**Comment by dilzeem** [comment]
I looked at the source code, and it seems it was related to the databricks extension. 

So I used the databricks-cli instead and it works as expected. 
Really useful extensions, adds a lot on what was released by databricks, and better setup for local development.

**Comment by dilzeem** [comment]
Yeah it was. 

It was set to Default before, and I had the extension installed.

**Comment by gbrueckl** [comment]
the fix for this will be released on Monday 
make sure to update both extensions (but this should happen automatically anyway)

**Comment by dilzeem** [comment]
Great thanks for that!
If it is not resolved I will reopen it again :)
