### ISSUE TITLE
Code Cell immediate execution

### ISSUE THREAD

**Issue by dilzeem** [paiqo/Databricks-VSCode#144]
Hi, 

This is a very minor issue, but it would improve my developer workflow

When I use code cells as outline here: https://github.com/paiqo/Databricks-VSCode/issues/17
It works as expected. However I am getting the issue when I run the cell it moves the code to the cell block. 
But it doesn't execute. I have to go to the cell block and then actually execute the block.
This only happens when I use the databricks kernel. 

When I have a local virtual environment it behaves as expected. 
That is is the code is executed in the cell block.

**Comment by gbrueckl** [comment]
I tried to implement this in the past but faced a blocker as code-cells are a feature of vscode-jupyter and not a native part of vscode notebooks
https://github.com/microsoft/vscode-discussions/discussions/331

so unfortunately we cannot implement is as you would expect/requested

may I ask what you need it for and why notebooks do not work for you?

**Comment by dilzeem** [comment]
Ahh not a problem then. I will close this issue. 

The reason I prefer code cells over notebooks is that I can jump around the codebase a bit more this a nice to have with a monorepo setup we are aiming for. I also use vim keybindings, and it just much easier to navigate in a python file than a notebook as well. Like I said it was a convenience feature and nothing critical for me.  Again very much appreciate the extension.
