### ISSUE TITLE
Opening or creating a .scala doesnt render as a notebook 

### ISSUE THREAD

**Issue by SontungAnakin** [paiqo/Databricks-VSCode#147]
despite being mentioned in the release notes, the new version 2.1.0 it working with a .scala Databricks notebook doesn't work. The notebook is still treated as a source text file.

**Comment by gbrueckl** [comment]
v2.1.0 is not yet released to the market place so you need to download it from here and install it manually 
https://github.com/paiqo/Databricks-VSCode/releases/tag/v2.1.0

in addition you also need to make the following settings in VSCode:
```
"settings": {
		"workbench.editorAssociations":{
			"*.py": "databricks-notebook",
			"*.scala": "databricks-notebook",
			"*.sql": "databricks-notebook",
			"*.r": "databricks-notebook"
		},
    ...
}
```

**Comment by gbrueckl** [comment]
closing as fixed
