### ISSUE TITLE
No folder structure in Workspace or DBFS panel

### ISSUE THREAD

**Issue by jhickson** [paiqo/Databricks-VSCode#148]
Hi,

I have version 2.1.0 of the extension installed and am connecting to our Databricks via the Databricks extension (version 0.3.7), but neither the Workspace panel nor the DBFS panel show anything even though all the other panels show the expected data. When I click refresh on either the Workspace or DBFS panel I get an error notification saying

```
Cannot read properties of undefined (reading 'path')
```

However, no errors are shown in the output console.

Connecting using the Databricks CLI Profiles connection manager works perfectly, however.

**Comment by gbrueckl** [comment]
could it be that you did not set the Sync Destination in the Databricks Extension?
thats where we would derive the local folder from - if it is not set, you could see that error
