### ISSUE TITLE
Cannot create any Connections (setup)

### ISSUE THREAD

**Issue by leitneratselerity** [paiqo/Databricks-VSCode#149]
I have installed the Power Tools Extension v2.1.0 with VS Code 1.73.1.

I have set up both the VS Code and the Databricks-CLI-based connection managers.
Likely those are correct, because I can connect in other ways (with the `databricks` CLI for example, or with the "official" [Databricks extension](https://docs.databricks.com/dev-tools/vscode-ext.html) that I uninstalled again)
Finally, I can pick between those two or "default" as my connection manager in the settings.

However, even after restarting VS Code, there is no data shown in the extension's sidebar view.

And when I press the "refresh" button on the Connections tab, I get the following error message:

> Error running command databricksConnections.refresh: command 'databricksConnections.refresh' not found. This is likely caused by the extension that contributes databricksConnections.refresh.

I tried looking in Output (CMD-SHIFT-U) for any logs from this tool, but there is nothing.

Any help/suggestions?

**Comment by gbrueckl** [comment]
hmm, weird, are there new entries added to the log once you click/open the Databricks Power Tools tab?

**Comment by gbrueckl** [comment]
btw, if you use a connection manager other than "VSCode settings" (or "Default" without the official Databricks extension installed), the other settings within VSCode have no effect - e.g. everything with `databricks.connection.default.*`
