### ISSUE TITLE
Possibility to put personal token in an environment variable instead of directly in vscode settings

### ISSUE THREAD

**Issue by amine4567** [paiqo/Databricks-VSCode#15]
Hello,

I have a requet to make it possible to put databricks personal access token in an environment variable instead of filling it directly in the settings.json

The vscode settings don't seem in my opinion to be a good place to put secrets. To handle different connections, a field that could be named "personalAccessTokenEnvVar" could be added to specify which environment variable to use as a token for which connection.

Thanks !

**Comment by gbrueckl** [comment]
Hi,
so there are a lot of different opinions on where the PAT should be stored. We recently moved it from the VS Code workspace settings to the VS Code user settings as the user-settings are tied to the local user and reside in a "safe" place (within the users folder)
For settings stored in the VS code workspace settings we had the issues, that some people accidentally checked them in to the Source Control provider which can not happen anymore.

We also discussed using Environment variables but these also had drawbacks:
- Naming of a connection is not necessarily unique across workspaces (e.g. a connection called PROD may appear in multiple workspaces)
- it is pretty hard to move those settings to different machines
- the user experience would not be very good as you would have different places where you need to configure your connection

so for now, we will stay with the approach of using the VS Code User settings for sensitive information like PAT
