### ISSUE TITLE
Importing py files "next" to the notebook

### ISSUE THREAD

**Issue by leitneratselerity** [paiqo/Databricks-VSCode#150]
I am trying to run a notebook that has an "import some_file_name" statement to pull in a module with code that is stored right next to it.
That works just fine directly in the web UI with Databricks, but when I run that notebook locally, it breaks with ModuleNotFoundError.
I can even see that this extension has pulled the file down into the local sync folder.

What is needed that this works with this extension in VS Code, and not just in the web UI?
Is that feature even supported today?

**Comment by gbrueckl** [comment]
While we fully support files in repos, we did not implement anything specific to files in workspace which is guess is your scenario

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Florian Leitner ***@***.***>
Sent: Friday, April 21, 2023 3:31:24 PM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] Importing py files "next" to the notebook (Issue #150)


I am trying to run a notebook that has an "import some_file_name" statement to pull in a module with code that is stored right next to it.
That works just fine directly in the web UI with Databricks, but when I run that notebook locally, it breaks with ModuleNotFoundError.
I can even see that this extension has pulled the file down into the local sync folder.

What is needed that this works with this extension in VS Code, and not just in the web UI?
Is that feature even supported today?

**Comment by gbrueckl** [comment]
I will have a look next week to see what the effort to implement this would be

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Florian Leitner ***@***.***>
Sent: Friday, April 21, 2023 3:31:24 PM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] Importing py files "next" to the notebook (Issue #150)


I am trying to run a notebook that has an "import some_file_name" statement to pull in a module with code that is stored right next to it.
That works just fine directly in the web UI with Databricks, but when I run that notebook locally, it breaks with ModuleNotFoundError.
I can even see that this extension has pulled the file down into the local sync folder.

What is needed that this works with this extension in VS Code, and not just in the web UI?
Is that feature even supported today?

**Comment by gbrueckl** [comment]
If both are in the root of the repo it should work as long as you open the file from the Workspace Browser or via the wsfs:/ scheme from VSCode explorer

Could you check the logs?
At some point we explicitly set the path in the background using regular Python commands

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gbrueckl** [comment]
If you are using repos, you need to reference the py files starting from the root of the repo the same way as you would do in regular Python


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gbrueckl** [comment]
so just tested it again and FilesInRepo is (and was) working as expected:
![image](https://user-images.githubusercontent.com/11884402/233924423-a6c6f824-5e99-4638-aff3-b4a51093854b.png)

FilesInWorkspace did not work but I just implemented a fix which will be released soon

another issue could be that you use a cluster with an older DBR - make sure to use at least 11.3 - but the later the better (my tests were on 12.2 LTS)
