### ISSUE TITLE
Getting this error while trying to create connection

### ISSUE THREAD

**Issue by harshitgoyal** [paiqo/Databricks-VSCode#151]
Error running command databricksConnections.refresh: command 'databricksConnections.refresh' not found. This is likely caused by the extension that contributes databricksConnections.refresh.

I am using Windows machine.

**Comment by gbrueckl** [comment]
I assume something went wrong when starting the extension. This is usually related to some wrong/missing [connection] configuration
you can also check the logs to see what might went wrong:
![image](https://user-images.githubusercontent.com/11884402/234256288-41e3b4a6-aea8-4cd2-9094-d0b9ea53cac9.png)

**Comment by zhenghw0226** [comment]
this one should be the same as https://github.com/paiqo/Databricks-VSCode/issues/149

i encountered the same issue before, then i uninstalled and re installed a new VSCode, now it works!
