### ISSUE TITLE
Issue running nested notebooks in sub-folders

### ISSUE THREAD

**Issue by danw22** [paiqo/Databricks-VSCode#152]
I have a reference to notebook in a "Lib" subfolder that I am calling through the run command. The notebook is called "Common" and inside it I am calling the run command to several other notebooks that reside in the "Lib" folder. So for example one of them is called FileMetadata and run command looks like %run ./Lib/Common which then calls %run ./FileMetadata. I am receiving a file not found on the FileMetadata file and what is weird is if I change the run command to %run ./Lib/FileMetadata in Common it will run. Is there a setting or reason why the relativity of the files being referenced isn't based of the notebook where the command reside as this is how the functionality works in the Databricks ui? 

I am also having a problem where functions loaded in one cell are not able to be referenced in subsequent cells. Please advise. 

If I can get this to work I'll be a happy camper as I really like the possibility this extension has to offer.

**Comment by gbrueckl** [comment]
resolving `%run` works slightly different in our extension than it does in Databricks directly. 
As `%run` is not natively supported by the Commands and Execution APIs of Databricks we manually resolve the refrenced file, load its content and then execute it in the the current session.
This currently only works 1 level deep hence calling nested `%run` is currently not supported.

considering that `%run` should be replaced by [Workspace Files](https://docs.databricks.com/files/workspace.html) we will probably not implement a fix for this

**Comment by gbrueckl** [comment]
I added some information about this behavior also to the README so it is a bit more clear
as I said, unfortunately we cannot support the scenario of nested `%run` statements in different notebooks at the moment. This would introduce a lot of complexity considering each notebook could be of a different language and potentially even each cell!

**Comment by gbrueckl** [comment]
assuming you mainly define new, generic/global functions in your referenced notebooks, you could also simply import them using Workspace Files the very same way you would import  functions from other files in regular Python
