### ISSUE TITLE
%run doesn't work for (scala) notebooks

### ISSUE THREAD

**Issue by SontungAnakin** [paiqo/Databricks-VSCode#154]
**Problem**
Calling %run with other simple notebook does not work. Referenced notebook is a simple with no other references - please see the attached screenshot.
![Screenshot 2023-04-28 at 16 34 40](https://user-images.githubusercontent.com/23339071/235192520-50d3d715-7505-4e4b-bcae-145168fce642.png)

**Expected behaviour**
To be able to run/include other notebooks

**Comment by gbrueckl** [comment]
this should be fixed with v2.1.3 which was just published

However, this also made me aware that the current implementation of `%run` has some limitations which are now also listed in the readme:

> However, there are some known limitations to `%run` as listed blow:
> - cells of referenced notebooks that use magics are not executed
>   - this also applies to `%run` (see below)
> - nested `%run` statements are not supported
>   - you might consider migrating to [Files in Workspace](https://docs.databricks.com/files/workspace.html)
>

**Comment by SontungAnakin** [comment]
I see I see, the fix works fine. Thank you!
The limitations are not so restrictive for me and it's good that they are stated in readme for better clarification.

Thank you a lot for the useful plugin again!
