### ISSUE TITLE
Instructions for limiting interaction with Databricks per config rather than permission

### ISSUE THREAD

**Issue by mikecrowe-8451** [paiqo/Databricks-VSCode#155]
When I log into DB Power Tools, I can see a ton of users/repos:

![image](https://github.com/paiqo/Databricks-VSCode/assets/127351560/d3833cc2-1dae-454c-bafb-be21f5da7dcc)

I'd like to configure the extension to just show me my stuff, i.e.:

* `Users/m9...` 
* `Repos/m9....`

etc.  It feels like this could/is a config setting, but I can't figure out how to limit things.  Is this possible somehow?

If it involves specifying an Azure resourceId, is there a guide somewhere on how to even find that?  I wasn't sure if that's the right setting or not

**Comment by gbrueckl** [comment]
That idea already surfaced at the very beginning of this extension https://github.com/paiqo/Databricks-VSCode/issues/4

However, we decided to implement it differently using VSCode File System Providers 
so you can easily add `wsfs:/Users/m9...`, `wsfs:/Repos/m9...` or any other path of your choice to your VSCode workspace/explorer as described here https://github.com/paiqo/Databricks-VSCode#file-system-integration
