### ISSUE TITLE
Allow insecure flag in databricks power tool configuration

### ISSUE THREAD

**Issue by DrM0SK4** [paiqo/Databricks-VSCode#156]
Hi all,
I am using the following configuration to connect to databricks.
<img width="429" alt="image" src="https://github.com/paiqo/Databricks-VSCode/assets/18470176/ec32a1a6-58f3-40fe-94aa-4563ab3b36cf">
As you can see when setting the [insecure flag](https://stackoverflow.com/a/65285795) allows me to connect to databricks.
<img width="850" alt="image" src="https://github.com/paiqo/Databricks-VSCode/assets/18470176/d9f2d999-fe71-4b52-ba7b-08a791db98b2">
Removing the field gives me this error.
<img width="850" alt="image" src="https://github.com/paiqo/Databricks-VSCode/assets/18470176/78544819-be80-4b98-8413-f6e731bf8f25">

Because databricks power tool extension does not allow me to configure the insecure flag or does not pick up the value I get this error.
<img width="688" alt="image" src="https://github.com/paiqo/Databricks-VSCode/assets/18470176/68b77019-029f-4ece-8572-535dad6a899e">
Is there a way to pass the flag to the extension when connecting to the cluster?
Please let me know.

Kind regards

**Comment by gbrueckl** [comment]
can you please try to set `"http.proxyStrictSSL": false` in combination with `"http.proxySupport": "on"` in your VSCode settings

**Comment by DrM0SK4** [comment]
sorry for the late reply,
your fix works! 
thanks a lot :)
