### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by minhhieutran2112** [paiqo/Databricks-VSCode#157]
Hi all,

When I am trying to connect to databricks it is giving me this error:

![image](https://github.com/paiqo/Databricks-VSCode/assets/46810422/6e6923da-4fb3-4c0a-a393-35a7f3555a84)

I tried running a get request in my terminal and it was just fine:

![image](https://github.com/paiqo/Databricks-VSCode/assets/46810422/a8c6e9db-a450-4a4e-a686-942387261ab9)

Can you please help?

Thanks!!

**Comment by gbrueckl** [comment]
do you have any specific configuration with proxies etc. that use certificates?
also, what kind of Configuration Manager are you using?

you might want to try to set "http.proxyStrictSSL": false in combination with "http.proxySupport": "on" in your VSCode settings

**Comment by gbrueckl** [comment]
closing as no further feedback was provided
