### ISSUE TITLE
Mixing display(<string>) and display(<dataframe>) not working 

### ISSUE THREAD

**Issue by krzysztof-nawara-bp** [paiqo/Databricks-VSCode#158]
Hello,

In my workflow it's quite common to `display` multiple outputs from a single cell.
This seems to work fine, as long as I'm displaying strings:
```
display("1")
display("2")

#display(spark.createDataFrame([("1", "2")], ["a", "b"]))
#display(spark.createDataFrame([("1", "2")], ["a", "b"]))
```

<img width="441" alt="image" src="https://github.com/paiqo/Databricks-VSCode/assets/118826183/04200b83-df29-4918-a6bf-517b4f83611b">

However, as soon as I try to display dataframe, strings are no longer printed - and I see only one data frame.
```
display("1")
display("2")

display(spark.createDataFrame([("1", "2")], ["a", "b"]))
#display(spark.createDataFrame([("1", "2")], ["a", "b"]))
```
<img width="953" alt="image" src="https://github.com/paiqo/Databricks-VSCode/assets/118826183/8cc84ea1-ed73-4cad-8fc4-77d43a233ddf">

I've found this bit in the documentation:

> Due to the limitations of the underlying APIs, the output is limited to one output type so you should avoid mixing print(...), display(df) and df.plot as only one of them will be shown.

I take this to mean that as long as I'm using single output type, having multiple outputs should not be an issue. Have I misunderstood?

**Comment by gbrueckl** [comment]
thats actually another limitation of the underlying API, only the last dataframe will be returned and hence can be displayed in VSCode as output
back when this was implemented this was also the same behavior in the Databricks Web UI hence it is not explicitly mentioned in the docs

I will update the docs to also make this clear

**Comment by krzysztof-nawara-bp** [comment]
That's not ideal, but still it's a great extension - thanks for sharing your hard work :) 

I have developed this (rather nasty) work-around. If there are better ways to do it I'd love to hear about them
```
from typing import Any, List, Union, Callable
from pyspark.sql import DataFrame


class OutputManager():
    DF_MAX_ELEMENTS = 10
    DF_MAX_LEN = 50

    _outputs: List[Union[DataFrame, str]]
    _original_display: Callable[[Any], None]

    def __init__(self):
        self._outputs = []

    def append_output(self, output: Union[DataFrame, Any]) -> None:
        self._outputs.append(output)

    def display(self) -> None:
        repr_ = ""
        for output in self._outputs:
            if isinstance(output, DataFrame):
                repr_ += output._jdf.showString(self.DF_MAX_ELEMENTS, self.DF_MAX_LEN, False) + "\n"
            else:
                repr_ += str(output) + "\n"
        print(repr_)
        self._outputs = []

    def __enter__(self):
        self._outputs = []
        global display
        self._original_display = display
        display = self.append_output
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        self.display()
        global display
        display = self._original_display


with OutputManager():
    print(display)
    display("Hello, world!")
    display(spark.createDataFrame([("a", 1), ("b", 2)], ["letter", "number"]))
```

**Comment by krzysztof-nawara-bp** [comment]
> regarding your solution: I just had a quick look and it seems like it "only" prints the output which means we would loose all the capabilities that data table renderers would provide, right?

That's exactly how it works. To be honest I have no idea how to make it work with renderers

**Comment by gbrueckl** [comment]
just started a discussion with the guy from Data Table Renderers
https://github.com/RandomFractals/vscode-data-table/issues/152

**Comment by RandomFractals** [comment]
This is a very unusual ask. Most notebooks produce only one data to text output. 

We suggest your users put the second `display(...)` call in the next notebook cell.

**Comment by krzysztof-nawara-bp** [comment]
@RandomFractals I don't really have any data to judge whether it's usual or not - I only know that Databricks web interface supports it. I'm fairly sure Jupyter does too.

My personal experience is that I try (as much as possible) to organise my code into function, which may in turn call other functions. They all do data processing and they also do verification/sanity checks on data.

Not all checks can be expressed as simple conditions, sometimes it's easier and faster to just show statistics with some content (e.g. histogram of values to see the scope of deviation, or table of counts to "eyeball" whether they are +/- right).

Even when I'm able to put clear conditions on my assertions (primary key validation, integrity checks, non-nullability), the next step of investigation is to see which rows has caused assertion to fail. _display_ is perfectly suited to it, gives you as much context as possible.

But the consequence is that, if they are multiple layers of utilities and processing functions, _display_ can be invoked multiple times.

Fortunately there are workarounds available, even if they cannot match the beauty and functionality that your extension offers :)

**Comment by RandomFractals** [comment]
@krzysztof-nawara-bp I totally understand what your asking for, but that would require major changes to the way our data table renderers check for json array data and text data output, and some of that api has changed since we create those renderers.

We will take a note of your edge use case, but general 80/20 rule is still most JS or Py notebook cell should produce a single output data to render, json array data in our case, wrapped text output is more of a side effect to address the current built-in vscode ext. text mime type renderer.

**Comment by krzysztof-nawara-bp** [comment]
@RandomFractals Makes a lot of sense, just wanted to explain my usecase. Keep up the good work! :)

**Comment by gbrueckl** [comment]
@RandomFractals would it work if I create multiple notebook outputs, one for each table to be displayed?

**Comment by gbrueckl** [comment]
closed as no further info was provided
