### ISSUE TITLE
ERROR: TypeError: Cannot read properties of undefined (reading 'content')

### ISSUE THREAD

**Issue by liadpictime** [paiqo/Databricks-VSCode#159]
Hey hello,
While working on the notebooks in my workspace, some of the online notebooks could not be downloaded while others are ok: 
![image](https://github.com/paiqo/Databricks-VSCode/assets/124503835/8b8dafce-1342-4adf-b244-189ba5a78170)

Here I'm trying to download and work on the notebook gold layer but this error appeared 
![image](https://github.com/paiqo/Databricks-VSCode/assets/124503835/ca281b23-31c6-47dc-a7f5-cb0f6c14cdc2)

Is it something regarding my file type configurations?

thanks in advance

**Comment by gbrueckl** [comment]
hmm, hard to say, according to the logs it tries to export it as JUPYTER notebook which I guess is fine (and is also the default for Python notebooks)
can you check whats in your local folder?
it could be that the same file but with `.py` exists already and is causing issues
its also worth checking, if the notebooks are particularly big (size)

according to the screenshot "2 Silver Layer" did download correctly, is there anything specific about this notebook?

regards,
-gerhard

**Comment by liadpictime** [comment]
Erased existing files just to download the relevant ones, still not working.
The gold layer is around 27MB, is it too big?
Any way I think it might be with the content it self, I'm still trying to understand why..

**Comment by gbrueckl** [comment]
27MB sounds quite big and can definitely cause issues while downloading (I think the API limit is somewhere around 2MB)

As I expect that most of this 27MB is output cells, you might want to try to change the export formats from `.ipynb` to `.py` as described here: https://github.com/paiqo/Databricks-VSCode#setup-and-configuration-vscode-connection-manager

besides that, there is not much we can do here
