### ISSUE TITLE
Support magic %run command

### ISSUE THREAD

**Issue by BKoblinger** [paiqo/Databricks-VSCode#16]
Databricks supports the magic command `%run`. https://docs.databricks.com/notebooks/notebooks-use.html#run-a-notebook-from-another-notebook

In Databricks, the file in the magic `%run` command cannot have a file extension:
`%run ./myFunction`

Locally, after importing with the Databricks-VSCode extension, the file `myFunction` is renamed to `myFunction.py.ipynb`. When I try to run the notebook, an error is returned:
_ERROR:root:File './myFunction.py' not found._
because the local file is called `myFunction.py.ipynb`.

I can run the local file by modifying the magic command to:
`%run ./myFunction.py.ipynb`
but Databricks cannot find this file, because Databricks stores it as `myFunction`.
_Notebook not found: Users/ ... /myFunction.py.ipynb._

The easiest change I can think of would be to append `.py.ipynb` to the end of each magic `%run` command after downloading the file from Databricks, and then removing it when uploading the file back to Databricks.

**Comment by gbrueckl** [comment]
actually you can modify the extension of the downloaded files - it can either be .py or .py.ipynb (default)
the problem here is that if you change it to .py, VS Code will open it as a regular Python file and not as a notebook 
so this would solve your problem whit referencing the file but would cause your main Python file to also be opened as regular Python file

if the file you reference only contains functions and not necessarily has to be opened as notebook, you can simply rename your local file from myFunction.py.ipynb to myFunction.py so your reference works
your main Python file would still be called myMainFile.py.ipynb to ensure it is opened as a notebook

**Comment by BKoblinger** [comment]
Thanks for the prompt reply.

I tried what you suggested; however, myFunction.py.ipynb is not python, it is JSON, so the functions definitions are not seen.

In details:
I renamed myFunction.py.ipynb to myFunction.py.
`%run myFunction`
This is successful.
`print(myFun(2))`
_NameError: name 'myFun' is not defined_

I assume this is because myFunction.py contains a python dictionary:
`{"cells":[{"cell_type":"code","source":["def myFun(x):\n  return x + x"],"metadata":{},"outputs":[],"execution_count":1}],"metadata":{"name":"myFunction","notebookId":4420009728409474},"nbformat":4,"nbformat_minor":0}`

**Comment by gbrueckl** [comment]
yes, if the file was originally downloaded as myFunction.py.ipynb it will contain JSON. In this case you cannot simply rename it to myFunction.py as it would not be a proper Python file then. Can you manually download/export the file as "Source file" in the Databricks UI and then place it in the corresponding path under your localSyncFolder?

**Comment by gbrueckl** [comment]
Hi @BKoblinger, 
could you test my proposed solution?
if it is still not working I would need more information, otherwise i would close this ticket

**Comment by BKoblinger** [comment]
Hi @gbrueckl,
Thanks for getting back to me.
Unfortunately, I don't quite understand how your proposed solution addresses my issue.

The closest I can get is to set the export format to .py
`"databricks.connection.default.exportFormats": {"Python": ".py"}`
(or export from the Databricks UI, which also exports .py), and then make a _new_ myMain.py.ipynb. Then I can successfully run:
`%run ./myFunction`
But I still cannot use your add on to simultaneously develop myMain.py.

Our team calls Databricks Notebooks via the [Azure Data Factory Databricks Notebook activity](https://docs.microsoft.com/en-us/azure/data-factory/transform-data-databricks-notebook). We would like to work with both myMain and myFunction in VS Code.

**Comment by BKoblinger** [comment]
A possible solution would be to useCodeCells, exportFormat .py, and replace `# MAGIC %` with `%` when downloading the files from Databricks (and replace `%` with `# MAGIC %` when uploading to Databricks).

**Comment by gbrueckl** [comment]
regarding the original proposed solution:
if you have myFunction.py and myMain.py.ipynb in the same folder, the extension will display them both also in the same folder within the VS Code extension and allows you to edit both
you can also up-/download both files this way retaining the original local format
or do I get something wrong here?

Code Cells were introduced with release v.0.5.0 and basically add "# %%" after each "# COMMAND -----------" what databricks uses to define cells within regular Python source files. This way you would only have .py files and %run should just work

**Comment by BKoblinger** [comment]
Hi again!
I tried again. I didn't realize that the Databricks Extension could handle both .py and .py.ipynb at the same time.

1. I set: `"databricks.connection.default.exportFormats": { "Python": ".py.ipynb" }`
2. I downloaded myMain using the extension (as myMain.py.ipynb).
3. I downloaded myFunction using the Databricks UI (as myFunction.py) and I moved myFunction.py into the same folder as myMina.py.ipynb.
4. I can run myMain in VSCode successfully as expected.
5. Then, in VS Code, I added a new function to myFunction.py and I called that function in myMain.py.ipynb.
6. In the _Workspace_ panel, I see that myFunction is [Online only], so I click the refresh button. Now the _Workspace_ panel shows, [Synced]. 
7. I clicked "Upload" for both myMain and myFunction. I can see the changed in Databricks UI and everything works as expected.

**Comment by gbrueckl** [comment]
cool, great to hear!
I will close this issue then

One last note about supported file extensions: with the `exportFormats `configuration you can define the default format when downloading notebooks the first time. However, the VSCode extension does a matching based on the filename only (without extension) of the notebooks that are online and the files that are local, basically ignoring the actual file extension. This allows scenarios like yours and also gives a lot of flexibility also in other scenarios
