### ISSUE TITLE
Different behavior when using recursive "%run" magic command 

### ISSUE THREAD

**Issue by lomizandtyd** [paiqo/Databricks-VSCode#161]
Hi,

The nested magic command issue I encountered is:
1. I have a `init.ipynb` with multiple `%run xxx`  magic commands to import multiple notebooks.
2. I have a `task.ipynb` with `%run init` to import all functions with one magic command.
3. When I run the `task.ipynb` with power tools in VS Code, the output differs from what I get in databricks web editor.
4. After run `%run init`, cells below in `task.ipynb` couldn't read the definitions in `xxx.ipynb`. But it works in web editor.
5. If I run `%run xxx` in `task.ipynb` directly, I could get the definitions here.

The output of run `%run init` in `task.ipynb` with Databricks Power Tools in VS Code:
![image](https://github.com/paiqo/Databricks-VSCode/assets/5525904/7304c948-f47b-4053-a64b-75ef3fe8e5e0)

It outputs the source code of `init.ipynb`.

The output of run `%run init` in webui.
![image](https://github.com/paiqo/Databricks-VSCode/assets/5525904/25715a7c-1fe2-49a8-9a31-02768677f806)

Does nested magic command run work?

**Comment by gbrueckl** [comment]
unfortunately nested `%run` calls are not supported - this is also stated in the README.md:
> However, there are some known limitations to `%run` as listed blow:
> - cells of referenced notebooks that use magics are not executed
>   - this also applies to `%run` (see below)
> - nested `%run` statements are not supported
>   - you might consider migrating to [Files in Workspace](https://docs.databricks.com/files/workspace.html)
> 

please also see 
https://github.com/paiqo/Databricks-VSCode/issues/152
https://github.com/paiqo/Databricks-VSCode/issues/154

**Comment by krzysztof-nawara-bp** [comment]
@gbrueckl Sorry if this is not the right place to ask the question, but was it always the case that %MAGIC cells in %run notebooks are not executed? I used to have %autoreload in one of the notebooks that I'm %run'ing and I'm 90% it worked in the past
