### ISSUE TITLE
Image cell renderer not working 

### ISSUE THREAD

**Issue by phuismann** [paiqo/Databricks-VSCode#162]
I'm was trying to plot in cell mode and databricks power tools using matplotlib and always get empty cells. 

<img width="1240" alt="image" src="https://github.com/paiqo/Databricks-VSCode/assets/45405932/637ba3dd-5a70-4d20-9e95-7ffc50194f95">

Even tho the example is with geopandas just simple matplotlib lineplots are not showing up too. 

I tried using display(fig) aswell and am on Mac.

Ony idea what could be going wrong?

**Comment by gbrueckl** [comment]
do you have some full code as a repo so I could try to reproduce this on my side?
just has to be a simple plot

**Comment by phuismann** [comment]
I can provide you with a very very basic example of what doesnt work here:

```
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(20, 5))
x = [0, 10, 50, 100, 200]
y = [23, 21, 1,2 , 3]
ax.plot(x , y)

```
Sometimes I get the error: "TypeError: Cannot read properties of undefined (reading 'error')" 

Some other informations that are maybe relevant:
- I'm running it on a Personal Compute Cluster
- VSCode Version 1.79
- macOS Ventura 13.2.1 (M2 Max Chip)

**Comment by JuanEcheagaray75** [comment]
I'm experiencing the same issue here, except my VS Code instance is running on an Azure Virtual Desktop machine

**Comment by gbrueckl** [comment]
I just tried the sample code and it worked as epxected:
![image](https://github.com/paiqo/Databricks-VSCode/assets/11884402/6aac2bca-a29f-4aa4-a585-0ced5aae262c)

it might be related to MacOS though as the image is returned as PNG which does not work well with MacOS ?! (I am not a MacOS user :D )

**Comment by gbrueckl** [comment]
closing as no further feedback was provided and issue is not reproduceable

**Comment by tsveiga** [comment]
Hi! Reusing this issue to avoid openning a new one on the same topic.

I am experiencing the same behavior as described by the above users, although without any errors. Taking the basic example given before, the cell outputs only the handle of the plot.

![bilde](https://github.com/paiqo/Databricks-VSCode/assets/45718165/35273cf5-121b-4d30-8bc6-ff866186c0ed)

After digging a bit, it seems that the raw file does not include the image data. This is the raw data for this cell, under "data" there should be an image field.

![bilde](https://github.com/paiqo/Databricks-VSCode/assets/45718165/dcd48551-d01f-4cdc-a9f2-295bc31ba950)

Furthermore, if I run the cell directly in Databricks through the browser UI and download it afterwards, then downloaded notebook includes the image data and it gets properly displayed. Also, if I run the notebook locally then it is fine as well.

I am VSCode v1.84.2 on Windows 10 with the latest extension version, but have tried on a setup with Linux Mint with the same behavior.
Thankfully if we can get some pointers on this!
