### ISSUE TITLE
[bug] Enabling power tool extension makes all prints to duplicate upon.

### ISSUE THREAD

**Issue by vityas** [paiqo/Databricks-VSCode#163]
Is it possible to weaken the dependence of power tools on the **Data Table Renderers** extension? (maybe we could disable it, while keeping power tools enabled).

As soon as I enable it (including on a clean install of VS code) stdout/stderr start duplicating (not flashed when the cell is rerun)
[possible regression] Is it something caused recently?

Steps to diagnose
-------------

- the first thing I checked was if those outputs were present in the json source, and the answer was no
- then I disabled every extension one-by one, "Data Table Renderers" is certainly the culprit.

Video
----------------
![dbr_bug](https://github.com/RandomFractals/vscode-data-table/assets/12552690/68a93d06-504e-4113-be2c-e42a4edc1091)

hopefully, this is reproducible

**Comment by gbrueckl** [comment]
There is no hard dependency, and we will consider it in the future.
But technically speaking, the output is produced by the notebookkernel and the notebook [output] renderer simply displays it.
In your example its one output (as expected) but it is rendered 3 times. Now the question is what output is actually sent from the kernel to the renderer.

Anyway, you can always change the renderer for each individual output by clicking the [...] button next to it

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Vitya Alexandrov ***@***.***>
Sent: Wednesday, July 5, 2023 3:03:40 AM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] [bug] Enabling power tool extension makes all prints to duplicate upon. (Issue #163)


Is it possible to weaken the dependence of power tools on the Data Table Renderers extension? (maybe we could disable it, while keeping power tools enabled).

As soon as I enable it (including on a clean install of VS code) stdin outputs are duplicated (not flashed when the cell is rerun)
[possible regression] Is it something caused recently?

Steps to diagnose

  *   the first thing I checked was if those outputs were present in the json source, and the answer was no
  *   then I disabled every extension one-by one, "Data Table Renderers" is certainly the culprit.

Video

[dbr_bug]<https://user-images.githubusercontent.com/12552690/251008757-68a93d06-504e-4113-be2c-e42a4edc1091.gif>

hopefully, this is reproducible

**Comment by vityas** [comment]
Thanks, Gerhard. 
1. were you able to reproduce it?
2. Changing renderer via [...] to a built-in default solved my issue (and, of course disabled `display(df)` render)
3. How do we get to the root of the problem? How can i help?

thanks!

**Comment by gbrueckl** [comment]
yes, I can reproduce it
but as it does not seem to happen if you use a Databricks Kernel but only for regular Jupyter/Ipython kernels, there is not much I can do about it

I have seen you also opened an issue for the Renderer Extensions (https://github.com/RandomFractals/vscode-data-table/issues/153) which is probably the best way to address this

we will though consider removing the dependency in the future as it is no hard dependency but more like a nice add-on to our extension

**Comment by gbrueckl** [comment]
the issue got fixed in the referenced Rendering Extension
