### ISSUE TITLE
Outline view not populated when editing .py Workspace Files

### ISSUE THREAD

**Issue by m-marquis** [paiqo/Databricks-VSCode#168]
Thanks for this great tool!

It would be really nice if the VScode Outline view populated properly when editing non-notebook .py files that have been opened via the File System Integration feature.

For context, I'm trying to edit Databricks Workspace Files (.py) that are part of custom modules used by my notebooks. As far as I can tell, it is not possible to see the symbol tree of those files in the Outline view when they are opened from the virtual file system.

For this use case I wouldn't need the ability to actually run those files from vscode, just edit them and have any saved changes synced with my Databricks workspace.

**Comment by gbrueckl** [comment]
as it seems the built-in Outline view does not work with custom File System Integrations or probably simply does not support URIs but only local paths - probably nothing we can fix in the short term
might be something that could be addressed by custom outline/codemap extensions 

I opened a feature request here so if they implement support for custom file system providers, you could use that extension
https://github.com/Gerrnperl/outline-map/issues/48
