### ISSUE TITLE
Cannot attach cluster 

### ISSUE THREAD

**Issue by Createdd** [paiqo/Databricks-VSCode#169]
I use the latest version and cannot attach a cluster because it yields:
![image](https://github.com/paiqo/Databricks-VSCode/assets/22077628/bfed91a4-4e15-4800-8ea9-136a100aaad4)

The cluster is connected and running, but I cannot run any queries.

**Comment by gbrueckl** [comment]
are you using the Databricks Power Tools in combination with the Databricks Extension and want to derive the cluster settings from there or using it stand-alone?

**Comment by gbrueckl** [comment]
according to the error message, the error comes from the Databricks extension and not from our Power Tools extension

when exactly do you get that error? where do you click?

**Comment by Createdd** [comment]
I attached the wrong screenshot.  this is the correct one: 
![image](https://github.com/paiqo/Databricks-VSCode/assets/22077628/3548f0d1-760d-4d1b-8a4d-7e7dac858f5e)

when I want to execute "attach cluster" from the command palette I get this error

**Comment by gbrueckl** [comment]
ah ok, that makes sense, the command requires a cluster-object 
to use "Attach Cluster" from Power Tools, you need to use the button in the Cluster Manager. 
![image](https://github.com/paiqo/Databricks-VSCode/assets/11884402/732dac43-43ce-4ccb-8943-4dfeb075c137)

**Comment by Createdd** [comment]
yes. but when i click that nothing happens.

**Comment by gbrueckl** [comment]
well, you should see that cluster then being selected in the Databricks Extension
![image](https://github.com/paiqo/Databricks-VSCode/assets/11884402/c51c9ac8-8626-4200-a683-b1e57df40d14)

**Comment by Createdd** [comment]
yes it is selected, but in the sql tab it says: 
![image](https://github.com/paiqo/Databricks-VSCode/assets/22077628/0de4a81b-c180-436a-b25c-46cfdc2bc16c)

**Comment by gbrueckl** [comment]
SQL Browser should work as long as you have at least one running cluster
by explicitly using "Attach Cluster" you select that cluster to be used for the Databricks Extensions and also for the SQL Browser

can you click the Refresh-Button in the SQL Browser please and check the output logs:
![image](https://github.com/paiqo/Databricks-VSCode/assets/11884402/de748af5-d761-48ff-bcb5-0756cf72992e)

**Comment by Createdd** [comment]
ok thanks for the tip! it yields me only this: 

![image](https://github.com/paiqo/Databricks-VSCode/assets/22077628/11f5b83d-1a3e-47b7-add5-ba121b7c9a40)

 not quite sure what it should tell me?

**Comment by gbrueckl** [comment]
that one response that says `"status":"Finished"` also has the `"results"` property which would contain a list of database as you can see in my screenshot.
Your screenshot is unfortunately cut off so I dont see the output but I assume its quite short and might not contain any databases?!?

we are basically just running a `SHOW DATABASES` via SQL and for every entry in the returned table, we create an item in the SQL Browser

please try to run `SHOW DATABASES` also in a notebook to see the results
if you get a proper output there but the SQL Browser still is not working, it would be great if you could send the full screenshot
