### ISSUE TITLE
Any way to share a notebook's execution contexts between vscode and databricks web UI?

### ISSUE THREAD

**Issue by jdanbrown** [paiqo/Databricks-VSCode#174]
When I open the same databricks notebook in separate browser tabs, they automatically share the same execution context. This is really useful, because I know there's only ever one execution context regardless of how many times I happen to have opened (or accidentally refreshed) the same notebook in my browser. Knowing there's only one execution context gives me a very simple mental model of how to execute and manage my code in a long-running notebook that I come back to multiple times a day, and over multiple days.

In vscode, it'd be really useful to enable the same behavior. Currently, when I open the same databricks notebook in vscode and the databricks web UI, each gets a separate execution context. This is surprising because long-running data I computed on one side isn't available in the other, which is different than how opening the same databricks notebook in multiple browser tabs works. Also, I think it'd be a simpler — and more flexible! — UX if vscode and databricks automatically shared the same execution context, inline with the simpler mental model above.

Do you think this is possible? Looking through the databricks api docs I don't see a way to list the current execution contexts on a cluster, e.g. to find and reuse one created from a web notebook. 
- https://docs.databricks.com/api/workspace/commandexecution

I guess it's also out of our control to make the databricks web UI find and reuse an execution context created by vscode, but even if it only worked in one direction (open notebook in databricks web UI, then open in vscode), that would still add a lot of flexibility to the UX.

**Comment by gbrueckl** [comment]
while I also think that this could provide some value, I do not think this is possible - at least no with the existing APIs.

we will keep it in mind but it will definitely not be implemented (if possible at all!) in the near future
