### ISSUE TITLE
Magic commands not properly executed.

### ISSUE THREAD

**Issue by cyaris** [paiqo/Databricks-VSCode#175]
Consider a notebook called `file1.ipynb` that begins with a cell saying `%pip install attrmap==0.0.7`. I can run this notebook as intended.

Now, consider a second notebook called `file2.ipynb` containing a cell `%run ./file1`. This notebook will execute the installation command in `file1.ipynb` as markdown instead of recognizing it as a magic command.

**Comment by gbrueckl** [comment]
please check the limitations mentioned at https://github.com/paiqo/Databricks-VSCode#notebook-kernel

> cells of referenced notebooks that use magics are not executed
this also applies to %run (see below)

**Comment by gbrueckl** [comment]
closing as this issue is a know limitation and is also documented
