### ISSUE TITLE
Files cannot be created

### ISSUE THREAD

**Issue by janosbiro** [paiqo/Databricks-VSCode#176]
Hey,

I had issues with .py duplication as ipynb. When I have saved or created a .py file in the attached workspace my py file is automatically filled with the string version of a jupyter notebook in v2.1. So I have changed to v2.2.3 as I noticed this issue was fixed in that. 
Unfortunately I can't create files now in the attached workspace. The error I got is complaining about it cannot resolve path since the file is nonexistent. Do you know this issue or is it maybe for me only?

Thanks in advance for your answer.

**Comment by gbrueckl** [comment]
where do you want to create the file? 
in your local file system under `localSyncFolder`?
or have you mounted the Databricks Workspace File System using a the `wsfs:/` scheme in your VSCode workspace?

**Comment by janosbiro** [comment]
wsfs:/ 

Previous versions worked fine - but with latest version it can only use existing paths. 
So if file is exist in wsfs then I can save it.
If the file is not exist and I want to create in the wsfs workspace - it gives the error about resolving path of nonexistent.

I have found it easier for other reasons to use localSyncFolder now - but that would be nice if I could create files instantly in wsfs in the future.

**Comment by gbrueckl** [comment]
this will be fixed with the next release

**Comment by gbrueckl** [comment]
just released v2.2.4 where this is fixed!
