### ISSUE TITLE
Error: EntryNotFound

### ISSUE THREAD

**Issue by raffael-paiva-hsb** [paiqo/Databricks-VSCode#178]
Hello,

I'm trying to sync the extension to my Databricks environment for the first time, I can establish the connection, but I can't access any file, everytime I try to open or download a file I receive the following error message:

![image](https://github.com/paiqo/Databricks-VSCode/assets/105434387/3e7a0474-6322-4ea4-a574-4af27f976243)

I've tried to change folders, and the problem persists, I'm doing something wrong? I've followed the configuration guide, and I can see all the available files, I just can't open them

**Comment by gbrueckl** [comment]
did you set your sync folder accordingly?
do you see items local items and/or remote items?
I assume you are using the workspace browser, right? (and not the `wsfs:/` file system integration)

**Comment by gbrueckl** [comment]
do you have any feedback for me on this @raffael-paiva-hsb otherwise I will have to close this issue

**Comment by raffael-paiva-hsb** [comment]
Hello @gbrueckl, I'm sorry for the late reply, you can close the issue, I've realized the problem was on my environment. Thank you for reaching me!
