### ISSUE TITLE
Language for extension '.py.ipynb' is not defined!

### ISSUE THREAD

**Issue by kyy-ai-2017** [paiqo/Databricks-VSCode#18]
After exporting the notebooks as ".py.ipynb" from Databricks, I got the following error:

"Language for extension '.py.ipynb' is not defined!"

and WORKSPACE does not show the exported notebooks, though the files are successfully downloaded to my local machine.

If the notebooks are exported as ".py", then everything works fine. 

Any idea of what the problem might be?

**Comment by gbrueckl** [comment]
seems like I introduced a bug with the latest release - already have a clue what it is and will have a look and hopefully fix it tomorrow!

**Comment by kyy-ai-2017** [comment]
Well, I just added another case right above .ipynb in LanguageFileExtensionMapper.js, and it seems to do the trick. :-) 

```    
static fromExtension(extension) {
        let ret = new LanguageFileExtensionMapper();
        ret._extension = extension.toLowerCase();
        ret._isNotebook = false;
        ret._exportFormat = "SOURCE";
        switch (ret.extension) {
            case ".py":
                ret._language = "PYTHON";
                break;
            case ".py.ipynb":             // <-----------------------
            case ".ipynb":
                ret._language = "PYTHON";
                ret._isNotebook = true;
                ret._exportFormat = "JUPYTER";
                break;
            case ".r":
                ret._language = "R";
                break;
            case ".Rmd":
                ret._language = "R";
                break;
            case ".scala":
                ret._language = "SCALA";
                break;
            case ".sql":
                ret._language = "SQL";
                break;
            default: throw new Error("Language for extension '" + ret.extension + "' is not defined!");
        }
        return ret;
    }
```

maybe similar change in LanguageFileExtensionMapper.ts would resolve the issue?

**Comment by kyy-ai-2017** [comment]
[Updated]

Well, adding the following to the fromExtension function in LanguageFileExtensionMapper.js seems to do the trick:

```
            case ".py.ipynb":
                ret._language = "PYTHON";
                ret._isNotebook = true;
                ret._exportFormat = "JUPYTER";
                break;
```

Adding that to LanguageFileExtensionMapper.ts would resolve this issue, maybe?

**Comment by gbrueckl** [comment]
looks promising!
but let me quick check all the other dependencies before I deploy a fix today

**Comment by gbrueckl** [comment]
just fixed it with v.0.5.2
your findings were a good starting point already :)

the extension ".py.ipynb" was now removed from the valid configuration settings (still works though) but for the future only ".py" for raw python files and ".ipynb" for IPython notebooks are supported - both are associated with language = PYTHON

**Comment by kyy-ai-2017** [comment]
Thanks a lot for the quick fix! Works like a charm! :-)
