### ISSUE TITLE
Filter functionality in the browse section

### ISSUE THREAD

**Issue by jianchen1628** [paiqo/Databricks-VSCode#182]
Great tool to write your code on vscode as an alternative to the UI.
Regarding this CR, it would be great if there is some kind of filter option in the browse section.
E.g. I'm one of many Databricks user on a regular base in my company, thus we have a quite a lot workspaces and cluters.
Having the functionality to filter, or considering the cluster section to choose the clusters I'm assigned to would ease the work quite a lot!

**Comment by gbrueckl** [comment]
as for all tree views in VSCode you can just press `CTRL + F` inside the treeview to get a filter capabilities

what I could think of alternatively is a config that allows you to specify a regex to filter for specific items only - would that help?

**Comment by jianchen1628** [comment]
That's a fair point. How could I miss that...
No, it's fine, I'm happy with that. Thank you!
We can close this.
