### ISSUE TITLE
Unable to use OAUTH with Databricks Power Tool extension 

### ISSUE THREAD

**Issue by massal07** [paiqo/Databricks-VSCode#184]
I have recently installed the extension and I use the Databricks CLI connect manager. 
Unfortunately, the extension does not automatically connect to the workspaces listed in my ~/.databrickscfg file. 
It only works, when I generate a PAT and put it in the ~/.databrickscfg. 
For security matters, we should avoid generating Personal Access Tokens and it would be highly beneficial if the extension could integrate OAuth for authentification, providing a more secure experience. 

Thank you for considering the improvement.

**Comment by gbrueckl** [comment]
instead of PAT or Databricks CLI Authentication you can also use already use OAuth for Azure Active Directory as stated in the docs
https://github.com/paiqo/Databricks-VSCode?tab=readme-ov-file#setup-and-configuration-azure-connection-manager
this way you do not need to use PAT at all

**Comment by gbrueckl** [comment]
closed as no further info was provided
