### ISSUE TITLE
not able to see Workspace Manager or download files into a local folder

### ISSUE THREAD

**Issue by shunfoto** [paiqo/Databricks-VSCode#186]
I have tried Azure, PAT, Databricks CLI so far. They all worked and I can run it on the remote cluster.

However I can't see Workspace Manager from Databricks Power Tools.

It doesn't seem to download into a specified local folder either. How can I fix this issue?

I am using Mac with VSCODE 1.86.2 with Databricks Power Tools ver.2.2.4

I have setup a Local Sync Folder recommended with a template 'myUser/mySyncFolder'

<img width="271" alt="image" src="https://github.com/paiqo/Databricks-VSCode/assets/136023992/497c92d5-ad03-4914-96af-29d6d29b69e1">

**Comment by gbrueckl** [comment]
the only reason we are hiding the Workspace Manager is if you are on a virtual workspace, e.g. accessing/using the extension via the browser (e.g. https://vscode.dev ) as there is no local file system to download the files to

besides that, it could be that you disabled/hide it manually- you can easily check that by right-clicking any of the other tabs
![image](https://github.com/paiqo/Databricks-VSCode/assets/11884402/b0d93bd9-9b60-45e3-817d-3e930ce1964d)

**Comment by gbrueckl** [comment]
closed as no further info was provided
