### ISSUE TITLE
Synchronization with github

### ISSUE THREAD

**Issue by IuriiBakach** [paiqo/Databricks-VSCode#188]
I am exploring this extension, and I am trying to understand how to set it up in order to be able to push my code to the remote branch. 

I was able to synchronize my databricks account with vs code and I could check out a several branches using extension. Under Workspace I was able to open a few files and modify them. I wonder if it is possible to directly push to remote using this extension. I can upload to databricks and push from there, but I'd prefer to omit that step and do it directly from vs code, if possible?

I apologize if it's a wrong place for such a question.

Thank you

**Comment by gbrueckl** [comment]
yes, thats the right place :) 
first of all it would be important to know which Execution Mode you are using
https://github.com/paiqo/Databricks-VSCode?tab=readme-ov-file#execution-modes

For Live-Execution, you are working directly with the files in the Databricks workspace without a local copy in your file system. Hence all changes you make are immediately pushed to the Databricks workspace.

For Offline-Execution, you need to save your changes locally and then Upload/Push them to the Databricks Workspace manually.

in both cases, the last step you always need to do is to push the changes to the actual git repository attached to the Workspace using the [Repo Manager](https://github.com/paiqo/Databricks-VSCode?tab=readme-ov-file#repo-manager)

**Comment by IuriiBakach** [comment]
Thank you for update!

Unfortunately, when I mouse over the repo in the Repo Manager, I only see these 2: pull and check out. I don't see a push as you have under the pic for it.

![image](https://github.com/paiqo/Databricks-VSCode/assets/40870076/8c8134e3-678f-47ec-aec6-9010c91096d2)

Is there a way to enable it?

**Comment by gbrueckl** [comment]
well, if it is working in the Databricks UI, it should also work in the VSCode extension - can you check if it works in the DAtabricks web UI?

**Comment by IuriiBakach** [comment]
> well, if it is working in the Databricks UI, it should also work in the VSCode extension - can you check if it works in the DAtabricks web UI?

Yes, it works with databricks, I was doing it so for a while before discovering VSCode integration. Although, the way it's set up in our team, one needs to spin up a separate cluster to be able to push and pull from web UI. this cluster is also present in VSCode, I can not check out different branches without it running for instance.
![image](https://github.com/paiqo/Databricks-VSCode/assets/40870076/65461c33-fe0d-4454-9ada-27c5ec3c7ed7)

however even if it's running, the push button does not appear...

**Comment by gbrueckl** [comment]
just realized that there is no REST API to push changes to the remote repository - hence there is also no Push-Action implemented in VSCode
https://docs.databricks.com/api/azure/workspace/repos

so I am afraid we cannot support this until the required APIs are provided by Databricks, sorry for the confusion

**Comment by gbrueckl** [comment]
Live mode works by "mounting" your Databricks Workspace into the filesystem of VSCode. It is mandatory that your current VSCode session uses a VSCode workspace. If you dont have one already, you can just File -> Save As Workspace

once you have a VSCode Workspace you can use the icon in the Workspace Browser:
![image](https://github.com/paiqo/Databricks-VSCode/assets/11884402/6524fb8c-159e-4634-85f1-359abcc3248d)
This will create a new entry in the VSCode solution explorer representing the current items on Databricks.
![image](https://github.com/paiqo/Databricks-VSCode/assets/11884402/c64dd66f-6bf6-4a80-8a24-0148ca8a701d)
From there on it behaves just like any other local file system. It supports drag& drop, renaming, etc.

**Comment by gbrueckl** [comment]
yes - as of now, thats the only way - unfortunately :(

closing this issue as there is currently nothing I can do to solve this
