### ISSUE TITLE
ERROR: SyntaxError - Unexpected token '<', "<!doctype "... is not valid JSON

### ISSUE THREAD

**Issue by kimisikainai** [paiqo/Databricks-VSCode#193]
when i try to get the  cluster list ,I encounter the following error:

GET 2.0/clusters/list --> null
ERROR: SyntaxError - Unexpected token '<', "<!doctype "... is not valid JSON

**Comment by gbrueckl** [comment]
this usually indicates an authentication issue where instead of a JSON an HTML of the login page is returned
you might find more information in the logs (Outputs -> Databricks VSCode)

what authentication method / which connection manager are you using?

**Comment by kimisikainai** [comment]
The logs do not provide more useful information. For more details, please see the image below.

![image](https://github.com/paiqo/Databricks-VSCode/assets/16152606/d970d21e-e5d9-425a-b5df-dd83d0c068ab)

**Comment by gbrueckl** [comment]
please scroll to the top/beginning of the logs as we do some basic connecitvity check when the extension starts
also, did you provide the Personal Access Token (PAT) in your VSCode settings and did you set all other configurations accordingly?
can you share them? (without sensitive information of course)

**Comment by kimisikainai** [comment]
Although I don't know the reason, when I switched to a different computer and used the same token, there was no problem. So let's close this issue for now. If I discover anything more, I'll update it.

**Comment by kimisikainai** [comment]
The cause has been found. It was due to a proxy setting in VSCode. After removing the proxy setting, everything returned to normal.
