### ISSUE TITLE
Linting in Python Databricks Notebooks

### ISSUE THREAD

**Issue by CapCaWork** [paiqo/Databricks-VSCode#198]
Hi guys, 
I really like the extension, thanks a lot for the great work! 

Right now, I setup a whole development workflow with remote compute engine on Databricks. This also includes Linting (e.g. via PyLance), however it looks like that for *.py Notebooks I don't have linting: 

<img width="745" alt="Bild (4)" src="https://github.com/user-attachments/assets/78da2a76-b8f1-4cb3-8d21-0e24ce88fa19">

Whereas when I am using normal .ipynb I have linting included: 

<img width="745" alt="Bild (3)" src="https://github.com/user-attachments/assets/5029497f-bf01-441d-a8be-3bf873f70e2e">

Is there also a chance I can setup linting for Python Notebooks? 

My .vscode JSON: 

```json
{
    "workbench.editorAssociations":{
        "*.scala": "databricks-notebook",
        "*.sql": "databricks-notebook",
        "*.r": "databricks-notebook",
        "*.ipynb": "databricks-notebook",
        "*.py": "databricks-notebook"
    },
    "databricks.connection.default.exportFormats": 
    {
      "Scala": ".scala",
      "Python": ".py",
      "SQL": ".sql",
      "R": ".r"
        },
    "python.envFile": "${workspaceFolder}/.databricks/.databricks.env",
    "databricks.python.envFile": "${workspaceFolder}/.env",
    "jupyter.interactiveWindow.cellMarker.codeRegex": "^# COMMAND ----------|^# Databricks notebook source|^(#\\s*%%|#\\s*\\<codecell\\>|#\\s*In\\[\\d*?\\]|#\\s*In\\[ \\])",
    "jupyter.interactiveWindow.cellMarker.default": "# COMMAND ----------",
    "notebook.defaultFormatter": "ms-python.pylint",
    "notebook.formatOnSave.enabled": false,
    "jupyter.interactiveWindow.cellMarker.decorateCells": "allCells",
    "editor.defaultFormatter": "ms-python.pylint",
    "pylint.args": [
        "\"pylint.args\":[\"--load-plugins\",\"databricks.labs.pylint.all\"]"
    ],
    "python.analysis.inlayHints.variableTypes": true,
}
```

Thank you! 

Best, Christoph

**Comment by CapCaWork** [comment]
Update: renaming the Python Notebooks from *.py to *.ipynb.py does the trick with the vscode configuration: 

```json
{
    "workbench.editorAssociations":{
        "*.ipynb.py": "databricks-notebook",
        "*.scala": "databricks-notebook",
        "*.sql": "databricks-notebook",
        "*.r": "databricks-notebook"
    }
}
```

**Comment by gbrueckl** [comment]
thats a bit weird, it should not make a difference
I think linting is also based on the  language mode of the code-cell which can changed at the right bottom of each cell

thereby it should be independent of the notebook you use, whether its regular ipynb or the `databricks-notebook` (which basically just renders your .py source file as Notebook)
