### ISSUE TITLE
New Feature: Saving to DBFS

### ISSUE THREAD

**Issue by JacekPliszka** [paiqo/Databricks-VSCode#20]
Currently when you click on file in DBFS it is copied to tmp location and opened in editor.

File can be edited but after save only local copy is saved.

What I would love to have is some mechanism for saving to remote dbfs files.
It could be either icon at the top right editor window (if opened editor file remebers its source)
or a small icon next to delete and download  - e.g. 'upload from window' one that will upload contents of currently opened window there

**Comment by gbrueckl** [comment]
good idea - definitely something we will consider for the next release!
I will keep you updated here

**Comment by JacekPliszka** [comment]
Is there any 'contributing guide' ?  I've never written anything in TypeScript not mentioning VS Code extension but if there were good instructions I could try.

I've tried modifying files in .vscode/extensions/paiqo.databricks-vscode-0.2.5/out and restarting VSCode but it does not work.

My current idea is that download sets this._local_copy_path and upload uploads file from this path.

Though someone more skilled could do more:
a) better temporary location - ensuring it is unique
b) subsequent download goes to the same _local_copy_path
c) upload/download icon or filename could look differently if local copy was modified... like modified in git

**Comment by gbrueckl** [comment]
you can just clone this repository, open it in VS Code and start debugging it (Press F5)

regarding your thoughts:
a) yes, we could create a temporary location for DBFS within the localSyncFolder, maybe even downloading/persisting it there in a similar way we do for notebooks
b) would also be solved with a)
c) again, would also be solved with a)

**Comment by JacekPliszka** [comment]
OK, looks like you have already nice pattern for that and effort is such that you will do it faster for the next release than newbie like me.

I've found 2 issues:

a) when workspace contains dots like j.p@company.com then it appears twice - once as j.p@company.com and once as j.p@company

b) in the settings.json I set
```
    "databricks.connection.default.exportFormats": 
        "Python": ".py"
    },
```
But it downloads in .ipynb regardless

**Comment by gbrueckl** [comment]
could you file a separate issue for a)

for b) , if a local .ipynb file exists, it will not be downloaded again as .py but as .ipynb - is this the case for you?

**Comment by JacekPliszka** [comment]
moved a) to #22  and got simple fix.

**Comment by JacekPliszka** [comment]
.ipynb does not exist, in settings I've replaced all ipynb by py and still it downloads as ipynb

Shall I open separate issue for that?

**Comment by JacekPliszka** [comment]
OK, I've tried to replicate Workspace upload with DBFS but I am failing with

```
ERROR writing file: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
```

in downloadDBFSFile

```
let writeStream = fs.createWriteStream(localPath, { highWaterMark: batchSize, encoding: 'base64' });
```

And then I am getting the error on write...

I've never before used TypeScript so I am afraid I might be quite inefficient...

**Comment by JacekPliszka** [comment]
Strange - now it works...

**Comment by JacekPliszka** [comment]
The above commit is ugly but works for me. It is much more primitive than what is for Workspace.

Also it changes behaviour for DBFS - when double-clicked - downloads to sync dir and opens in editor.

**Comment by JacekPliszka** [comment]
Regarding b) - even if file does not exist - it is still saved as ipynb despite configuration settings.

**Comment by gbrueckl** [comment]
works fine for me - but could be that if you delete the file when your VS Code session is still running and it did previously exist as .ipynb that this was cached and hence it was downloaded as .ipynb again
if you start a clean VS Code instance and nothing is in your local sync folder it downloads in the defined export format - no?

**Comment by JacekPliszka** [comment]
Pushed version that addressed all your points but separate Save As button.

**Comment by JacekPliszka** [comment]
Thank you.

moved .py issue to #27 - I need more time to investigate it. I am always getting .ipynb

I believe for this issue we have everything covered.

Shall we close it?

**Comment by gbrueckl** [comment]
new DBFS features were introduced with the latest release
