### ISSUE TITLE

Feature Request: JupyterLab Extension for Databricks Power Tools

### ISSUE THREAD

**Issue by jslorrma** [paiqo/Databricks-VSCode#200]
Hello,

First off, thank you for creating such an amazing tool. The Databricks Power Tools VS Code extension is incredibly useful for my team and we use it a lot during development and interactive / iterative testing. 

However, many in our team prefer working in JupyterLab and in addition our company provides JupyterHub environments for a variety of purposes including development, courses and workshops.

I wanted to check if a similar extension for JupyterLab is already available, has been considered, or is currently in the pipeline. If not, is this something you might consider adding?

**Feature Request:**
We would love to see a JupyterLab extension for Databricks Power Tools. This would enable users to connect to remote Databricks workspaces, access DBFS, and use remote notebook kernels directly from JupyterLab, just like in VS Code.

**Benefits:**
- Broaden the tool's reach to users who prefer JupyterLab.
- Offer a consistent and integrated experience across different IDEs.

Thank you for considering this request.

**Comment by gbrueckl** [comment]
Hi @jslorrma,

thanks for you kind words - we really appreciate it!

Databricks Power Tools are currently built as VSCode extension and we do not plan to expand to any other IDEs/environments.
There are a couple of reason but foremost I/we do not use JupyerHub and have no experience there. As Databricks Power Tools was originally created for my personal needs and I decided to open-source it, I/we have no motivation to build something similar for other IDEs that we dont use.

Two more things to mention here:
1. Databricks Power Tools is built 100% on top of the Databricks REST APIs, so technically, a similar extension could be build also for e.g. JupyterHub - but again, we will not do it
2. you can reach out to the Databricks team and see if they have plans to support JupyterHub with their extension

regards,
-gerhard

**Comment by jslorrma** [comment]
Ok, thanks for your reply. 

Because your extension has this nice wrapping and abstraction of the Databricks API and due to the fact that jupyter lab extensions are also written in JavaScript / TypeScript , I was just wondering if it would be possible with not too much effort to build this jupyter adaptor on top of your Databricks API layer. And I have just too little to no experience with JavaScript or TypeScript to estimate it.

Anyhow, thanks again.

**Comment by gbrueckl** [comment]
while most of the [DatabricksApiService.js](https://github.com/paiqo/Databricks-VSCode/blob/master/src/databricksApi/databricksApiService.ts) could probably be reused, I think the majority of work would be in adopting the UI to jupyther lab. As you can see in the sourcecode, the DatabricksApiService is only about 2% of the actual code where the rest is related to the UI and actions in VSCode
