### ISSUE TITLE
Unable to attach cluster in Databricks VSCode extension

### ISSUE THREAD

**Issue by KonstantinosTsoumas** [paiqo/Databricks-VSCode#203]
Hello,

I'm encountering an issue with the Databricks extension in VSCode where I am unable to attach any cluster to my workspace. I've tried using multiple different Databricks instances, but no cluster is visible. I also tried cross-checking my settings with colleagues, but I found having no differences among us. One thing to note, we are not using Unity Catalog.
Please also check the pictures attached which might be helpful!

### Here’s a brief summary of the problem:

**Steps to Reproduce:**

- Open VSCode with the Databricks extension installed and configured.
- Log in to Databricks workspace successfully using OAuth.
- Navigate to the Clusters panel and try to attach any cluster.

**Expected Behavior:**

- All the clusters should be visible (just like under the 'Compute' section in the Databricks UI) and available to be selected. 

**Actual Behavior:**

- I can't see any available clusters at all. 

**Environment Details:**

Databricks Extension Version: v1.4.0
VSCode Version: 1.95.3
OS: Windows 11

**What I’ve Tried:**

- Fresh uninstall & install VSCode 
- Fresh uninstall & install Databricks extension
- Tried multiple versions of the Databricks extension
- Tried multiple different instances
- Tried multiple different authorization methods.
- Cross-checking settings with other people.

Any guidance or potential fixes would be greatly appreciated!

Thank you in advance!

### Appendix images:
![image](https://github.com/user-attachments/assets/609fb040-523f-4e9d-93a0-5187ccb00617)

![image](https://github.com/user-attachments/assets/b3c6f964-8869-4899-980f-32dfbbff6143)

**Comment by gbrueckl** [comment]
I think you opened your issue in the wrong VSCode extension for Databricks :D 
according to your screenshots you have troubles with the [original extension from Databricks](https://marketplace.visualstudio.com/items?itemName=databricks.databricks) itself but not with Databricks Power Tolls (this extension)

please open a support-ticket here
https://github.com/databricks/databricks-vscode/issues

**Comment by KonstantinosTsoumas** [comment]
Thanks for the reference & sorry for the wrong post!
