### ISSUE TITLE
not able to connect to databricks workspace

### ISSUE THREAD

**Issue by TarekSalha** [paiqo/Databricks-VSCode#24]
Hi,
I am having trouble in setting up the initial connection. I am providing
"databricks.connection.default.apiRootUrl": "https://westeurope.azuredatabricks.net",
    "databricks.connection.default.displayName": "DeltaTableDemo",
    "databricks.connection.default.personalAccessToken": "dapiexxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "databricks.connection.default.localSyncFolder": "C:\\Users\\blabla\\Documents\\Projekte\\Databrickstest",
    "databricks.connection.default.useCodeCells": true,
    "databricks.connection.default.organizationId": "435xxxxxxxxxxxxxxx"

I set it via VS Code UI.
however, it is not performing the connection to my cluster when hitting refresh in the connections pane.
![image](https://user-images.githubusercontent.com/25264670/86276757-c376ea80-bbd5-11ea-8518-4845099bb87f.png)

What am I doing wrong?
I am also wondering why the cluster ID is not used for the connection as explained in https://docs.databricks.com/dev-tools/databricks-connect.html#set-up-client. Is this expected?
best regards,
Tarek

**Comment by briancuster** [comment]
I'm having the same problems as Tarek above.  I type in all the required information and I don't see my workspace or any other information in the side bar after refreshing.  Any idea what could be going wrong?

**Comment by gbrueckl** [comment]
your configuration looks correct (I assume you copied it from the settings JSON file directly)
it should also show you a connection "DeltaTableDemo" and connect to it automatically. 
can you check the output "paiqo.databricks-vscode" ?
![image](https://user-images.githubusercontent.com/11884402/87308447-8850b180-c51b-11ea-8d70-fba30cf51fcf.png)

for your second question: this is/was work-in-progress and does not work yet. In fact it will even be removed with the next version and may be added again later. But for now, there is no direct connection/dependency between this extension and Databricks-Connect but you can of course execute notebooks downloaded by this extension against a Databricks cluster using Databricks-Connect

**Comment by TarekSalha** [comment]
Hi Gerhard,
thanks for your feedback. I wasn't aware of the extensive logging output before.
However, the connection showed up (miraculously) immediately after startup of vscode. I cannot describe why. Maybe due to fresh startup?
Also, scripts and clusters now work fine for me.
@briancuster: Maybe, this is going to work for you as well? Certainly, also the logs are extremely useful. As a test, I used an outdated token and logs gave me the direct error message directly to output.

**Comment by gbrueckl** [comment]
@TarekSalha well, most of the logging about reading the connections from the config settings was added with yesterdays release ;)
however, the logs about the API calls have been there for quite some time

anyway, happy that it is working for you now
waiting for positive feedback from @briancuster so we can hopefully close this issue then

**Comment by gbrueckl** [comment]
any update form your side @briancuster 
did you try with the latest version?

**Comment by hukun01** [comment]
One little hiccup I had was that after entering all the mandatory info, and hit refresh button on the connection bar, a message showed up at the bottom right saying "refreshing connection etc", but nothing happened. I realized that it was because the PAT I just generated wasn't finalized in Azure until I hit 'Ok' button there.
Also, after the above little fix on my own side, I still need to restart the VS code to be able to see the connection. The log output helped me determine that the connection was indeed loaded, it's just invisible until a restart of VS code.
Thanks for making this extension!

**Comment by oynek** [comment]
I had the exact same problem and can confirm that it works for me after doing a restart of VS Code, like @TarekSalha.

**Comment by champion-054** [comment]
@hukun01 can you tell me more about how to do the Azure part?
Also I am getting an error as soon as I refresh which says 
"Client network socket disconnected before secure tls connection was established"
Any idea regarding this??
My workspace ,clusters etc show empty.

**Comment by briancuster** [comment]
> I'm having the same problems as Tarek above. I type in all the required information and I don't see my workspace or any other information in the side bar after refreshing. Any idea what could be going wrong?

I figured this out by first creating a workspace in vs code.  Once the workspace was created I was able to create a connection to my Databricks cluster and workspace.

**Comment by gbrueckl** [comment]
this should be fixed by now
