### ISSUE TITLE
Notebooks always downloaded as .ipynb ignoring .py setting

### ISSUE THREAD

**Issue by JacekPliszka** [paiqo/Databricks-VSCode#27]
This was found when working on #20 

Need more time to investigate

**Comment by gbrueckl** [comment]
can you check whether you have different settings for the ExportFormats in your workspace and in your global user settings?
if you debug the code, what values do you see for `ThisExtension.ActiveConnection.exportFormats` (simply assign it to a variable and check it)

**Comment by fred2008** [comment]
The same problem. Even if I delete the workspace folder with .vscode config. Any update to work around the problem?

**Comment by JacekPliszka** [comment]
OK, I am back to using databricks and switched to version 0.7.1 and now it looks like it works after this fix:

In extension settings I have Databricks>Connection>Default:Export Formats set Python to .py for User but I found there is Workspace tab that has ipynb - after changing this to .py everything works fine.

@fred2008  - could you check this ? then we should close the issue

**Comment by gbrueckl** [comment]
closing this as fixed
