### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by M9T** [paiqo/Databricks-VSCode#3]
- Add favorites
- Pre-filtering option to hide clusters, jobs and Co, to which you only have view rights anyway
- View and execute notebooks without downloading them separately (direct vscode integration)
- Enable to display more cluster details
- filter feature (not search)
- add Mlflow experiments

**Comment by gbrueckl** [comment]
I added separate issues for the first two topics
regarding the other topics:
- View and execute notebooks without downloading them separately (direct vscode integration)
  this does not work technically. The only way I could think of is to start a job that executes the notebook - is this what you had in mind?
- Enable to display more cluster details
  can you elaborate on that? if you double-click a cluster or user "Show definition" you get all necessary information about the cluster that the REST API exposes. What else would you expect?
- filter feature (not search)
   when using search, there is a small button next to the input field that allows you to either highlight the search-term or actually filter on it - thats a standard feature in VS Code
- add Mlflow experiments
  interesting idea. However, I think this should be done in a separate extension so it would work with all tools that support MLflow and not only with databricks

**Comment by gbrueckl** [comment]
closing this one as separate issues were created for some of the ideas
for the others no further feedback was provided
