### ISSUE TITLE
How can i limit the VS code workspace to sync only with my workspace on databricks 

### ISSUE THREAD

**Issue by Sumad** [paiqo/Databricks-VSCode#30]
Hi,
I set up the extension, it is taking long to download everything from databricks workspace and show on the workspace view in the VS code explorer. 
I am unable to find a setting for the extension that could allow limiting the sync to specific folder/s instead of the whole databricks workspace.
Can you advise on a possible solution?

**Comment by gbrueckl** [comment]
when you open the extension the first time, the Workspace-browser shows the structure as it is online in the Databricks workspace. At this stage nothing is downloaded yet. You can then decide what you want to download by either downloading notebooks one by one or a complete folder and its subfolders.
in your case you can simply navigate to /users/yourUser@yourdomain.com and click the "Download" button next to it what will cause a download of the whole folder including subfolders

however, I also added a new [enhancement request](https://github.com/paiqo/Databricks-VSCode/issues/31) to make this configurable - please follow up there with any suggestions
