### ISSUE TITLE
Ability to remove the Workspace folder from Local Sync folder

### ISSUE THREAD

**Issue by jeffhebrank** [paiqo/Databricks-VSCode#33]
I noticed that a "Workspace" folder is created in the local sync folder when I download local copies of notebook from my databricks workspace. It would be nice to have an option that does not create the "Workspace" folder.

My specific scenario:

My git repo looks like this:
myProjectName/myNotebooks/HelloWorld.py

And my databricks workspace looks like this:
Workspace/Users/myUsername/mypersonalstuff.py
Workspace/myNotebooks/HelloWorld.py

(The Users folder doesn't get checked in to our repo)

When I specify "myProjectName" as my local sync folder it creates:
myProjectName/Workspace/myNotebooks/HellowWorld.py

So its not mapping properly to my existing checked in notebooks. To solve this I think two things would be nice
1. Ability to ignore folders in the Databricks workspace (like Users folder)
2. Ability to map Databricks workspace folders to specific locations in my local repo.

**Comment by gbrueckl** [comment]
Hi @jeffhebrank 
currently, the special folder "Workspace" is created to be compatible with my PowerShell module [DatabricksPS](https://www.powershellgallery.com/packages/DatabricksPS)
It would allow you to manage and easily deploy all artifacts of your Databricks workspace (notebooks, jobs, clusters, ...)
the long-time goal is to also integrate jobs and cluster in this VSCode extension so you can use VSCode to manage everything and then use DatabricksPS to deploy it in a CI/CD pipeline

removing the artificial folder "Workspace" would mean that you need 5 separate config settings for the different artifacts (notebooks/workspace, jobs, clusters, dbfs, ...)

However, I understand that it can make a lot of sense to exclude specific folders automatically so I will add a feature request for that!
Until that, you can simply manually exclude it by not downloading the whole workspace but only the folders you really need

**Comment by gbrueckl** [comment]
moved to https://github.com/paiqo/Databricks-VSCode/issues/34

**Comment by gbrueckl** [comment]
@jeffhebrank there is now a new configuration setting called `localSyncSubfolders` which you can use 
if you set the value for `localSyncSubfolders.Workspace` to a blank value, the notebooks will be downloaded to the root of `localSyncFolder`

```
"localSyncSubfolders": {
	"Workspace": "",
	"Clusters": "Clusters2",
	"DBFS": "DBFS3",
	"Jobs": "Jobs4"
}
```
