### ISSUE TITLE
New feature: Use Databricks CLI config to get host and token

### ISSUE THREAD

**Issue by bernhard-42** [paiqo/Databricks-VSCode#35]
I usually try to avoid spreading my personal access tokens around on my laptop and prefer to have them in one place (security and convenience when I e.g change them).
[Databricks CLI](https://docs.databricks.com/dev-tools/cli/index.html) has a config file `~/.databrickscfg` that is structured like an ini file:

```test
[profile1]
host = https://...
token = dapi...
```

How about allowing an alternative config for the combination `apiRootUrl` + `personalAccessToken` called `cliProfile`.
Instead of reading url and token from VSCode config, the extension would read the `cliProfile` from the VSCode config and get url and token then from `~/.databrickscfg`.

Now I even could have the config in my workspace in `<workspaceDir>/.vscode/settings.json` 

```json
{
    "cliProfile": "profile1",
    "cloudProvider": "Azure",
    "displayName": "My Dev workspace",
    "localSyncFolder": "c:\\Databricks\\dev",
}
```

and if I want to commit my `.vscode` folder together with the project, no token is committed.

**Comment by gbrueckl** [comment]
we have been thinking a lot lately whats the best way to store the sensitive values (Personal Access Token / PAT)
Initially it was stored as part of the VS Code workspace configuration - however, people complained that they now have to commit the PAT to GIT if they want to commit their VS Code workspace
So we moved it to the global user settings and only store a reference in the workspace config - thats also the current state

In general, we want to keep the config within VS Code so you do not need any external config file to set it up as this introduces more and more complexity

mixing it with other tool's configs is also not a good idea from my point of view as you may break the other tools while you modify the configuration for your purposes. (this applies to Databricks CLI and also Databricks-Connect config files)

the current idea is to store the sensitive settings in the PCs security store using [keytar](https://github.com/atom/node-keytar) 
in the workspace config we would then simply store the name of the secret and retrieve it at runtime. If you want to change it, you would still set it in VS Code and the extension would pick it up, generate a unique ID as secret name for keytar and then keytar stores the PAT and VS Code the unique ID as reference

what do you think?

**Comment by bernhard-42** [comment]
I agree that storing PATs outside of workspace configuration is a must.

And I also agree that mixing could break things. However, this is not what I meant: Keep your own config in VS Code as it is now. However, for people using Databricks CLI (e.g. for CI/CD workflows), add an additional feature to retrieve the Databricks connection config (host + token) for a given profile from `~/databrickscfg`. You can't break anything since this will only be read access. And a user providing `cliProfile` in your config will well be aware that uninstalling Databricks CLI will break your extension. 

Rationale:

For the Databricks connection config (host + token) I would love to see something that fulfills:
1) Keep all PATs in one central place
2) Just store each PAT once, so that whenever the APT gets changed (e.g. due due to expiration), there is one location to update
3) Allow different tools to access the same Databricks connection config (host + token)

Unfortunately, Databricks Connect and Databricks CLI already have their own config file, violating 3).

However, building more and more tools using their own storage method for the Databricks connection config (host+token), just makes token management on your local machine more difficult.

So I have decided to use `~/databrickscfg` as the "source of truth" for my tools (https://github.com/databrickslabs/Jupyterlab-Integration and https://github.com/bernhard-42/db-12-vscode/tree/makefile_on_save). So whenever I change a PAT and update it in `~/databrickscfg` all tools will continue to work (well, except Databricks Connect, ...). 

Of course, each tool will store tool specific config in its own domain, not touching `~/databrickscfg`. `db-12-vscode` stores for example

```json
{
    "databricks-run.profile": "aws-ffm",
    "databricks-run.cluster": "0808-143712-abcde1",
    "databricks-run.lib-folder": "test_pipeline",
    "databricks-run.remote-folder": "dbfs:/home/bernhard"
}
```

in `<workspace folder>/.vscode/settings.json`

Now that I have installed your VSCode extension as a complementary tool in VSCode to `db-12-vscode`, I just would have loved to not even open my `.databrickscfg` to copy the token over, but just provide the profile name, which is easy to remember.

**Comment by gbrueckl** [comment]
I am totally with you that a single place of configuration for all tools would be the final goal to have. 
But I think this will only be possible if we get all vendors/creators of tools to commit to a standard. And this can be a lot of work!
If Databricks (as the creator of the most common tools - CLI and DB-connect) some time in the future use a common configuration file, I am happy to change the code for this extension to work with it.

For us it is important that we can keep using VS Code configurations and store sensitive values securely on the local machine and outside of the workspace which is currently the case

**Comment by bernhard-42** [comment]
ok, fair enough
