### ISSUE TITLE
"'dbutils' is not defined" when running locally

### ISSUE THREAD

**Issue by hukun01** [paiqo/Databricks-VSCode#38]
Hi,

I just started using the extension today, thanks for making this extension!

When I ran the python notebook synced from my workspace, some lines stop working, like below
```python3
for file_info in dbutils.fs.ls(folder):
    print(file_info)
# NameError: name 'dbutils' is not defined
```
Can I do something extra (maybe configure somewhere) to completely simulate the databricks environment in my local environment? Or, can I do something else to access files in DBFS/mnt path without downloading them?

Thanks

**Comment by gbrueckl** [comment]
This is not related to this extension but only to [databricks-connect](https://docs.databricks.com/dev-tools/databricks-connect.html)
please check this link about [dbutils and databricks-connect](https://docs.databricks.com/dev-tools/databricks-connect.html#access-dbutils)
