### ISSUE TITLE
Client network socket disconnected before secure tls connection was established 

### ISSUE THREAD

**Issue by champion-054** [paiqo/Databricks-VSCode#40]
This is the error I get after restarting VSCode.
Client network socket disconnected before secure tls connection was established 
Also I am getting the clusters is not iterable.
Essentially all my left hand side controls except for Environment is showing empty.

**Comment by champion-054** [comment]
Ok somehow this issue miraculously vanished when I uninstalled and re-installed the extension.
Now I am able to get all the folders in the Clusters, Jobs etc. But when I try to access one of the directories in the Workspace, I get this error:
Cannot read property "extension" of Undefined

**Comment by gbrueckl** [comment]
please make sure you have the latest version from the marketplace installed - the issue you are describing has been solved in a previous fix
if this does not help, please open a dedicated ticket for the new issue

**Comment by gbrueckl** [comment]
closed due to missing feedback and/or lack of detailed information
