### ISSUE TITLE
Execute Notebook on Databricks clusters - is there a way

### ISSUE THREAD

**Issue by ss68974** [paiqo/Databricks-VSCode#41]
is there any way to execute the notebooks on databricks clusters from vscode like %sh %sql %python supported in databricks ?
Using databricks-connect we can execute scripts, but I would like to know if there is any option to run %sh %sql like features from vscode using the databricks notebooks downloaded into the vscode workspace..

**Comment by gbrueckl** [comment]
in general I think this should be possible but it is more related to Python/Jupyter extension to understand the %sql and %sh magics 
If jupyter is configured to work properly with those magics, it *should* also work in VS Code

**Comment by ss68974** [comment]
Would be great if you can explain how it can be achieved.

**Comment by gbrueckl** [comment]
thats not actually related to this VSCode extension but to the Python/Jupyter extension - please open an issue there
