### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by YJacobs90** [paiqo/Databricks-VSCode#42]
Hello,

I have succesfully established a connection to Databricks, but my workspaces aren't loading. When refreshing the workspaces, I am getting the error "Cannot read property 'data' of undefined". On my personal MacBook Pro the connection is working, and I have copied the settings.json file from there. What could be the cause of this?

Thanks for your response.

Regards,
Yannick

**Comment by gbrueckl** [comment]
Hi Yannick,

I assume there is an issue with the API calls. 
Can you check the output-tab and filter for "paiqo.databricks-vscode"
this should reveal more information

regards,
-gerhard

**Comment by YJacobs90** [comment]
Hi Gerhard,

Thanks for the quick reply. The output is as follows:
GET 2.0/workspace/list
Params:{"params":{"path":"/"}}
ERROR: Request failed with status code 407
ERROR: undefined
ERROR: ""

Regards,
Yannick

**Comment by gbrueckl** [comment]
looks like an error with the actual API call.
Are you sure the API token and the URL are correct?
if you copied the settings.json from your Mac Book you also need to make sure that the workspace-settings link to the right workspaceGuid in user-settings.
I know, this setup is a bit complicated but it will change with the next release

**Comment by YJacobs90** [comment]
I triple checked the proxy settings and changed some stuff around and it is working now.
