### ISSUE TITLE
Getting URI with a schema is expected

### ISSUE THREAD

**Issue by jviegas6** [paiqo/Databricks-VSCode#46]
Hi,

Trying to setup my databricks-vscode and can't setup local sync folder.
Tried different setups (absolute paths, relative paths) and keeps telling me "URI with a scheme is expected"

Current setup macos 10.15.7

Any solution. Thanks?

**Comment by gofr1** [comment]
Same on Ubuntu 20.04.1 LTS.

**Comment by jviegas6** [comment]
Got it sorted. Although in settings UI evaluates to an error the statement "//Users/[myMacUser]/folder" is actually valid.
Went to settings json configured it.
