### ISSUE TITLE
Able to connect to but receive error when loading workspace <Cannot read property 'data' of undefined>

### ISSUE THREAD

**Issue by bdeshon** [paiqo/Databricks-VSCode#48]
I was able to get a connection to appear in the 'connection' box but when the workspace and other boxes try to load I receive this error 'Cannot read property 'data' of undefined'.

My setup is currently this:
I have to connect to Azure via a VM so I have vscode remote ssh connecting to the VM(windows) and using that VM to run the connection to Azure.

I do have the extension installed on both the local and remote machines. 

Below are my settings on the remote side:

{
    "remote.SSH.connectTimeout": 30,
    "python.analysis.completeFunctionParens": true,
    "python.autoComplete.addBrackets": true,
    "databricks.connection.default.localSyncFolder": "C:\\Users\\userID\\OneDrive\\gitRepositories\\dataBricksTraining",
    "databricks.connection.default.apiRootUrl": "https://adb-11111111111111111.1.azuredatabricks.net",
    "databricks.connection.default.displayName": "Azure Data Bricks",
    "databricks.connection.default.personalAccessToken": "dapixxxxxxxxxxxxxxxxxxxxxxxx"
}

Any help would be appreciated.

**Comment by gbrueckl** [comment]
I do not have any experience with VSCode remote SSH connections so I do not know if I can really help you here

does the extension work locally on your machine? on the VM?

**Comment by bdeshon** [comment]
It returns the same error on my VM.

this is what is returned in the log:

`Logger initialized!
Initializing ConnectionManager ...
Loading connections array from Workspace (databricks.connections)...
0 connection(s) loaded from Workspace!
Loading default connection from Workspace/UserSettings (databricks.connection.default.*) ...
Configuration Azure Data Bricks: Setting Configuration property "cloudProvider" to "Azure" based on the property "apiRootUrl"
Default connection loaded from Workspace/UserSettings!
Loading connections array from UserSetting (databricks.userWorkspaceConfigurations)...
0 connection(s) loaded from UserSetting!
Updating user setting 'databricks.userWorkspaceConfigurations' ...
Removing workspace settings 'databricks.*' as they have been persisted in the user settings!
Initializing Databricks API Service ...
Initializing Databricks API Service ...
Initializing Databricks API Service ...
GET 2.0/workspace/list
Params:{"params":{"path":"/"}}
GET 2.0/clusters/list
Params:null
GET 2.0/jobs/list
Params:null
GET 2.0/dbfs/list
Params:{"params":{"path":"/"}}
GET 2.0/secrets/scopes/list
Params:null
ERROR: Request failed with status code 502
ERROR: undefined
ERROR: "<HEAD><TITLE>Connection reset by peer</TITLE></HEAD>\n<BODY BGCOLOR=\"white\" FGCOLOR=\"black\"><H1>Connection reset by peer</H1><HR>\n<FONT FACE=\"Helvetica,Arial\"><B>\nDescription: Connection reset by peer</B></FONT>\n<HR>\n<!-- default \"Connection reset by peer\" response (502) -->\n</BODY>\n                                                                                                                                                                                                                                                                                                                                                                                              \u0000"`

**Comment by bdeshon** [comment]
Here is what i get when i hit the API with curl.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/36005411/106033411-59ed8a80-6097-11eb-82f3-ca942dd27e5f.png">

**Comment by gbrueckl** [comment]
You would also need to add an API endpoint, easiest would be a GET for e. G clusters

curl ... https://<databricks-instance>/api/2.0/clusters/list

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bdeshon** [comment]
ok... i hit the api/2.0/cluster/list and still was able to get a good connection.  here is the output.  it does list out all the clusters at the bottom.  i didnt capture all of it since it was a lot to snap.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/36005411/106332276-125c2f80-624c-11eb-9350-13e0c566b122.png">

**Comment by gbrueckl** [comment]
ok, this looks indeed good 

again, this does work from the VM and also from your local machine?

**Comment by bdeshon** [comment]
yes it works on both but... the VM looks like it had some trouble initially connecting.  it still listed out all the clusters at the end.  here is the output.  sorry it is so long.

smrcy\xxxxx@xxxxxxxxxxxxx C:\Users\xxxx>curl -v -s -H "Authorization: Bearer dapixxxxxxxxxxxxx" https://adb-xxxxxxxxxxxxx.1.azuredatabricks.net/api/2.0/clusters/list
*   Trying xxxxxxxxxxxxx...
* TCP_NODELAY set
* Connected to xxxxxxxxxxxxx (xxxxxxxxxxxxx) port 80 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to adb-xxxxxxxxxxxxx.1.azuredatabricks.net:443
> CONNECT adb-xxxxxxxxxxxxx.1.azuredatabricks.net:443 HTTP/1.1
> Host: adb-xxxxxxxxxxxxx.1.azuredatabricks.net:443
> User-Agent: curl/7.55.1
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Date: Fri, 29 Jan 2021 22:28:30 GMT
< Proxy-Connection: Keep-Alive
< Via: 1.1 wdc-VM
<
* Proxy replied OK to CONNECT request
* CONNECT phase completed!
* schannel: SSL/TLS connection with adb-xxxxxxxxxxxxx.1.azuredatabricks.net port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 206 bytes...
* schannel: sent initial handshake data: sent 206 bytes
* schannel: SSL/TLS connection with adb-xxxxxxxxxxxxx.1.azuredatabricks.net port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* CONNECT phase completed!
* CONNECT phase completed!
* schannel: SSL/TLS connection with adb-xxxxxxxxxxxxx.1.azuredatabricks.net port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 4028
* schannel: encrypted data buffer: offset 4028 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with adb-xxxxxxxxxxxxxxxx.1.azuredatabricks.net port 443 (step 2/3)
* schannel: encrypted data got 1024
* schannel: encrypted data buffer: offset 5052 length 5052
* schannel: encrypted data length: 250
* schannel: encrypted data buffer: offset 250 length 5052
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with adb-xxxxxxxxxxxxx.1.azuredatabricks.net port 443 (step 2/3)
* schannel: encrypted data got 64
* schannel: encrypted data buffer: offset 314 length 5052
* schannel: sending next handshake data: sending 93 bytes...
* schannel: SSL/TLS connection with adb-xxxxxxxxxxxx1.azuredatabricks.net port 443 (step 2/3)
* schannel: encrypted data got 258
* schannel: encrypted data buffer: offset 258 length 5052
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with adb-xxxxxxxxxxx.1.azuredatabricks.net port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /api/2.0/clusters/list HTTP/1.1
> Host: adb-xxxxxxxxxxxx.1.azuredatabricks.net
> User-Agent: curl/7.55.1
> Accept: */*
> Authorization: Bearer dapi.....
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 6134
* schannel: encrypted data buffer: offset 6134 length 103424
* schannel: decrypted data length: 6105
* schannel: decrypted data added: 6105
* schannel: decrypted data cached: offset 6105 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 6105 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 6105
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 200 OK
< server: databricks
< date: Fri, 29 Jan 2021 22:28:30 GMT
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-content-type-options: nosniff
< content-type: application/json
< x-databricks-org-id: xxxxxxxxxxxxx
< vary: Accept-Encoding
< transfer-encoding: chunked
<
{"clusters":[{"cluster_id":"0512-201654-wary962","driver":{"

**Comment by gbrueckl** [comment]
thats probably related to you SSH setup - but as I said, I have no experience there

if it is working fine locally on both machines I am afraid there is not much more I can really help you with. 
But the logs above look fine to me - no?

**Comment by gbrueckl** [comment]
closing this as it is very likely not related to the extension itself
