### ISSUE TITLE
Cannot set property exportFormats of #<DatabricksConnectionTreeItem> which has only a getter

### ISSUE THREAD

**Issue by agarwalabhilash1984** [paiqo/Databricks-VSCode#49]
It was working perfectly fine and all of a sudden I am hitting this error after VSCode update - now I cannot connect to my Azure DataBricks workspace and basically do nothing using Databricks extension

**Comment by agarwalabhilash1984** [comment]
here is the output log
Loading Connection from 'databricks.default.*' ...
Configuration ADB-INP-Common-PB: Property "exportFormats" was not provided - using the default value "[object Object]"!
Configuration ADB-INP-Common-PB: Setting Configuration property "cloudProvider" to "Azure" based on the property "apiRootUrl"
Configuration ADB-INP-Common-PB: Property "useCodeCells" was not provided - using the default value "true"!
Setting 'databricks.lastActiveConnection' to 'ADB-INP-Common-Prod' ...
Loading Connections from 'databricks.connections' ...
Loading Connection from 'databricks.default.*' ...
Configuration ADB-INP-Common-PB: Property "exportFormats" was not provided - using the default value "[object Object]"!
Configuration ADB-INP-Common-PB: Setting Configuration property "cloudProvider" to "Azure" based on the property "apiRootUrl"
Configuration ADB-INP-Common-PB: Property "useCodeCells" was not provided - using the default value "true"!
Setting 'databricks.lastActiveConnection' to 'ADB-INP-Common-Prod' ...

**Comment by gbrueckl** [comment]
HI @agarwalabhilash1984,

sorry for the inconvenience but thanks for reporting this.
I just had a look and fixed the issue in version v0.7.1 which is also already published to the VSCode marketplace
please give it another try

-gerhard

**Comment by agarwalabhilash1984** [comment]
It works perfect - thanks a lot for quick response - Gerhard
