### ISSUE TITLE
Locla Sync Folder path without "workspace"-folder

### ISSUE THREAD

**Issue by invalidarg** [paiqo/Databricks-VSCode#50]
Hi,

I have an existing git-repository with db-notebooks in a folder
/notebooks/dev/code.py

From Databricks-VSCode the code is downloaded into
<folder i select in settings>/Workspace/dev/code.py

So if I select "/notebooks/" in extension settings the code is in 
/notebooks/Workspace/dev/code.py
and does not match with my repo

Is it possible to download into the folder I select and not a subfolder called "Workspace"?

**Comment by gbrueckl** [comment]
currently that is not possible but we will consider it for a future release to make these paths configurable

**Comment by gbrueckl** [comment]
I just published a new version where you can control the name of the subfolders using a new configuration setting:
```
"localSyncSubfolders": {
	"Workspace": "notebooks",
	"Clusters": "myClusters",
	"DBFS": "myDBFS",
	"Jobs": "myJobs"
}
```

please give it a try

**Comment by gbrueckl** [comment]
closing this as it was fixed
