### ISSUE TITLE
I'm using dbconnect in a container and can't configure out where my workspace downloads are going

### ISSUE THREAD

**Issue by Freewilly3d** [paiqo/Databricks-VSCode#51]
Is this supported?  I tried using  c:\work and /workspaces; I get a message that says it downloaded the notebook.

**Comment by gbrueckl** [comment]
the should be under `C:\work\workspaces`
you may try to use workspaces (without a slash) or try a backslash if you want a nested folder

also it would help if you post your config here so I can investigate

**Comment by Freewilly3d** [comment]
Here is my config
{
    "update.enableWindowsBackgroundUpdates": false,
    "terminal.integrated.rendererType": "dom",
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "databricks.connection.default.apiRootUrl": "https://adb-8642464234266872.12.azuredatabricks.net/",
    "databricks.connection.default.displayName": "Databricks-eem",
    "databricks.lastActiveConnection": "Databricks-eem",
    "databricks.connection.default.personalAccessTokenSecure": {
        "keyTarSettingName": "Databricks-eem-API-Token"
    },
    "databricks.connection.default.localSyncFolder": "c:\\work\\workspaces"

**Comment by gbrueckl** [comment]
in this case your downloaded notebooks would be placed in `C:\work\workspaces\Workspace`

what happens if you double-click on the item in the Databricks Workspaces tab once you downloaded it? 
It should open in the editor and there you would also see the full path

**Comment by Freewilly3d** [comment]
I can click download and I get a message that the download completed.  When I double click on the script nothing happens.  I assume this issue is being caused because I'm using the docker container for by dbconnect?

**Comment by gbrueckl** [comment]
closing as it is pretty much outdated
It may be worth a try using the new Notebook Execution feature that was released with v1.0
