### ISSUE TITLE
How do I run my notebook on my cluster?

### ISSUE THREAD

**Issue by RengarLee** [paiqo/Databricks-VSCode#52]
I have successfully connected to my Databricks workspace, and I see my notebooks and clusters listed in the "WORKSPACE" and "CLUSTERS" sections of the sidebar, respectively.

However, I'm having trouble opening the notebook I want to open and run it on my Databricks cluster. Does anyone have any advice on how to do this?

If I double-click on my notebook, it downloads. If I double-click it again, it says " Opening local cached file. To open most recent file from Databricks, please manually download it first!"; 
![image](https://user-images.githubusercontent.com/23287334/118580180-062bbc00-b7c2-11eb-9713-13814526f6b6.png)

If I open this file in the folder, It can work.
![image](https://user-images.githubusercontent.com/23287334/118580420-6de20700-b7c2-11eb-8a99-d7ae3e296e19.png)

This is my config
{
    "workbench.sideBar.location": "right",
    "editor.renderWhitespace": "all",
    "editor.renderControlCharacters": true,
    "workbench.iconTheme": "vscode-icons",
    "git.confirmSync": false,
    "workbench.activityBar.visible": true,
    "[csharp]": {},
    "git.ignoreWindowsGit27Warning": true,
    "debug.onTaskErrors": "debugAnyway",
    "databricks.connection.default.apiRootUrl": "https://adb-2296486909405229.9.azuredatabricks.net/",
    "databricks.connection.default.displayName": "Dev",
    "databricks.connection.default.localSyncFolder": "G:\\RengarLeeDatabrickDoc",
    "databricks.lastActiveConnection": "Dev",
    "databricks.connection.default.personalAccessTokenSecure": {
        "keyTarSettingName": "Dev-API-Token"
    },
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
    "jupyter.alwaysTrustNotebooks": true,
}

Does anyone have any advice on how to do this?

**Comment by gbrueckl** [comment]
to run the code against a Databricks cluster you need to use [dbconnect](https://docs.databricks.com/dev-tools/databricks-connect.html)
this is nothing this extension will help you with as it only takes care of keeping your local files in sync with whats in the Databricks workspace

**Comment by RengarLee** [comment]
thanks

**Comment by fdescamps** [comment]
Hi @RengarLee and @gbrueckl 

I am in the same case as @RengarLee.
I don't find _where_ and _how_ to run my notebook on my cluster ?
(I have https://docs.databricks.com/dev-tools/databricks-connect.html OK _(confirmed by databricks-connect test)_) 
Could you give me some help ?

Thanks for all the work around this extension @gbrueckl 

Regards,

**Comment by fdescamps** [comment]
(may be we could re open the issue @gbrueckl ?)

**Comment by gbrueckl** [comment]
Hi @fdescamps,

As I said in my previous comments, the execution of the notebooks against a Databricks cluster has nothing to do with this extension. Also the configuration is different, so if you say that this extensions is working for you but you cannot execute your notebooks on the cluster then you should open a ticket at the databricks-connect tool and not here.

sorry, but I hope you understand that I cannot deal with issues that are not related to this repo
-gerhard

**Comment by aafendi** [comment]
Hey @fdescamps @RengarLee I am having the same issue and trying to find a solution. If you guys found a way to get this working or want to discuss I can drop my email here.

**Comment by fdescamps** [comment]
Hi

Not yet, but still have hope to find a way ;)
