### ISSUE TITLE
Not able to run the notebooks interactively

### ISSUE THREAD

**Issue by cvsekhar** [paiqo/Databricks-VSCode#54]
Hi,

I have installed the plugin and was able to get all the databricks functionality inside VSCode. But when I tried to run any one the notebooks , I am not able to display the cells. I have installed the jupyter notebook plugin thinking that is the missing one. Still the notebooks show up as HTML code.

**Comment by aafendi** [comment]
I have the same issue. It displays as cells when I double click the file tab, but that still seems stupid cause it opens the cell formatted view in a separate tab.

**Comment by gbrueckl** [comment]
to run the code against a Databricks cluster you need to use [dbconnect](https://docs.databricks.com/dev-tools/databricks-connect.html)
this is nothing this extension will help you with as it only takes care of keeping your local files in sync with whats in the Databricks workspace

please also have a look at other (already closed) tickets for more details
