### ISSUE TITLE
Can't know if the connection is successfull and if the workspace is being downloaded

### ISSUE THREAD

**Issue by Pawlowski123** [paiqo/Databricks-VSCode#55]
Hi team,

First of all thanks for the extension development, its really a huge contribution to the dev community.

I'm trying to set the VS Code with it, added the required parameters such as workspace URL and personal token and now I can see the alias I created with a green label (seems to be fine).

The problem is, when I click to download workspace, I understand it should download (like a pull request to my local directory) for the first time all the folders and files inside the workspace. But I can't see if that is happening, or if the connection is even working.

Can you help me with that?

Thanks!

**Comment by gbrueckl** [comment]
Hi @Pawlowski123 ,

can you check the logs? they probably reveal a lot more information on whats actually going on
just open the Output view and select `paiqo.databricks-vscode`
![image](https://user-images.githubusercontent.com/11884402/122401282-be44b400-cf7c-11eb-8b58-6ca12c108cac.png)

**Comment by Pawlowski123** [comment]
Hi @gbrueckl,

Indeed the output helped to understand what is going on. I'm getting the "API has not yet been initialized! Please connect first!" error.

This means the connection between the VSCode and the Workspace is not correct? I did not follow the MS doc to set the Databricks connect yet... just installed your extension

**Comment by gbrueckl** [comment]
this means that there is something wrong with your configuration of the VSCode extension
I would guess it either the `apiRootUrl` is wrong (should be something like `https://westeurope.azuredatabricks.net`) or the `personalAccessToken` (should be something like `dapi1234123123123`)

does the log reveal any additional information?

**Comment by Pawlowski123** [comment]
The workspace root URL does not have the deployment region subdomain, like westeurope, mine is a code like adb-2932193921.11.databricks.com, might this be an issue? I double-checked on the azure portal.

About the personaAccessToken, it is correctly placed on the settings, with the formar dapi...

**Comment by gbrueckl** [comment]
try `https://adb-2932193921.11.databricks.com` then please
maybe also recreating a new personal access token and add it again just to be sure

**Comment by Pawlowski123** [comment]
I omited the https:// but I was already using it. Just recreated the PAT and added it again, no success...

**Comment by gbrueckl** [comment]
can you post the logs?

**Comment by Pawlowski123** [comment]
Of course:

```
Loading Connections from 'databricks.connections' ...
Loading Connection from 'databricks.default.*' ...
Configuration SelfService_PROD: Property "useCodeCells" was not provided - using the default value "true"!
Setting 'databricks.lastActiveConnection' to 'SelfService_PROD' ...
Storing Personal Access Token in System KeyChain 'SelfService_PROD-API-Token' ...
API has not yet been initialized! Please connect first!
API has not yet been initialized! Please connect first!
```

**Comment by gbrueckl** [comment]
no row with `Activating Databricks connction xxx`?
may I ask which Operating system you are on?
as the last message is about Storing the personal access token, it could be related to the System Key Chain

**Comment by Pawlowski123** [comment]
I'm using a Windows 10 laptop. Is from my employee, no idea if could be some kind of lock about connecting to the ADB workspace due to that.

Just checked a few rows back on the log and found this:

```
Setting 'databricks.lastActiveConnection' to 'SelfService_PROD' ...
Activating Databricks Connection 'SelfService_PROD' ...
Initializing Databricks API Service ...
Getting Personal Access Token from System KeyChain 'SelfService_PROD-API-Token'
Testing new Databricks API settings ...
GET 2.0/dbfs/list
Params:{"params":{"path":"/"}}
Response: 
"<!doctype html><html><head><meta charset=\"utf-8\"/><meta http-equiv=\"Content-Language\" content=\"en\"/><title>Databricks - Sign In</title><meta name=\"viewport\" content=\"width=960\"/><link rel=\"icon\" type=\"image/png\" href=\"/favicon.ico\"/><meta http-equiv=\"content-type\" content=\"text/html; charset=UTF8\"/><link rel=\"icon\" href=\"favicon.ico\"></head><body class=\"light-mode\"><uses-legacy-bootstrap><div id=\"login-page\"></div></uses-legacy-bootstrap><script src=\"login/login.309d7a65.js\"></script></body></html>"
ERROR: TypeError: Cannot read property 'length' of undefined
API has not yet been initialized! Please connect first!
```

When I saw the length log I just thought it could be something with a too large string on the local path, so I changed to C:\folder and it seems to be downloading. Will let you know soon.

**Comment by gbrueckl** [comment]
so it is basically redirecting you to a login-page which indicates that something with your configuration is wrong - again, either `apiRootUrl` or `personalAccessToken`

if your check the JSON config it should contain the following two lines:
```
    "databricks.connection.default.apiRootUrl": "https://adb-12312365618971042.2.azuredatabricks.net",
    "databricks.connection.default.personalAccessToken": "dapi123123123123",
```

it could be that instead of the `personalAccessToken` you see `personalAccessTokenSecure` which is the reference to your systems secure password storage 
if you provide both, the `personalAccessToken` will be used and also overwrite the existing value in the secure password storage

**Comment by Pawlowski123** [comment]
It downloaded the files I have on the workspace, I can see the code. Next step is to understand how to see and run the cells with Ctrl+Enter as I do on the browser, I can only see with #MAGIC and #COMMAND when is not on the file language, and then set the remote cluster to run the job instead of my local CPU.

Since the next topics are not on this thread intention, feel free to close it if you might.

Thanks for the quick help!

**Comment by gbrueckl** [comment]
ok, great, good to hear it finally works
regarding running the code against the DAtabricks cluster you will need to install Databricks connect and set your Python environment up accordingly https://docs.databricks.com/dev-tools/databricks-connect.html
this is out of bounds of this extension
