### ISSUE TITLE
clusters is not iterable

### ISSUE THREAD

**Issue by urabenst** [paiqo/Databricks-VSCode#56]
Hi all,

I am really curious to give this extension a shot. However, I receive the error "clusters is not iterable" when I try to initially refresh my environments and can't connect to any env or cluster. 

databricks-connect works fine for me. Did I just misconfigure my settings.json?

This is my settings.json (the structure only, not the actual values ofc). It's a bit messy, since I tried different options and none of them worked:

```   "databricks.connection.default.organizationId": "1234",
    "databricks.connection.default.port": 15001,
    "databricks.connection.default.pythonInterpreter": "C:\\Util\\Anaconda3\\python.exe",
    "databricks.connection.default.databricksConnectJars": "c:\\util\\anaconda3\\lib\\site-packages\\pyspark\\jars",
    "databricks.connections": [
        {
            "apiRootUrl": "https://adb-123.1.azuredatabricks.net/",
            "displayName": "first instance",
            "localSyncFolder": "C:\\Users\\urabenst\\workspace\\databricks",
            "personalAccessToken": "123-2"
        },
        {
            "apiRootUrl": "https://adb-234.19.azuredatabricks.net/",
            "displayName": "second instance",
            "localSyncFolder": "C:\\Users\\urabenst\\workspace\\databricks",
            "personalAccessToken": "234-2"
        }
    ],
    "databricks.connection.default.exportFormats": 
    {
        "Scala": ".scala",
        "Python": ".py.ipynb",
        "SQL": ".sql",
        "R": ".r"
    },
    "databricks.connection.default.apiRootUrl": "https://adb-123.1.azuredatabricks.net/",
    "databricks.connection.default.displayName": "first instance",
    "databricks.connection.default.personalAccessToken": "123-2",
    "databricks.connection.default.localSyncFolder": "C:\\Users\\urabenst\\workspace\\databricks" 
```

**Comment by gbrueckl** [comment]
Can you ensure you are using the latest version from the VS Code gallery? Some of your config settings above do not exist/work anymore.

Another good sour e would be the output panel of the extensiin where each single API call is logged including the results.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: urabenst ***@***.***>
Sent: Monday, July 12, 2021 11:58:16 AM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] clusters is not iterable (#56)


Hi all,

I am really curious to give this extension a shot. However, I receive the error "clusters is not iterable" when I try to initially refresh my environments and can't connect to any env or cluster.

databricks-connect works fine for me. Did I just misconfigure my settings.json?

This is my settings.json (the structure only, not the actual values ofc). It's a bit messy, since I tried different options and none of them worked:

    "databricks.connection.default.port": 15001,
    "databricks.connection.default.pythonInterpreter": "C:\\Util\\Anaconda3\\python.exe",
    "databricks.connection.default.databricksConnectJars": "c:\\util\\anaconda3\\lib\\site-packages\\pyspark\\jars",
    "databricks.connections": [
        {
            "apiRootUrl": "https://adb-123.1.azuredatabricks.net/",
            "displayName": "first instance",
            "localSyncFolder": "C:\\Users\\urabenst\\workspace\\databricks",
            "personalAccessToken": "123-2"
        },
        {
            "apiRootUrl": "https://adb-234.19.azuredatabricks.net/",
            "displayName": "second instance",
            "localSyncFolder": "C:\\Users\\urabenst\\workspace\\databricks",
            "personalAccessToken": "234-2"
        }
    ],
    "databricks.connection.default.exportFormats":
    {
        "Scala": ".scala",
        "Python": ".py.ipynb",
        "SQL": ".sql",
        "R": ".r"
    },
    "databricks.connection.default.apiRootUrl": "https://adb-123.1.azuredatabricks.net/",
    "databricks.connection.default.displayName": "first instance",
    "databricks.connection.default.personalAccessToken": "123-2",
    "databricks.connection.default.localSyncFolder": "C:\\Users\\urabenst\\workspace\\databricks"

**Comment by urabenst** [comment]
Thanks for your reply! 

I have version 0.2.5 installed which is quite outdated, but the most current one available in vs code. Is there any possibility to install a more recent one?

![image](https://user-images.githubusercontent.com/39942780/125576270-9ef69b85-0e52-4785-a5cb-a2b5877d101e.png)

The only output I can see in the output panel is the following:

Logger initialized!
Validating settings ...
Settings validated!
Initializing Databricks API Service ...
Databricks API Service initialized!

**Comment by gbrueckl** [comment]
Weird, the most recent one should be 0.8.0
https://marketplace.visualstudio.com/items?itemName=paiqo.databricks-vscode
Maybe your VSCode version is also outdated and hence it cannot find/load the latest version of the extension?

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by urabenst** [comment]
Ok, that's been it. Thanks for your help and sorry for taking your time with such an issue :)

**Comment by gbrueckl** [comment]
No worries, glad we could solve this :)

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
