### ISSUE TITLE
Crashing on first launch

### ISSUE THREAD

**Issue by aescolastico** [paiqo/Databricks-VSCode#58]
After installing for the first time I see this error when attempting to add a connection. 

<img width="320" alt="image" src="https://user-images.githubusercontent.com/30540257/129281340-be124003-35d4-4d86-b406-9eaf479977cf.png">

This happens on macos and on windows. 
vs code ver: 1.59

Any ideas on what might be causing this? Does the extension generate any kind diagnostic data?

**Comment by gbrueckl** [comment]
Hi,

you can go to View -> Output and then selecth paiqo.databricks-vscode in the dropdown-box:
![image](https://user-images.githubusercontent.com/11884402/129551095-222d32d6-8f73-4c29-a6bb-7fe3a62b1eec.png)

this should reveal some more information on whats actually happening and potentially going wrong

unfortunately, as i do not have a Mac, I cannot really test this thoroughly :/

**Comment by gbrueckl** [comment]
closed due to inactivity and no feedback
