### ISSUE TITLE
Support for GCP?

### ISSUE THREAD

**Issue by bjeffrey92** [paiqo/Databricks-VSCode#61]
Do you support databricks instances built on google cloud provider? 

I can only see references to Azure and AWS in your documentation. I've tried to configure your extension to access my GCP databricks instance but none of the panes in the extension other than the top one have populated, and when I hover over the connection the box which appears says `CloudProvider: AWS`. Is there a way to change that to `CloudProvider: GCP`?

![Screenshot from 2021-10-07 12-09-08](https://user-images.githubusercontent.com/36240394/136373791-ccb8f8fb-0e44-44fa-9d83-275da4037439.jpg)

**Comment by bjeffrey92** [comment]
Thanks for your swift response @gbrueckl 

The `?o` is there because there is I have a workspace ID at the end of the URL (https://docs.databricks.com/workspace/workspace-details.html#workspace-instance-names-urls-and-ids). I entered the full URL with the workspace ID when I ran `databricks configure --token` and under `"databricks.connection.default.apiRootUrl"` in the vscode settings.json, but for some reason it doesn't show the full URL there.

This is the output, it is reporting an error. Any suggestions what to do about that?

```Logger initialized!
Trying to get config from Workspace settings ...
No Workspace settings found! Trying to get User-Settings instead ...
Initializing ConnectionManager CLI ...
Configuration DEFAULT: Property "localSyncSubfolders" was not provided - using the default value!
Configuration DEFAULT: Property "exportFormats" was not provided - using the default value!
Configuration DEFAULT: Property "useCodeCells" was not provided - using the default value "true"!
Setting 'databricks.lastActiveConnection' to 'DEFAULT' ...
Storing Personal Access Token in System KeyChain 'DEFAULT-API-Token' ...
Activating Databricks Connection 'DEFAULT' ...
Initializing Databricks API Service ...
Testing new Databricks API settings ...
GET 2.0/dbfs/list
Params:{"params":{"path":"/"}}
Response: 
"<!doctype html><html><head><meta charset=\"utf-8\"/><meta http-equiv=\"Content-Language\" content=\"en\"/><title>Databricks - Sign In</title><meta name=\"viewport\" content=\"width=960\"/><link rel=\"icon\" type=\"image/png\" href=\"/favicon.ico\"/><meta http-equiv=\"content-type\" content=\"text/html; charset=UTF8\"/><link rel=\"icon\" href=\"favicon.ico\"></head><body class=\"light-mode\"><uses-legacy-bootstrap><div id=\"login-page\"></div></uses-legacy-bootstrap><script src=\"login/login.956d9092.js\"></script></body></html>"
ERROR: TypeError: Cannot read property 'length' of undefined```

**Comment by satish-phchealth** [comment]
I tried to debug this and just to test locally, I disabled list operation on dbfs during initialization of the extension (which is where the extension failed for our GCP based databricks). After bypassing this, I was able to get rest of things working (workspace, clusters) including getting the notebook, running the notebook and starting the cluster. 

@gbrueckl I am not familiar with Typescript but looks like it is simple to add a flag in the extension to bypass this operation for GCP (until Databricks starts offering it). Suggestions? I can provide a PR if needed but would like your suggestions on best way to move forward.

**Comment by bjeffrey92** [comment]
@gbrueckl that sounds great, thanks for your help. Will v0.8.8 be released today?

**Comment by gbrueckl** [comment]
yes, it is in the gallery already, you may need to restart VS Code to trigger an update of the extension

**Comment by bjeffrey92** [comment]
Great, thanks.

The version without the `?o` at the end: `https://<...>.4.gcp.databricks.com`

**Comment by satish-phchealth** [comment]
Thanks, I am glad its working

**Comment by bjeffrey92** [comment]
I'll close this issue now that it's sorted. Thanks again for your help @gbrueckl and @satish-phchealth
