### ISSUE TITLE
Files are not downloaded in the correct format (Export formats)

### ISSUE THREAD

**Issue by AlexPapas** [paiqo/Databricks-VSCode#62]
I have all three below settings 

`"databricks.connection.default.exportFormats": { "Scala": ".scala", **"Python": ".py"**, "SQL": ".sql", "R": ".r" }`
and
` "databricks.connection.default.exportFormats": {
        "Scala": ".scala", "Python": ".py",
        "SQL": ".sql",
        "R": ".r"
    },`

and 

`		"databricks.connection.default.exportFormats": 
		{
			"Scala": ".scala",
			"Python": ".py.ipynb",
			"SQL": ".sql",
			"R": ".r"
		},`

But I am not able to get the modules as .py files. Only as ipynb.

This is how my file looks like:
![image](https://user-images.githubusercontent.com/29041538/136561824-d8e87a15-d236-44bc-9b92-8fc452f7bdad.png)

**Comment by gbrueckl** [comment]
thats exactly what the API returns and what you would also get if you use Export in the UI
what would you expect?

**Comment by AlexPapas** [comment]
Follow up question - is it possible to distinguish what will be a notebook file and which one will be a python file. The reason I am asking is that we want to import custom notebooks/python files from our same repo. But Databricks allows this with the %run /settings. If I download all files as .ipynb then the magic command does not work locally as the %run command imports only .py files. But if I download all files as .py then I cannot run the %run command in .py file to import other files.

**Comment by gbrueckl** [comment]
you are right, if a local file with any of the file extensions (.py or .ipynb) already exists, it will always be downloaded in that particular format. Thats also the best way how you can mix these file types
if no local file exists yet, the default exportFormat will be used which can be set via the configuration
