### ISSUE TITLE
Syncing both non-notebook as notebook Python files

### ISSUE THREAD

**Issue by mickvanhulst** [paiqo/Databricks-VSCode#64]
With the introduction of Repos, we can now finally import non-notebook Python files as shown in [0]. Now for some reason, these regular Python files are not downloaded, whereas my Notebook files are? I am not sure if this has to do with [1], but I tried that respective approach, but it is not working. I have both tried the default settings, both settings shown in [1] as well as the one below

```
  "databricks.connection.default.exportFormats": {
   "Scala": ".scala", "Python": ".py", "SQL": ".sql", "R": ".r" 
  }
```

Any idea why non-notebook files are not synced locally?

[0] https://docs.databricks.com/repos.html
[1] https://github.com/paiqo/Databricks-VSCode/issues/60

**Comment by gbrueckl** [comment]
Hi @mickvanhulst 
thanks for reporting this!
I just had a quick look and it seems that the repo-files are part of the file-listings (https://docs.databricks.com/dev-tools/api/latest/workspace.html#list) but cannot be downloaded/exported (https://docs.databricks.com/dev-tools/api/latest/workspace.html#export) yet. 
If I try to, I get
```
{"error":"DatabricksServiceException: INVALID_PARAMETER_VALUE: Path (/Repos/myuser@mydomain.at/Test_Databricks/README.md) is not a notebook."}
```

I added the files to the browser but we cannot provide the option to up-/download them yet as it is not supported by the Workspace API

**Comment by gbrueckl** [comment]
just published v0.8.9
it should be updated automatically

**Comment by mickvanhulst** [comment]
Hi @gbrueckl,

Thanks for the fast reply! Two questions from my side:
1. Does this mean that the settings, as shown above, no change from my side is needed for these files to be synced (once available through Databrick's API)? Besides obviously updating to v0.8.9
2. Any idea if there is a way to file this feature request and/or where we can find their roadmap regarding issues related to this? I realize this is somewhat of a wildcard, but given that you are actively maintaining this repository, it does not hurt to ask if you are more aware of recent developments.


Thanks for your contribution!

**Comment by gbrueckl** [comment]
regarding 1) 
once this is available through the API I probably need to do some further changes to the extension to make it work. your config should be fine as regular files will just be downloaded "as-is" with the existing file-extension. Of course, this all depends on what the new API is capable of.

regarding 2)
honestly I do not know. neither where to put feature requests nor the future road map of the REST API :(
most of the changes to the API are brought to me by feature requests like yours as I do not monitor changes to the REST API frequently

**Comment by mickvanhulst** [comment]
1. Thanks for letting me know!
2. That's a shame :(! I will see if I can file a feature request somewhere.

Thanks again for your contribution and the swift responses :)!

**Comment by mickvanhulst** [comment]
Hi @gbrueckl , 

I have been in contact with a DB engineer and it seems like the required features should be added this quarter :)!

Thanks for all the support!

**Comment by gbrueckl** [comment]
as of now, it is still not supported to download non-notebook files

**Comment by mickvanhulst-TomTom** [comment]
Can this potentially be supported using the new dbx tool? See https://dbx.readthedocs.io/en/latest/cli.html?highlight=sync#dbx-sync

**Comment by gbrueckl** [comment]
this feature was implemented for the new Filesystem `dbws:/` which you can mount into your VSCode solution explorer (https://github.com/paiqo/Databricks-VSCode#file-system-integration)

Browsing your Workspace from there also allows you to open non-notebook files and modify them

**Comment by mickvanhulst-TomTom** [comment]
Does this integrate with the notebook functionality? Meaning, if I make changes to non-notebook files, the notebooks that import these packages can actually use these changed files? Something like that which is described here: https://dbx.readthedocs.io/en/latest/guides/python/devloop/mixed/#using-dbx-sync-repo-for-local-to-repo-synchronization (**Note** that the main downside of what is described for `dbx` is that I still need to switch to DB to run my  notebooks, whereas in this case I can run the notebook from my VSCode)

**Comment by gbrueckl** [comment]
If you are in live-mode (by mounting `dbws:/Repos/me@mydomain.com/myRepo` in your VSCode workspace and use VSCode Explorer to open your notebooks and library-files, it uploads the files to databricks as soon as you save them. So if you save a library file and reference/import it in a notebook afterwards it will have the changes from your library-file
(for safety you should wait a couple of seconds though)

If you use the Databricks Workspace Browser in VSCode it is currently not supported to download library-files so it will not work there

**Comment by gbrueckl** [comment]
Workspace Browser and File System Integration should now both work also with non-notebook files just the same way as it does for notebooks
could you please test again, thanks
