### ISSUE TITLE
get detailed tasks info when `MULTI_TASK`

### ISSUE THREAD

**Issue by copdips** [paiqo/Databricks-VSCode#69]
hello,

I have a databricks service in Azure,

If the job has a single task, the `json definition` of the extension gives everything:

![image](https://user-images.githubusercontent.com/13083856/154581131-8f2d9bba-4213-4b56-ab25-fee9ee6579f9.png)

```json
{
	"job_id": 111111,
	"settings": {
		"name": "xxxxx",
		"new_cluster": {
			"spark_version": "9.1.x-cpu-ml-scala2.12",
			"spark_conf": {
				"spark.databricks.delta.preview.enabled": "true"
			},
			"node_type_id": "xxxs",
			"enable_elastic_disk": true,
			"azure_attributes": {
				"availability": "ON_DEMAND_AZURE"
			},
			"num_workers": 1
		},
		"libraries": [
			{
				"whl": "dbfs:/dbx/xxx.whl"
			}
		],
		"email_notifications": {},
		"timeout_seconds": 0,
		"spark_python_task": {
			"python_file": "dbfs:/dbx/xxx/xxx/artifacts/xxx/xx.py",
			"parameters": []
		},
		"max_concurrent_runs": 1,
		"format": "SINGLE_TASK"
	},
	"created_time": 1645005111842,
	"creator_user_name": "xxxxx"
}
```

But if the job has multi-tasks, the `json definition` gives only `"format": "MULTI_TASK"`, it would be nice if we can have more info.

```json
{
	"job_id": 11111,
	"settings": {
		"name": "xxxx",
		"email_notifications": {},
		"timeout_seconds": 0,
		"max_concurrent_runs": 2,
		"format": "MULTI_TASK"
	},
	"created_time": 1644483934666,
	"creator_user_name": "xxxxx"
}
```

**Comment by gbrueckl** [comment]
I think I know what the problem here is - the extension currently still uses jobs API v2.0 which does not support multi-step jobs
need to change it to use jobs API v2.1 
will probably do it in the next few days and update you here

**Comment by copdips** [comment]
@gbrueckl
is it possible to realse a new extension version with job api v2.1 ?

**Comment by copdips** [comment]
great , works like a charm, thanks a lot 💯
