### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by drkg4b** [paiqo/Databricks-VSCode#7]
I get this error and cannot see anything in the extension. The developer tool console didn't help me too much and I could use expert advice. This is the output of the error related to the extension:

`
Extension 'paiqo.databricks-vscode cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)

  | updateEnableProposedApi | @ | abstractExtensionService.ts:485
-- | -- | -- | --
  | _checkEnableProposedApi | @ | abstractExtensionService.ts:274
  | _deltaExtensions | @ | extensionService.ts:224
`

`
Error: Request failed with status code 400
	at createError (c:\Users\Gabriele\.vscode\extensions\paiqo.databricks-vscode-0.2.0\node_modules\axios\lib\core\createError.js:16:15)
	at settle (c:\Users\Gabriele\.vscode\extensions\paiqo.databricks-vscode-0.2.0\node_modules\axios\lib\core\settle.js:17:12)
	at IncomingMessage.handleStreamEnd (c:\Users\Gabriele\.vscode\extensions\paiqo.databricks-vscode-0.2.0\node_modules\axios\lib\adapters\http.js:236:11)
	at IncomingMessage.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)

onDidChangeNotification | @ | notificationsAlerts.ts:38
-- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:26
  | fire | @ | event.ts:587
  | addNotification | @ | notifications.ts:183
  | error | @ | notificationService.ts:57
  | (anonymous) | @ | mainThreadTreeViews.ts:178
  | processTicksAndRejections | @ | internal/process/task_queues.js:85
`

These are my settings:

`
"databricks.connection.default.apiRootUrl": "https://********.azuredatabricks.net/",
    "databricks.connection.default.displayName": "***_****_***",
    "databricks.connection.default.localSyncFolder": "C:\\Users\\Gabriele\\Desktop\\projects\\databricks",
    "databricks.connection.default.personalAccessToken": "dapixxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "databricks.connection.default.databricksConnectJars": "c:\\users\\gabriele\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\pyspark\\jars",
    "databricks.connection.default.organizationId": "xxxxxxxxxxxxxxxxxx",
    "databricks.connection.default.port": 15001,
`

Any clue of what is going on? Databricks-connect is working fine

Thanks,
Gabriele

**Comment by gbrueckl** [comment]
can you please try again with the just released v0.2.5

**Comment by drkg4b** [comment]
@gbrueckl Thanks for answering! I still see the same problem and honestly wouldn't know where to start debugging:

`Error: Request failed with status code 400
	at createError (c:\Users\Gabriele.Bertoli\.vscode\extensions\paiqo.databricks-vscode-0.2.5\node_modules\axios\lib\core\createError.js:16:15)
	at settle (c:\Users\Gabriele.Bertoli\.vscode\extensions\paiqo.databricks-vscode-0.2.5\node_modules\axios\lib\core\settle.js:17:12)
	at IncomingMessage.handleStreamEnd (c:\Users\Gabriele.Bertoli\.vscode\extensions\paiqo.databricks-vscode-0.2.5\node_modules\axios\lib\adapters\http.js:236:11)
	at IncomingMessage.emit (events.js:208:15)
	at endReadableNT (_stream_readable.js:1168:12)
	at processTicksAndRejections (internal/process/task_queues.js:77:11)`

**Comment by gbrueckl** [comment]
can you please check the various output of VS Code if you find any more information there?
![image](https://user-images.githubusercontent.com/11884402/76647736-a8686800-655d-11ea-8aa7-80886c90c80f.png)
I recently added a separate output channel for this extension but all the others may also reveal some information

**Comment by drkg4b** [comment]
Same output as you:

`Logger initialized!
Validating settings ...
Settings validated!
Initializing Databricks API Service ...
Databricks API Service initialized!`

is there any way I can debug this? Without more information is going to be hard to figure out what's going on

**Comment by gbrueckl** [comment]
you should be able to download this whole repository, open it in VS Code and simply press F5 to run/debug it

did you also check the other output channels? e.g. "Extensions"?

**Comment by gbrueckl** [comment]
just published v0.3.0 where I also explicitly set "enableProposedApi": false
would be great if you could try it again

**Comment by drkg4b** [comment]
Hi unfortunately I still have the same issue, do you have any suspicion on what could cause the error?

**Comment by gbrueckl** [comment]
to be honest I have no idea
you could try to disable any other extensions except Python and this one
maybe there is a compatibility issue with any of the other extensions

**Comment by drkg4b** [comment]
I tried that too, but it's no use. I cloned the project and tried to run it through the debugger, but I never did that so I'm not sure about the procedure and I'm getting the `ECONNREFUSED localhost:5870` error

**Comment by gbrueckl** [comment]
maybe some network/firewall issue or permission issue on your local machine?

**Comment by drkg4b** [comment]
Hi, I tried today after some time and the issue resolved itself. Don't know unfortunately what changed but this can be closed!

**Comment by gbrueckl** [comment]
ok, great!
actually there were a couple of changes which were released recently and could potentially have fixed this issue :)
