### ISSUE TITLE
Opening Scala notebook in VSCode

### ISSUE THREAD

**Issue by fernando2393** [paiqo/Databricks-VSCode#74]
Hi!

I might have missed how to do so, but is it possible to download a scala notebook as a notebook on my local device and work with it in this format?

According to this:
`
		"databricks.connection.default.exportFormats": 
		{
			"Scala": ".scala",
			"Python": ".py.ipynb",
			"SQL": ".sql",
			"R": ".r"
		}
`
> Each filetype can either be exported as raw/source file (.scala, .py, .sql, .r) or as a notebook (.scala.ipynb, .py.ipynb, .sql.ipynb, .r.ipynb). This is also very important if you want to upload a local file as these also have to match these extension and will be ignored otherwise!

It should be supported. Nevertheless, when I try to change the value of the Scala field, it tells me that ".scala" is the only supported value. I was wondering if I am missing something or whether this functionality is not available at the moment.

Thanks in advance

**Comment by gbrueckl** [comment]
no, you are not missing something, the documentation is just not up-to-date anymore.

So Scala-Notebooks cannot be exported as Notebooks - you will realize that this is also not possible via the Databricks Web-UI
The export as notebook is only possible if the default-language of the notebook is set to Python 

You can work around this by simply switching the default language to Python instead. It will automatically add `%scala` magics to all cells then. That notebook can then be downloaded as `.ipynb` file but it will still contain all the `%scala` magics at the top of each cell
