### ISSUE TITLE
Setting exportFormats>Python to ".py" incorrectly exports Workspace Python notebooks as ".ipynb"

### ISSUE THREAD

**Issue by TimTheinAtTabs** [paiqo/Databricks-VSCode#77]
I have set in my User settings to export Python files as ".py" files instead of ".ipynb" files for a connection under "databricks.connections", but the Python files are downloading as ".ipynb" files. Is this a bug in v0.9.3?

**Comment by gbrueckl** [comment]
if a local `.ipynb` file already exists, it will keep downloading the file as `.ipynb`
if no local file exists yet, it will/should download it using the extension you specified 

can you check if a local `.ipynb` file already exists? otherwise I assume it is indeed a bug and I will investigate

**Comment by TimTheinAtTabs** [comment]
Local `.ipynb` file did not exist. I changed the localSyncFolder for the same connection to a non-existing path and it downloaded the file as  `.ipynb`. This appears to be a bug now.

**Comment by TimTheinAtTabs** [comment]
The setting is working again. I had one connection when I wrote this bug report, but after adding two more connections, I discovered the bug is now gone. I wonder if there may be some caching issue because I had five connections before, and the setting was not working then. I thought it may have been the localSyncFolder, because I changed that value too. I'm not sure anymore now. I will keep a lookout for the bug.

**Comment by gbrueckl** [comment]
yes, so those settings cannot be changed on the file
if you change the export formats for a given connection in your settings, you need to switch the connection once and then back to the one you changed (Assuming it was the active one)
so those changes only take effect when the connection is activated again
or if you restart VSCode

**Comment by TimTheinAtTabs** [comment]
Thanks for the confirmation. It would be helpful to others if you could add this detail to the documentation. For now, I will keep an eye on it.

**Comment by gbrueckl** [comment]
those settings are usually only done once at the very beginning and should not change very frequently

but sure, will add a note to the docs
