### ISSUE TITLE
Feature request: Environment variable support in localSyncFolder setting

### ISSUE THREAD

**Issue by TimTheinAtTabs** [paiqo/Databricks-VSCode#78]
Because I sync my vscode user settings across two machines, and my home folder path is different on both machines, and I wanted to place my localSyncFolder under my home folder on both machines, I tried to set localSyncFolder to "${env:HOMEPATH}\Databricks_sync" but it seems [environment variables](https://vscode-eastus.azurewebsites.net/docs/editor/variables-reference) are not supported for that setting.

Could this feature please be added soon?

**Comment by gbrueckl** [comment]
added support for environment variables in `localSyncPath` but you need to use cmd/bash syntax and not PowerShell syntax
e.g. `%HOMEPATH%\Databricks_sync` 
actually you should use `%USERPROFILE%\Databricks_sync`  as `%HOMEPATH%` does not contain the drive letter

**Comment by TimTheinAtTabs** [comment]
I have updated to 0.9.4 and your added support does not seem to work. When I refresh the WORKSPACE area, I see error, "EPERM: operation not permitted, mkdir '%USERPROFILE%\Databricks_sync\Workspace'.

**Comment by gbrueckl** [comment]
thanks for the confirmation 
please close the ticket if it works for you now, thanks!
