### ISSUE TITLE
databricks-connect vs dbx?

### ISSUE THREAD

**Issue by wshayes** [paiqo/Databricks-VSCode#79]
Looks like [databricks-connect](https://docs.databricks.com/dev-tools/databricks-connect.html) is deprecated in favor of [dbx](https://github.com/databrickslabs/dbx).

Are there any instructions for using dbx with databricks vscode?

**Comment by gbrueckl** [comment]
There has never been a direct dependency between this VSCode extension and databricks-connect and there will also be no dependency to dbx.
Honestly I do not really think that dbx helps a lot with local development and is a step backwards from databricks-connect

I am thinking of a new feature for the VSCode extension in the future that allows you to run some python code directly on an existing Databricks cluster (similar to databricks-connect) but there is nothing too share yet

**Comment by mickvanhulst** [comment]
Agree that being able to run Python code directly on an existing (and active) Databricks cluster would be more valuable. As it stands, I am unsure if dbx allows for persistence of its state across your `run` commands. If I have to run all my cells after every change, then it is going to be costly when debugging larger pipelines.

**Comment by gbrueckl** [comment]
So I finally implemented this feature in v1.0.0 of this extension. It is not officially released to the VSCode gallery yet but only in this repo. You can download the `.vsix` file here: https://github.com/paiqo/Databricks-VSCode/releases/tag/v1.0.0

Every running cluster should show up automatically as a new Kernel in your Jupyter notebook. Please also see the readme for details https://github.com/paiqo/Databricks-VSCode#notebook-kernel

Feedback is highly appreciated!

**Comment by gbrueckl** [comment]
So I finally implemented this feature in v1.0.0 of this extension. It is not officially released to the VSCode gallery yet but only in this repo. You can download the .vsix file here: https://github.com/paiqo/Databricks-VSCode/releases/tag/v1.0.0

Every running cluster should show up automatically as a new Kernel in your Jupyter notebook. Please also see the readme for details https://github.com/paiqo/Databricks-VSCode#notebook-kernel

Feedback is highly appreciated!

**Comment by gbrueckl** [comment]
the code to run local Notebooks against a Databricks Cluster was released with v1.0.0. which is now also available via the VSCode Gallery 
-> closing this ticket
