### ISSUE TITLE
Fresh install causes extension host to fail

### ISSUE THREAD

**Issue by aescolastico** [paiqo/Databricks-VSCode#81]
Installing the extension causes all extensions to fail with the following error.

 Extension host cannot start: version mismatch.

I can provide diagnostics, if needed. Just need to know where to grab those.

**Comment by gbrueckl** [comment]
hi, are you actually sure this is related to this extension? 
I just tried the same and it worked just fine in my environment

to get diagnostics, please open the output pane and select Extension host:
![image](https://user-images.githubusercontent.com/11884402/172943265-1bbdfd06-349a-4123-ba6f-03b24750079e.png)

this should provide a lot more information for what could have potentially gone wrong
you may also want the check the other built-in output channels or the one specific to the Databricks extension

**Comment by aescolastico** [comment]
Unfortunately the Output channels dont contain anything. They are blank. There are dev console errors. Would any of those be helpful?

Im pretty certain its the extension. It happens when I open the Databricks extension pane. And it dissapears when I uninstall the extension. And reappears on reinstall. It also happens on two different PCs. One running windows 11, the other running macos. The mac has other vscode extensions on it. The windows, install does not. It is a fresh install with no non-default configs. Here is a clip of the behavior.

https://user-images.githubusercontent.com/30540257/172963647-74f8ad0c-9a01-4404-9582-d3df8a9441fc.mov

**Comment by gbrueckl** [comment]
does the issue persist if you actually configure a connection?
you can do this via the VS Code settings UI or in the JSON file directly as described here https://github.com/paiqo/Databricks-VSCode#setup-and-configuration-vscode-connection-manager

**Comment by aescolastico** [comment]
That actually does resolve the issue. The extension host no longer crashes meaning my other extensions are working again, and the databricks extension seems to be working as intended as well. Thanks!

**Comment by gbrueckl** [comment]
ok, great that this is resolved now - I will investigate why having no connections configured could cause an issue
