### ISSUE TITLE
run Spark on Databricks 

### ISSUE THREAD

**Issue by ofirmgr** [paiqo/Databricks-VSCode#82]
Can I run Spark on Databricks server other than on my local machine?

**Comment by gbrueckl** [comment]
you can also run Spark on your local machine yes, if that is your question
but it will be different from running your code directly on Databricks due to different versions of different libraries

**Comment by ofirmgr** [comment]
I"m using Azure Databricks . I use the Databrick portal to run Spark (*.azuredatabricks.net).
I tried to run Spark with Databricks-VSCODE extension (Execute cell) but it run Spark locally instead of on Azure Databricks cluster.
My question is how do I run Spark on Azure Databricks cluster with the Databricks-VSCODE extension?

**Comment by gbrueckl** [comment]
ok, got it - that is actually a very common feature request - for obvious reasons
However, in general, this is not (yet) covered by this extension 
there is already a similar ticket open https://github.com/paiqo/Databricks-VSCode/issues/79 
the official way used to be [databricks-connect](https://docs.databricks.com/dev-tools/databricks-connect.html) but it got deprecated recently
As I mentioned there, I am working on a way to allow execution of local code against a running databricks cluster - I will post updates in the ticket linked above and closing this one for now
