### ISSUE TITLE
Debugging via ipykernel

### ISSUE THREAD

**Issue by benedikt-mayer** [paiqo/Databricks-VSCode#86]
Hi!
Thank you very much for this great extension!

On top if this:
VS Code supports debugging via the ipykernel, even on remote machines:
https://github.com/microsoft/vscode-jupyter/wiki/Setting-Up-Run-by-Line-and-Debugging-for-Notebooks

Databricks now uses the ipykernel:
> In Databricks Runtime 11.0 and above, Python notebooks use the IPython kernel to execute Python code.
https://docs.microsoft.com/en-us/azure/databricks/notebooks/ipython-kernel

even with an appropriate version:
![image](https://user-images.githubusercontent.com/42207135/183419589-abb0b6cd-0e8c-4e72-a7ec-298afca64556.png)

Now if I select `Debug Cell` with a Databricks kernel, it sends me to the `change kernel` Dialog.
Do you think it would be possible to enable this debugging through the extension?

**Comment by gbrueckl** [comment]
thats actually a very good question!
as of now we are using the Databricks Execution API to run the code and wrapped a VSCode Notebook Kernel around it. So we are not actually using a "real" Jupyter Kernel hence the debugging will currently not work.
But I will definitely also look into this as it would obviously also have some benefits using that approach

unfortunately the documentation I could find about it is very sparse, not to say non-existent - but I will ask my peers at Databricks and Microsoft about some more insights - so please stay tuned!

**Comment by gbrueckl** [comment]
according to the information I got, this IPython kernel is currently not accessible from outside but only used internally 
so I guess for now we cannot use/connect to it

will close this ticket for now but keeping this in mind if it changes in the future!

**Comment by benedikt-mayer** [comment]
Not sure if this is the necessary change, but with Runtime 11.2 and up, the Python debugger (pdb) is available:
https://learn.microsoft.com/en-us/azure/databricks/languages/python#--debug-in-python-notebooks
https://learn.microsoft.com/en-us/azure/databricks/_static/notebooks/python-debugger.html

**Comment by gbrueckl** [comment]
so we are currently not using the IPython kernel to run our notebooks from VSCode against the DAtabricks cluster but instead we use the (quite old) [Commands API](https://docs.databricks.com/dev-tools/api/1.2/index.html#run-a-command)

I doubt that `%debug` or `$pdb on` will be supported via the Commands API hence I also do not think it will be of any use for us

**Comment by benedikt-mayer** [comment]
Thanks for the quick clarification! Let's hope that maybe in the future Databricks will make the kernel available 😃.

**Comment by gbrueckl** [comment]
yes, I guess that would be the easiest for all :D
