### ISSUE TITLE
Notebook Kernel not created

### ISSUE THREAD

**Issue by skamalj** [paiqo/Databricks-VSCode#87]
I am working on Windows Subsystem for Linux - Ubuntu 20. Connection works ok and I can see all artifacts. Import of notebooks to sync folder works as well.
But databricks cluster kernel is not listed/created to work locally.

**Comment by gbrueckl** [comment]
I could not think of any reason why Databricks notebook kernels should not work in WSL.
Can you assure the following things also:
- you use v1.0.0 or above
- you have opened the cluster tab and you see a list of clusters
- at least one cluster is RUNNING

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Kamal ***@***.***>
Sent: Tuesday, August 9, 2022 5:00:35 PM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] Notebook Kernel not created (Issue #87)


I am working on Windows Subsystem for Linux - Ubuntu 20. Connection works ok and I can see all artifacts. Import of notebooks to sync folder works as well.
But databricks cluster kernel is not listed/created to work locally.

**Comment by gbrueckl** [comment]
please check again with the latest version as it contains a lot of improvements with regards to your issue
if there is still a problem, please open a new ticket
