### ISSUE TITLE
Pull button

### ISSUE THREAD

**Issue by dsfrederic** [paiqo/Databricks-VSCode#88]
Is it possible to add a simple "PULL" button? 

I just want the functionality to pull the active branch to the latest version. 
![image](https://user-images.githubusercontent.com/28486949/183700743-bf8ebd3e-a133-4edf-b8e8-d07352c8dc6d.png)

**Comment by gbrueckl** [comment]
Good point, will add it in the next release!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Frédéric De Smet ***@***.***>
Sent: Tuesday, August 9, 2022 5:58:30 PM
To: paiqo/Databricks-VSCode ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [paiqo/Databricks-VSCode] Pull button (Issue #88)


Is it possible to add a simple "PULL" button?

I just want the functionality to pull the active branch to the latest version.
[image]<https://user-images.githubusercontent.com/28486949/183700743-bf8ebd3e-a133-4edf-b8e8-d07352c8dc6d.png>

**Comment by gbrueckl** [comment]
v1.1.0 is now available for download from this github repo
https://github.com/paiqo/Databricks-VSCode/releases/tag/v1.1.0

It is not yet published to the VSCode gallery so please install in manually and run your tests 

PS: it also includes a lot of other new features!

**Comment by gbrueckl** [comment]
this has been released some time ago already - if it is still an issue, please open another ticket
