### ISSUE TITLE
Azure databricks issue : ERROR: TypeError: Cannot read properties of undefined (reading 'data')

### ISSUE THREAD

**Issue by ashitabh** [paiqo/Databricks-VSCode#89]
I have checked the URL and PAT token, and its working in POSTMAN
![image](https://user-images.githubusercontent.com/16971797/184934814-a19c8025-cd1f-481d-860c-9d36221fda15.png)

However, in VS Code, I am getting the following error 

Initializing ConnectionManager VSCode ...
Loading Connections from 'databricks.connections' ...
Loading Connection from 'databricks.default.*' ...
Configuration dev: Property "localSyncSubfolders" was not provided - using the default value!
Configuration dev: Property "useCodeCells" was not provided - using the default value "true"!
Setting 'databricks.lastActiveConnection' to 'dev' ...
Storing Personal Access Token in System KeyChain 'dev-API-Token' ...
Activating Databricks Connection 'dev' ...
Initializing Databricks API Service ...
Testing new Databricks API (https://eastus2.azuredatabricks.net) settings ()...
GET 2.0/workspace/list
Params:{"params":{"path":"/"}}
ERROR: TypeError: Cannot read properties of undefined (reading 'data')

**Comment by ashitabh** [comment]
No issues, running VS code behind company proxy needs the following command parameters 
code --proxy-server="http://user:password@myorgproxy.com:800/"
Its working for me now

**Comment by gbrueckl** [comment]
you may also try to set those directly via the VSCode settings
![image](https://user-images.githubusercontent.com/11884402/185054107-ac4d205c-25d7-40d9-9409-c7a0c99f99f5.png)
not sure though if this also works with username/pw, but the proxy-setting itself is supported by the extension

-gerhard
