### ISSUE TITLE
Can no longer select local Python kernel with version 1.0.0

### ISSUE THREAD

**Issue by sebastienlanglois** [paiqo/Databricks-VSCode#91]
Hi!

When using this extension with version 1.0.0, I'm able to select and run code on running Databricks clusters. However, in some instance, I would prefer to run code locally (for instance, when I need a library not yet installed in a Databricks cluster). Unfortunately, it seems that when trying to select other kernels, only Databricks clusters are available to select and I can't see local Python kernels anymore (just after updating to version 1.0.0)

Any idea if it's possible to display local kernels again?

Thank you very much!

**Comment by gbrueckl** [comment]
that sounds weird as we dont do anything with existing kernels but just add new ones for Databricks 

it could though happen, that if you have a lot of Databricks clusters running, the Kernels that get created somehow overflow the list and push the local kernels to the back!?

can you try the command "Jupyter: Filter Kernels" to see if they are still there?

**Comment by gbrueckl** [comment]
any update on this @sebastienlanglois ?

**Comment by gbrueckl** [comment]
closing due to missing feedback

**Comment by hansharhoffbestseller** [comment]
Just FYI, I had a similar problem and by filtering some kernels as suggested I was suddenly able to see the relevant venv. Before filtering I only say my base python image and the remote cluster.
