### ISSUE TITLE
Show Pandas DataFrame in Databricks Notebook Issue

### ISSUE THREAD

**Issue by mrakelinggar** [paiqo/Databricks-VSCode#92]
Hi

First of all, I am loving this extension!

However I am facing issues when displaying pandas dataframe from Databricks Notebooks.

![image](https://user-images.githubusercontent.com/8598185/186573468-7db78fe8-7c20-4242-97ab-f7cbf64a1913.png)

it just shows the HTML format. 

When I use the `display` function it displays as a JSON

![image](https://user-images.githubusercontent.com/8598185/186573657-4930a13c-bce6-4536-8481-f9a03e31ecc1.png)

Plz help. This is a very helpful extension and it would be of great to develop Python Notebooks in VS Code compared to Databricks web UI

**Comment by gbrueckl** [comment]
this will be fixed in the next version which will be released within the next days

**Comment by gbrueckl** [comment]
v1.1.0 is now available for download from this github repo
https://github.com/paiqo/Databricks-VSCode/releases/tag/v1.1.0

It is not yet published to the VSCode gallery so please install in manually and run your tests 

PS: it also includes a lot of other new features!

**Comment by gbrueckl** [comment]
this has been released some time ago already - if it is still an issue, please open another ticket
