### ISSUE TITLE
Expose cluster kernels to quarto

### ISSUE THREAD

**Issue by runkelcorey** [paiqo/Databricks-VSCode#95]
Tools that work on top of Jupyter (papermill, quarto, etc) [allow users to specify kernels for rendering](https://quarto.org/docs/computations/python.html#kernel-selection). Currently, I can't find the running cluster kernels that I see in the Jupiter kernel selection. I think that exposing these kernels (or at least paths) would enable revealjs presentations—a killer application of Quarto—to include figures and code run against the cluster and using hive metastore data.

Are cluster kernels located in an easy-to-call directory? Would their names be persistent over cluster sessions and VS Code sessions?

**Comment by gbrueckl** [comment]
so the Databricks Kernels are no "real" Jupiter kernels. They use the [Notebook API in VSCode](https://code.visualstudio.com/api/extension-guides/notebook) to mimic a Jupyter Kernel hence they can only be used within VSCode 
They are always created on the fly when you start VSCode and activate the extension (e.g. by opening a notebook)

not sure if this works for your scenario

if the tools you mentioned (papermill, quarto, ...) just produce specific output that needs to be rendered accordingly, the should be implemented as dedicated [Notebook Renderers](https://code.visualstudio.com/api/extension-guides/notebook#notebook-renderer)

**Comment by runkelcorey** [comment]
Thanks for the info. I recognize now that your work has been limited to exposing the cluster kernels to VS Code. Are you saying that, were these other tools to have a dedicated notebook renderer in VS Code, then that notebook could select Databricks kernel clusters?

**Comment by gbrueckl** [comment]
as I understood it, the tools you mentioned produce some specific output which you want to visualize as output of the notebook then, correct?
in that case we would need a renderer extensions to parse and display the output properly

**Comment by gbrueckl** [comment]
closing as I think all questions were answered
