### ISSUE TITLE
Missing repos

### ISSUE THREAD

**Issue by arvkevi** [paiqo/Databricks-VSCode#96]
Thanks for developing this extension, I find it very useful.

The Repo Manager does not show all the users' Repos for my organization. When I run the command below, using the databricks cli tool, the user directories (and one directory named "dev") match exactly with repos listed in the Repo Manager. However there are many more directories in Databricks that don't show up in the Repo Manager. My first thought was that this could be related to pagination? I noticed that `next_page_token` [is defined in the extension's source code](https://github.com/paiqo/Databricks-VSCode/blob/6ac743bfd35b3a658ede2aaa0225d8b4a65be7ff/src/databricksApi/_types.ts#L36), but Iam unsure how it it used. If this is a bug, I'm happy to help in any way, but I don't have much experience with typescript. Thanks for reading.

```bash
$ databricks repos list --path-prefix /Repos | grep path | awk '{print $2}' | awk -F '/' '{print $3}' | sort | uniq

user1@email.com
user2@email.com
dev
user3@email.com
user4@email.com
user5@email.com
user6@email.com
user7@email.com
user8@email.com
user9@email.com
user10@email.com
user11@email.com
``` 

These match exactly the repos listed in Repo Manager ^

**Comment by gbrueckl** [comment]
Hi and thanks for reporting this issues
even though the `next_page_token` is there in the definition of the API response, it was not actually used when querying the API

I just implemented it and ran some basic tests on my side (e.g. creating 20+ repos and see if it still works) which was successful

The fix will be released then in the next few days!

**Comment by gbrueckl** [comment]
the fix was just deployed today with v1.1.4!

@arvkevi please test it again and report back here

**Comment by arvkevi** [comment]
The fix worked, thanks again @gbrueckl!

**Comment by gbrueckl** [comment]
closed as fixed
