### ISSUE TITLE
How to read local files while using databricks cluster?

### ISSUE THREAD

**Issue by shaikmoeed** [paiqo/Databricks-VSCode#97]
Hi Team, 

How to read/access local files/folders (.py files to import modules/ csv files to read data) from notebooks when using databricks cluster as kernel in VSCode?

My environment details:
Databricks VSCode - v1.1.4
WSL2
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:          20.04
Codename:       focal

**Comment by gbrueckl** [comment]
simply answer is you cannot use local files when running the code on the databticks cluster as it is running in the cloud and has no access to your local resources
what you can do instead is to upload your local files to the DBFS using the [DBFS Browser ](https://github.com/paiqo/Databricks-VSCode#dbfs-browser) or by mounting `dbfs:/` into your VSCode Workspace as described [here ](https://github.com/paiqo/Databricks-VSCode#file-system-integration) and then simply drag&drop local files to DBFS (or the other way round)
